// Test script to verify JS_POOL entries
const entries = [
  // string
  { declaration: '"Alice"', type: 'string', difficulty: 'easy' },
  { declaration: '"hello"', type: 'string', difficulty: 'easy' },
  { declaration: '"user@example.com"', type: 'string', difficulty: 'easy' },
  { declaration: '"Berlin"', type: 'string', difficulty: 'easy' },
  { declaration: '"Loading..."', type: 'string', difficulty: 'easy' },
  { declaration: '"Submit"', type: 'string', difficulty: 'easy' },
  { declaration: '"Tokyo"', type: 'string', difficulty: 'easy' },
  { declaration: '"password"', type: 'string', difficulty: 'easy' },
  { declaration: '"#FF0000"', type: 'string', difficulty: 'easy' },
  { declaration: '"2024-01-01"', type: 'string', difficulty: 'easy' },
  { declaration: '"42"', type: 'string', difficulty: 'medium' },
  { declaration: '""', type: 'string', difficulty: 'medium' },
  { declaration: '"0"', type: 'string', difficulty: 'medium' },
  { declaration: '"3.14"', type: 'string', difficulty: 'medium' },
  { declaration: '"false"', type: 'string', difficulty: 'medium' },
  { declaration: '" "', type: 'string', difficulty: 'medium' },
  { declaration: '"1"', type: 'string', difficulty: 'medium' },
  { declaration: '"hello".slice(0, 3)', type: 'string', difficulty: 'medium' },
  { declaration: '"hello " + "world"', type: 'string', difficulty: 'medium' },
  { declaration: '"true"', type: 'string', difficulty: 'hard' },
  { declaration: '"null"', type: 'string', difficulty: 'hard' },
  { declaration: '"undefined"', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof 42', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof []', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof null', type: 'string', difficulty: 'hard' },
  { declaration: '"NaN"', type: 'string', difficulty: 'hard' },
  { declaration: '"Infinity"', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof {}', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof undefined', type: 'string', difficulty: 'hard' },
  { declaration: 'String(42)', type: 'string', difficulty: 'hard' },
  { declaration: '(42).toString()', type: 'string', difficulty: 'hard' },
  { declaration: 'JSON.stringify(1)', type: 'string', difficulty: 'hard' },
  { declaration: '[1].join()', type: 'string', difficulty: 'hard' },
  { declaration: 'String(true)', type: 'string', difficulty: 'hard' },
  { declaration: '1 && "hello"', type: 'string', difficulty: 'hard' },
  { declaration: 'null || "default"', type: 'string', difficulty: 'hard' },
  { declaration: '"" ?? "backup"', type: 'string', difficulty: 'hard' },
  { declaration: 'false ? 1 : "no"', type: 'string', difficulty: 'hard' },
  { declaration: '[] ? "yes" : 0', type: 'string', difficulty: 'hard' },
  // number
  { declaration: '42', type: 'number', difficulty: 'easy' },
  { declaration: '3.14', type: 'number', difficulty: 'easy' },
  { declaration: '-1', type: 'number', difficulty: 'easy' },
  { declaration: '100', type: 'number', difficulty: 'easy' },
  { declaration: '9.99', type: 'number', difficulty: 'easy' },
  { declaration: '5000', type: 'number', difficulty: 'easy' },
  { declaration: '0', type: 'number', difficulty: 'easy' },
  { declaration: '7', type: 'number', difficulty: 'easy' },
  { declaration: '255', type: 'number', difficulty: 'easy' },
  { declaration: '-42', type: 'number', difficulty: 'easy' },
  { declaration: '0.01', type: 'number', difficulty: 'easy' },
  { declaration: '99', type: 'number', difficulty: 'easy' },
  { declaration: 'NaN', type: 'number', difficulty: 'medium' },
  { declaration: '1e3', type: 'number', difficulty: 'medium' },
  { declaration: '-0', type: 'number', difficulty: 'medium' },
  { declaration: '0.1 + 0.2', type: 'number', difficulty: 'medium' },
  { declaration: 'Math.PI', type: 'number', difficulty: 'medium' },
  { declaration: '2 ** 10', type: 'number', difficulty: 'medium' },
  { declaration: '0xff', type: 'number', difficulty: 'medium' },
  { declaration: 'Math.floor(3.9)', type: 'number', difficulty: 'medium' },
  { declaration: '"5".length', type: 'number', difficulty: 'medium' },
  { declaration: 'Infinity', type: 'number', difficulty: 'hard' },
  { declaration: '+"42"', type: 'number', difficulty: 'hard' },
  { declaration: 'parseInt("5px")', type: 'number', difficulty: 'hard' },
  { declaration: 'Number(true)', type: 'number', difficulty: 'hard' },
  { declaration: '+false', type: 'number', difficulty: 'hard' },
  { declaration: 'Number("")', type: 'number', difficulty: 'hard' },
  { declaration: 'parseInt("0x1F")', type: 'number', difficulty: 'hard' },
  { declaration: 'Number(false)', type: 'number', difficulty: 'hard' },
  { declaration: '~~3.9', type: 'number', difficulty: 'hard' },
  { declaration: '1 / 0', type: 'number', difficulty: 'hard' },
  { declaration: 'true && 42', type: 'number', difficulty: 'hard' },
  { declaration: '"" || 0', type: 'number', difficulty: 'hard' },
  { declaration: '0 ?? 99', type: 'number', difficulty: 'hard' },
  { declaration: 'true ? 10 : "no"', type: 'number', difficulty: 'hard' },
  { declaration: '1 || "hello"', type: 'number', difficulty: 'hard' },
  // boolean
  { declaration: 'true', type: 'boolean', difficulty: 'easy' },
  { declaration: 'false', type: 'boolean', difficulty: 'easy' },
  { declaration: '10 > 3', type: 'boolean', difficulty: 'easy' },
  { declaration: '1 < 2', type: 'boolean', difficulty: 'easy' },
  { declaration: '0 < 1', type: 'boolean', difficulty: 'easy' },
  { declaration: '"a" === "a"', type: 'boolean', difficulty: 'easy' },
  { declaration: '!true', type: 'boolean', difficulty: 'easy' },
  { declaration: '3 >= 3', type: 'boolean', difficulty: 'easy' },
  { declaration: '5 !== 6', type: 'boolean', difficulty: 'easy' },
  { declaration: '1 === 1', type: 'boolean', difficulty: 'medium' },
  { declaration: '"a" !== "b"', type: 'boolean', difficulty: 'medium' },
  { declaration: '!false', type: 'boolean', difficulty: 'medium' },
  { declaration: '0 === 0', type: 'boolean', difficulty: 'medium' },
  { declaration: '[].length === 0', type: 'boolean', difficulty: 'medium' },
  { declaration: '"hello".includes("ell")', type: 'boolean', difficulty: 'medium' },
  { declaration: '!0', type: 'boolean', difficulty: 'hard' },
  { declaration: '!![]', type: 'boolean', difficulty: 'hard' },
  { declaration: 'Boolean(1)', type: 'boolean', difficulty: 'hard' },
  { declaration: '0 == false', type: 'boolean', difficulty: 'hard' },
  { declaration: '"" == false', type: 'boolean', difficulty: 'hard' },
  { declaration: 'Boolean("a")', type: 'boolean', difficulty: 'hard' },
  { declaration: 'null == undefined', type: 'boolean', difficulty: 'hard' },
  { declaration: '[] == false', type: 'boolean', difficulty: 'hard' },
  { declaration: 'typeof null === "object"', type: 'boolean', difficulty: 'hard' },
  { declaration: 'NaN === NaN', type: 'boolean', difficulty: 'hard' },
  { declaration: '!!"false"', type: 'boolean', difficulty: 'hard' },
  { declaration: 'false && null', type: 'boolean', difficulty: 'hard' },
  { declaration: 'false || false', type: 'boolean', difficulty: 'hard' },
  { declaration: 'false ?? true', type: 'boolean', difficulty: 'hard' },
  { declaration: '0 ? "yes" : true', type: 'boolean', difficulty: 'hard' },
  { declaration: '"" ? 1 : false', type: 'boolean', difficulty: 'hard' },
  // null
  { declaration: 'null', type: 'null', difficulty: 'easy' },
  { declaration: 'null || null', type: 'null', difficulty: 'medium' },
  { declaration: 'JSON.parse("null")', type: 'null', difficulty: 'hard' },
  { declaration: '[1, 2].find(x => x > 9)', type: 'null', difficulty: 'hard' },
  { declaration: '"abc".match(/\\d/)', type: 'null', difficulty: 'hard' },
  { declaration: 'null ?? null', type: 'null', difficulty: 'hard' },
  { declaration: '/\\d+/.exec("abc")', type: 'null', difficulty: 'hard' },
  { declaration: 'null && "hello"', type: 'null', difficulty: 'hard' },
  { declaration: 'false || null', type: 'null', difficulty: 'hard' },
  { declaration: '0 || null', type: 'null', difficulty: 'hard' },
  { declaration: 'undefined || null', type: 'null', difficulty: 'hard' },
  // undefined
  { declaration: 'undefined', type: 'undefined', difficulty: 'easy' },
  { declaration: 'void 0', type: 'undefined', difficulty: 'medium' },
  { declaration: 'void "hello"', type: 'undefined', difficulty: 'medium' },
  { declaration: 'void null', type: 'undefined', difficulty: 'medium' },
  { declaration: '[1, 2][5]', type: 'undefined', difficulty: 'medium' },
  { declaration: '[][0]', type: 'undefined', difficulty: 'hard' },
  { declaration: '({}).missing', type: 'undefined', difficulty: 'hard' },
  { declaration: '[undefined][0]', type: 'undefined', difficulty: 'hard' },
  { declaration: 'undefined ?? undefined', type: 'undefined', difficulty: 'hard' },
  { declaration: 'undefined && "hello"', type: 'undefined', difficulty: 'hard' },
  { declaration: '0 || undefined', type: 'undefined', difficulty: 'hard' },
  { declaration: 'null?.foo', type: 'undefined', difficulty: 'hard' },
  // object
  { declaration: '{ id: 1 }', type: 'object', difficulty: 'easy' },
  { declaration: '{ name: "Alice" }', type: 'object', difficulty: 'easy' },
  { declaration: '{ x: 0, y: 0 }', type: 'object', difficulty: 'easy' },
  { declaration: '{ active: true }', type: 'object', difficulty: 'easy' },
  { declaration: '{ score: 0 }', type: 'object', difficulty: 'easy' },
  { declaration: '{ width: 100, height: 200 }', type: 'object', difficulty: 'easy' },
  { declaration: '{ items: [] }', type: 'object', difficulty: 'easy' },
  { declaration: '{ color: "red" }', type: 'object', difficulty: 'easy' },
  { declaration: '{}', type: 'object', difficulty: 'medium' },
  { declaration: 'new Date()', type: 'object', difficulty: 'medium' },
  { declaration: 'new Map()', type: 'object', difficulty: 'medium' },
  { declaration: '{ 0: "a", 1: "b" }', type: 'object', difficulty: 'medium' },
  { declaration: 'new Error("oops")', type: 'object', difficulty: 'medium' },
  { declaration: 'Object.assign({}, { a: 1 })', type: 'object', difficulty: 'medium' },
  { declaration: '{ ...{ a: 1 } }', type: 'object', difficulty: 'medium' },
  { declaration: 'JSON.parse("{}")', type: 'object', difficulty: 'hard' },
  { declaration: 'Object.create(null)', type: 'object', difficulty: 'hard' },
  { declaration: 'new RegExp("ab")', type: 'object', difficulty: 'hard' },
  { declaration: 'new WeakMap()', type: 'object', difficulty: 'hard' },
  { declaration: 'Object.fromEntries([["a", 1]])', type: 'object', difficulty: 'hard' },
  { declaration: 'new Set([1, 2])', type: 'object', difficulty: 'hard' },
  { declaration: 'null || {}', type: 'object', difficulty: 'hard' },
  // array
  { declaration: '[1, 2, 3]', type: 'array', difficulty: 'easy' },
  { declaration: '["a", "b"]', type: 'array', difficulty: 'easy' },
  { declaration: '[true, false]', type: 'array', difficulty: 'easy' },
  { declaration: '[1, 2]', type: 'array', difficulty: 'easy' },
  { declaration: '[0]', type: 'array', difficulty: 'easy' },
  { declaration: '["hello"]', type: 'array', difficulty: 'easy' },
  { declaration: '[null, null]', type: 'array', difficulty: 'easy' },
  { declaration: '[false, true]', type: 'array', difficulty: 'easy' },
  { declaration: '[]', type: 'array', difficulty: 'medium' },
  { declaration: 'new Array(3)', type: 'array', difficulty: 'medium' },
  { declaration: '[1, [2, 3]]', type: 'array', difficulty: 'medium' },
  { declaration: 'Array(3).fill(0)', type: 'array', difficulty: 'medium' },
  { declaration: 'Object.values({ a: 1 })', type: 'array', difficulty: 'medium' },
  { declaration: '[1, ...[], 2]', type: 'array', difficulty: 'medium' },
  { declaration: '[...[1, 2, 3]]', type: 'array', difficulty: 'medium' },
  { declaration: 'Array.from("abc")', type: 'array', difficulty: 'hard' },
  { declaration: 'Object.keys({ a: 1 })', type: 'array', difficulty: 'hard' },
  { declaration: '"a,b,c".split(",")', type: 'array', difficulty: 'hard' },
  { declaration: '[...new Set([1, 1, 2])]', type: 'array', difficulty: 'hard' },
  { declaration: 'Array.from({ length: 3 })', type: 'array', difficulty: 'hard' },
  { declaration: 'Object.entries({ a: 1 })', type: 'array', difficulty: 'hard' },
  { declaration: '"hello".split("")', type: 'array', difficulty: 'hard' },
  { declaration: 'null || []', type: 'array', difficulty: 'hard' },
  // function
  { declaration: '() => "hi"', type: 'function', difficulty: 'easy' },
  { declaration: '(x) => x * 2', type: 'function', difficulty: 'easy' },
  { declaration: 'function() { return 1 }', type: 'function', difficulty: 'easy' },
  { declaration: '() => {}', type: 'function', difficulty: 'easy' },
  { declaration: '(x, y) => x + y', type: 'function', difficulty: 'easy' },
  { declaration: 'n => n * n', type: 'function', difficulty: 'easy' },
  { declaration: '() => null', type: 'function', difficulty: 'easy' },
  { declaration: 'function add(a, b) {}', type: 'function', difficulty: 'easy' },
  { declaration: 'Math.random', type: 'function', difficulty: 'medium' },
  { declaration: 'parseInt', type: 'function', difficulty: 'medium' },
  { declaration: 'Array.isArray', type: 'function', difficulty: 'medium' },
  { declaration: 'JSON.stringify', type: 'function', difficulty: 'medium' },
  { declaration: 'async () => {}', type: 'function', difficulty: 'medium' },
  { declaration: 'Object.keys', type: 'function', difficulty: 'medium' },
  { declaration: 'class Foo {}', type: 'function', difficulty: 'hard' },
  { declaration: '(function() {})', type: 'function', difficulty: 'hard' },
  { declaration: 'function* gen() {}', type: 'function', difficulty: 'hard' },
  { declaration: 'new Function("return 1")', type: 'function', difficulty: 'hard' },
  { declaration: 'true && Math.random', type: 'function', difficulty: 'hard' },
  // extra tricky
  { declaration: 'typeof NaN', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof typeof 42', type: 'string', difficulty: 'hard' },
  { declaration: '[] + []', type: 'string', difficulty: 'hard' },
  { declaration: 'null + ""', type: 'string', difficulty: 'hard' },
  { declaration: 'String(null)', type: 'string', difficulty: 'hard' },
  { declaration: '+[]', type: 'number', difficulty: 'hard' },
  { declaration: '+null', type: 'number', difficulty: 'hard' },
  { declaration: 'true + true', type: 'number', difficulty: 'hard' },
  { declaration: 'null + 1', type: 'number', difficulty: 'hard' },
  { declaration: '[] - 1', type: 'number', difficulty: 'hard' },
  { declaration: 'Boolean([])', type: 'boolean', difficulty: 'hard' },
  { declaration: 'Boolean({})', type: 'boolean', difficulty: 'hard' },
  { declaration: '!!null', type: 'boolean', difficulty: 'hard' },
  { declaration: '!undefined', type: 'boolean', difficulty: 'hard' },
  { declaration: 'Boolean(null)', type: 'boolean', difficulty: 'hard' },
  { declaration: '(0, null)', type: 'null', difficulty: 'hard' },
  { declaration: '"a".match(/b/)', type: 'null', difficulty: 'hard' },
  { declaration: '[null][0]', type: 'null', difficulty: 'hard' },
  { declaration: 'void false', type: 'undefined', difficulty: 'hard' },
  { declaration: 'void {}', type: 'undefined', difficulty: 'hard' },
  { declaration: '[1, 2].find(() => false)', type: 'undefined', difficulty: 'hard' },
  { declaration: 'new Boolean(false)', type: 'object', difficulty: 'hard' },
  { declaration: 'new Number(42)', type: 'object', difficulty: 'hard' },
  { declaration: '[1, 2, 3].map(x => x * 2)', type: 'array', difficulty: 'hard' },
  { declaration: '"hello".match(/l/g)', type: 'array', difficulty: 'hard' },
  { declaration: 'Boolean', type: 'function', difficulty: 'hard' },
  { declaration: 'Number', type: 'function', difficulty: 'hard' },
];

function getActualType(value) {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  return typeof value;
}

const errors = [];
entries.forEach((entry, index) => {
  try {
    const result = eval(entry.declaration);
    const actualType = getActualType(result);
    if (actualType !== entry.type) {
      errors.push({
        index,
        declaration: entry.declaration,
        expectedType: entry.type,
        actualType,
        value: result,
      });
    }
  } catch (e) {
    errors.push({
      index,
      declaration: entry.declaration,
      expectedType: entry.type,
      error: e.message,
    });
  }
});

if (errors.length === 0) {
  console.log('All entries are correct!');
} else {
  console.log(`Found ${errors.length} errors:\n`);
  errors.forEach(err => {
    if (err.error) {
      console.log(`[${err.index}] ${err.declaration}`);
      console.log(`  Error: ${err.error}\n`);
    } else {
      console.log(`[${err.index}] ${err.declaration}`);
      console.log(`  Expected: ${err.expectedType}, Got: ${err.actualType}`);
      console.log(`  Value: ${JSON.stringify(err.value)}\n`);
    }
  });
}
