import type { Question } from '../types';

const algorithms: Question[] = [
  // --- easy (20) ---
  {
    id: 'algo-linear-search',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of linear search on an unsorted array of n elements?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    answer: 'O(n)',
    explanation: 'Linear search checks each element one by one. In the worst case, the target is at the end or absent, requiring n comparisons.',
  },
  {
    id: 'algo-binary-search-req',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Binary search requires the input array to be:',
    options: ['Unique elements only', 'Sorted', 'Stored as a linked list', 'Of even length'],
    answer: 'Sorted',
    explanation: 'Binary search works by halving the search space based on comparison. This only works correctly if the array is sorted.',
  },
  {
    id: 'algo-bubble-sort',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the worst-case time complexity of bubble sort?',
    options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
    answer: 'O(n^2)',
    explanation: 'Bubble sort compares adjacent pairs and swaps them. In the worst case (reverse sorted), it makes n*(n-1)/2 comparisons, which is O(n^2).',
  },
  {
    id: 'algo-stack-push-pop',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of push and pop operations on a stack?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'],
    answer: 'O(1)',
    explanation: 'Both push (add to top) and pop (remove from top) are O(1) — they operate only at one end of the stack.',
  },
  {
    id: 'algo-queue-enqueue',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of enqueue and dequeue on a queue implemented with a linked list?',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'],
    answer: 'O(1)',
    explanation: 'With a doubly linked list or two-pointer implementation, both enqueue (add to back) and dequeue (remove from front) are O(1).',
  },
  {
    id: 'algo-hashtable-lookup',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the average-case time complexity of lookup in a hash table?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'],
    answer: 'O(1)',
    explanation: 'Hash table lookup is O(1) on average — the hash function maps the key directly to a bucket. Worst case (many collisions) is O(n).',
  },
  {
    id: 'algo-array-access',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of accessing an element by index in an array?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'],
    answer: 'O(1)',
    explanation: 'Arrays store elements in contiguous memory. Index-based access computes a memory address directly (base + index * element_size), taking constant time.',
  },
  {
    id: 'algo-bst-search',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In a balanced BST, search is O(log n). What is search in an unbalanced BST in the worst case?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    answer: 'O(n)',
    explanation: 'A degenerate (skewed) BST becomes a linked list — all nodes on one side. Search requires traversing all n nodes in the worst case.',
  },
  {
    id: 'algo-sorting-stable',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'A sorting algorithm is "stable" if:',
    options: [
      'It always runs in O(n log n)',
      'Equal elements maintain their original relative order',
      'It sorts in place without extra memory',
      'It works on any data type',
    ],
    answer: 'Equal elements maintain their original relative order',
    explanation: 'A stable sort preserves the relative order of equal elements. Merge sort is stable; quicksort is typically not.',
  },
  {
    id: 'algo-big-o-linear',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'An algorithm that iterates through a list once has time complexity:',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    answer: 'O(n)',
    explanation: 'A single pass through n elements takes n steps — linear time O(n).',
  },
  {
    id: 'algo-two-loops',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'A nested loop that iterates n times inside another n-iteration loop has time complexity:',
    options: ['O(n)', 'O(2n)', 'O(n^2)', 'O(n log n)'],
    answer: 'O(n^2)',
    explanation: 'Nested loops where both run n times perform n*n = n^2 operations. Constant factors are dropped in Big O notation.',
  },
  {
    id: 'algo-fibonacci-naive',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'The naive recursive Fibonacci algorithm has which time complexity?',
    options: ['O(n)', 'O(n^2)', 'O(2^n)', 'O(log n)'],
    answer: 'O(2^n)',
    explanation: 'The naive recursive Fibonacci branches into two calls at each step without memoization, resulting in exponential O(2^n) time.',
  },
  {
    id: 'algo-insertion-sort-best',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the best-case time complexity of insertion sort?',
    options: ['O(n^2)', 'O(n log n)', 'O(n)', 'O(1)'],
    answer: 'O(n)',
    explanation: 'Insertion sort is O(n) on an already-sorted input — it makes one pass with no swaps needed. Average and worst case are O(n^2).',
  },
  {
    id: 'algo-graph-directed',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In a directed graph, edges have:',
    options: ['No direction', 'A direction (from one vertex to another)', 'Always equal weights', 'Exactly two endpoints with bidirectional flow'],
    answer: 'A direction (from one vertex to another)',
    explanation: 'Directed graphs (digraphs) have edges with a defined direction. An edge from A to B does not imply an edge from B to A.',
  },
  {
    id: 'algo-space-complexity',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does space complexity measure?',
    options: ['CPU cycles used', 'Number of recursive calls', 'Memory used by an algorithm relative to input size', 'Lines of code'],
    answer: 'Memory used by an algorithm relative to input size',
    explanation: 'Space complexity measures how much extra memory an algorithm uses as input size grows. O(1) space means a fixed amount regardless of input.',
  },
  {
    id: 'algo-linked-list-access',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of accessing the nth element in a singly linked list?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    answer: 'O(n)',
    explanation: 'Unlike arrays, linked lists have no direct index access. To reach the nth element, you must traverse from the head through n nodes.',
  },
  {
    id: 'algo-binary-search-complexity',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of binary search?',
    options: ['O(n)', 'O(n^2)', 'O(log n)', 'O(1)'],
    answer: 'O(log n)',
    explanation: 'Binary search halves the search space at each step. Starting with n elements, it takes at most log2(n) steps to find the target.',
  },
  {
    id: 'algo-merge-sort-complexity',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of merge sort?',
    options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
    answer: 'O(n log n)',
    explanation: 'Merge sort divides the array in half recursively (log n levels) and merges (n work per level), giving O(n log n) in all cases.',
  },
  {
    id: 'algo-dp-definition',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Dynamic programming improves performance by:',
    options: [
      'Parallelizing computation',
      'Storing and reusing results of overlapping subproblems',
      'Using more memory-efficient data structures',
      'Sorting the input first',
    ],
    answer: 'Storing and reusing results of overlapping subproblems',
    explanation: 'Dynamic programming (memoization/tabulation) avoids recomputing subproblems that appear multiple times, reducing exponential time to polynomial in many cases.',
  },
  {
    id: 'algo-heap-property',
    category: 'algorithms',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In a max-heap, the root node always contains:',
    options: ['The minimum value', 'The median value', 'The maximum value', 'The most recently inserted value'],
    answer: 'The maximum value',
    explanation: 'In a max-heap, every parent is greater than or equal to its children. This means the root is always the largest element.',
  },

  // --- medium (20) ---
  {
    id: 'algo-quicksort-pivot',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the worst-case time complexity of quicksort, and when does it occur?',
    options: [
      'O(n log n) always',
      'O(n^2) when the pivot is always the smallest or largest element',
      'O(n) for sorted arrays',
      'O(n^3) in pathological cases',
    ],
    answer: 'O(n^2) when the pivot is always the smallest or largest element',
    explanation: 'If the pivot is always the min or max (e.g., sorted array with first-element pivot), each partition creates one empty side and one of size n-1, degrading to O(n^2).',
  },
  {
    id: 'algo-graph-dijkstra',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Dijkstra\'s algorithm finds the shortest path in a graph with what constraint on edge weights?',
    options: ['All weights must be equal', 'No negative edge weights', 'All weights must be integers', 'No cycles allowed'],
    answer: 'No negative edge weights',
    explanation: 'Dijkstra\'s greedy approach fails with negative weights because a previously "settled" node might be reached via a cheaper negative-weight path. Bellman-Ford handles negatives.',
  },
  {
    id: 'algo-bfs-shortest',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'BFS guarantees the shortest path (by number of edges) in an unweighted graph.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'BFS explores nodes level by level. The first time it reaches a node is via the shortest path (fewest edges). This property does not hold for DFS.',
  },
  {
    id: 'algo-topological-sort',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Topological sort is only possible on which type of graph?',
    options: ['Undirected graphs', 'Directed Acyclic Graphs (DAGs)', 'Weighted graphs', 'Complete graphs'],
    answer: 'Directed Acyclic Graphs (DAGs)',
    explanation: 'Topological sort orders vertices so every edge goes from earlier to later. A cycle makes this impossible, so it requires a DAG.',
  },
  {
    id: 'algo-dp-vs-greedy',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the key difference between dynamic programming and a greedy algorithm?',
    options: [
      'DP uses recursion; greedy uses iteration',
      'DP considers all subproblem results and builds the optimal solution; greedy makes the locally optimal choice at each step',
      'Greedy is always slower than DP',
      'DP requires sorted input; greedy does not',
    ],
    answer: 'DP considers all subproblem results and builds the optimal solution; greedy makes the locally optimal choice at each step',
    explanation: 'Greedy algorithms are faster but may not always give the global optimum. DP guarantees optimality by considering all subproblem combinations but has higher overhead.',
  },
  {
    id: 'algo-avl-tree',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'An AVL tree maintains balance by ensuring:',
    options: [
      'All leaves are at the same level',
      'The height difference between any node\'s left and right subtrees is at most 1',
      'No node has more than 2 children',
      'All operations run in O(1)',
    ],
    answer: 'The height difference between any node\'s left and right subtrees is at most 1',
    explanation: 'AVL trees are self-balancing BSTs. After each insert/delete, they check the balance factor (height difference) and perform rotations to keep it within [-1, 0, 1].',
  },
  {
    id: 'algo-space-in-place',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'An in-place sorting algorithm uses how much extra space?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'],
    answer: 'O(1)',
    explanation: 'In-place algorithms use constant extra space, modifying the input directly. Bubble sort, insertion sort, and quicksort are in-place. Merge sort typically requires O(n) extra space.',
  },
  {
    id: 'algo-hash-chaining',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'In separate chaining for hash collision resolution, each bucket contains:',
    options: ['A sorted array', 'A linked list of all entries with that hash', 'A single entry', 'A secondary hash table'],
    answer: 'A linked list of all entries with that hash',
    explanation: 'Separate chaining stores a linked list (or other structure) at each bucket. Multiple keys hashing to the same bucket are stored in the list.',
  },
  {
    id: 'algo-sliding-window',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'The sliding window technique is typically used to:',
    options: [
      'Sort a subarray in place',
      'Find a subarray or substring satisfying a condition in O(n) instead of O(n^2)',
      'Perform binary search on 2D arrays',
      'Implement recursive tree traversal',
    ],
    answer: 'Find a subarray or substring satisfying a condition in O(n) instead of O(n^2)',
    explanation: 'The sliding window maintains a range with two pointers, expanding or contracting it as needed. Useful for max sum subarray, longest substring without repeats, etc.',
  },
  {
    id: 'algo-two-pointer',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'The two-pointer technique is commonly used to:',
    options: [
      'Traverse a tree',
      'Solve problems on sorted arrays in O(n) by moving two indices inward',
      'Perform in-order DFS',
      'Merge two hash tables',
    ],
    answer: 'Solve problems on sorted arrays in O(n) by moving two indices inward',
    explanation: 'Two pointers (left and right) move toward each other based on conditions. Used for two-sum in sorted arrays, palindrome checks, and removing duplicates.',
  },
  {
    id: 'algo-recursion-stack',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'Deep recursion can cause a stack overflow because each recursive call adds a new frame to the call stack.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Each recursive call uses stack memory. If recursion is too deep (e.g., n=100000 for naive Fibonacci), the call stack overflows, crashing the program.',
  },
  {
    id: 'algo-nlogn-lower-bound',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'It is theoretically impossible to sort a general list of n elements faster than O(n log n) using comparison-based sorting.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'The comparison-based sorting lower bound is O(n log n) — proven via decision tree analysis. Non-comparison sorts (radix, counting) can beat this with assumptions about input.',
  },
  {
    id: 'algo-mst',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A Minimum Spanning Tree (MST) of a graph:',
    options: [
      'Contains the shortest path between all pairs',
      'Connects all vertices with minimum total edge weight and no cycles',
      'Is always unique',
      'Requires the graph to be directed',
    ],
    answer: 'Connects all vertices with minimum total edge weight and no cycles',
    explanation: 'An MST spans all vertices with the minimum total weight, forming a tree (connected, acyclic). Kruskal\'s and Prim\'s algorithms find MSTs.',
  },
  {
    id: 'algo-backtracking',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Backtracking differs from brute force by:',
    options: [
      'Using dynamic programming to cache results',
      'Abandoning partial solutions that cannot lead to a valid answer (pruning)',
      'Always finding the optimal solution in O(n) time',
      'Using two stacks instead of one',
    ],
    answer: 'Abandoning partial solutions that cannot lead to a valid answer (pruning)',
    explanation: 'Backtracking is a depth-first search that abandons ("backtracks" from) branches as soon as a constraint is violated, reducing the search space.',
  },
  {
    id: 'algo-linked-list-insert',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of inserting at the beginning of a singly linked list?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'],
    answer: 'O(1)',
    explanation: 'Inserting at the head of a linked list only requires updating the new node\'s next pointer and the head reference — constant time.',
  },
  {
    id: 'algo-cycle-detection',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Floyd\'s cycle detection algorithm uses how many pointers?',
    options: ['1', '2', '3', 'n'],
    answer: '2',
    explanation: 'Floyd\'s "tortoise and hare" algorithm uses two pointers moving at different speeds (1 and 2 steps). If a cycle exists, they will eventually meet.',
  },
  {
    id: 'algo-heap-extract',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of extracting the maximum from a max-heap?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 'O(log n)',
    explanation: 'Extraction removes the root (O(1)), places the last element at the root, then sifts it down to restore the heap property — O(log n) comparisons.',
  },
  {
    id: 'algo-prefix-sum',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A prefix sum array allows range sum queries in:',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'],
    answer: 'O(1)',
    explanation: 'After O(n) preprocessing to build the prefix array, any subarray sum from index i to j is prefix[j+1] - prefix[i], computed in O(1).',
  },
  {
    id: 'algo-trie',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A trie (prefix tree) is optimized for:',
    options: ['Range queries', 'String prefix matching and autocomplete', 'Shortest path problems', 'Balanced insertion'],
    answer: 'String prefix matching and autocomplete',
    explanation: 'A trie stores strings character by character in a tree. Prefix lookups are O(k) where k is the prefix length, independent of how many strings are stored.',
  },
  {
    id: 'algo-amortized-array',
    category: 'algorithms',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Appending to a dynamic array (ArrayList) is amortized O(1). What causes the occasional O(n) cost?',
    options: ['Hash computation', 'Sorting the array after insert', 'Copying the array to a new larger allocation when full', 'Garbage collection'],
    answer: 'Copying the array to a new larger allocation when full',
    explanation: 'When the array is full, it doubles its capacity and copies all n elements — O(n). But this happens rarely enough that the average per-insert cost is O(1) amortized.',
  },

  // --- hard (15) ---
  {
    id: 'algo-np-hard',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'The traveling salesman problem (TSP) is NP-hard. This means:',
    options: [
      'It has no known efficient exact algorithm, but solutions can be verified in polynomial time',
      'It cannot be approximated',
      'It is unsolvable',
      'It runs in O(n!) exactly',
    ],
    answer: 'It has no known efficient exact algorithm, but solutions can be verified in polynomial time',
    explanation: 'NP-hard means no polynomial-time algorithm is known. TSP can be verified in polynomial time (check a given tour\'s cost), but finding the optimal tour is exponential in the worst case.',
  },
  {
    id: 'algo-red-black-tree',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Red-black trees guarantee O(log n) operations by enforcing:',
    options: [
      'Height difference of at most 1 between left and right subtrees',
      'Invariants about node coloring that bound the height to at most 2*log n',
      'All leaves being at the same depth',
      'The root always being red',
    ],
    answer: 'Invariants about node coloring that bound the height to at most 2*log n',
    explanation: 'Red-black trees use color properties to ensure the longest path is at most twice the shortest. This keeps height O(log n) with fewer rotations than AVL trees.',
  },
  {
    id: 'algo-kmp',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'The KMP (Knuth-Morris-Pratt) algorithm achieves O(n+m) string search by:',
    options: [
      'Sorting the pattern before searching',
      'Using a failure function to skip characters without re-examination',
      'Hashing each substring',
      'Using a trie of all patterns',
    ],
    answer: 'Using a failure function to skip characters without re-examination',
    explanation: 'KMP precomputes a "failure function" (partial match table) for the pattern, allowing the search to skip over already-matched characters when a mismatch occurs.',
  },
  {
    id: 'algo-segment-tree',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'A segment tree supports range queries and point updates in:',
    options: ['O(1) both', 'O(log n) both', 'O(n) both', 'O(n) queries, O(1) updates'],
    answer: 'O(log n) both',
    explanation: 'Segment trees store aggregate values (sum, min, max) for ranges. Both queries and updates traverse the tree height, O(log n). Build time is O(n).',
  },
  {
    id: 'algo-ford-fulkerson',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'The Ford-Fulkerson algorithm solves which problem?',
    options: [
      'Minimum spanning tree',
      'Maximum flow in a flow network',
      'Shortest path with negative edges',
      'Topological sort',
    ],
    answer: 'Maximum flow in a flow network',
    explanation: 'Ford-Fulkerson finds the maximum flow from source to sink in a flow network by repeatedly finding augmenting paths and updating residual capacities.',
  },
  {
    id: 'algo-union-find',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Union-Find (Disjoint Set Union) with path compression and union by rank achieves what amortized time per operation?',
    options: ['O(log n)', 'O(alpha(n)) — effectively constant', 'O(n)', 'O(1) exactly'],
    answer: 'O(alpha(n)) — effectively constant',
    explanation: 'With path compression and union by rank, each operation is nearly O(1) — specifically O(α(n)) where α is the inverse Ackermann function, which is at most 4 for any practical n.',
  },
  {
    id: 'algo-bellman-ford',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Bellman-Ford can detect negative cycles. How does it do this?',
    options: [
      'By checking if any edge is negative',
      'By running an extra (V-th) iteration and checking if any distance still decreases',
      'By sorting edges before running',
      'By running BFS after finding shortest paths',
    ],
    answer: 'By running an extra (V-th) iteration and checking if any distance still decreases',
    explanation: 'Bellman-Ford runs V-1 relaxations. If a V-th relaxation still updates any distance, there is a negative-weight cycle reachable from the source.',
  },
  {
    id: 'algo-fenwick-tree',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'A Fenwick tree (Binary Indexed Tree) is used for:',
    options: [
      'Graph traversal',
      'Efficient prefix sum queries and point updates in O(log n)',
      'Balanced BST operations',
      'String matching',
    ],
    answer: 'Efficient prefix sum queries and point updates in O(log n)',
    explanation: 'Fenwick trees compute prefix sums and support point updates in O(log n) time with O(n) space, simpler to implement than segment trees for cumulative sum problems.',
  },
  {
    id: 'algo-lcs',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'The dynamic programming solution to Longest Common Subsequence (LCS) has what time and space complexity?',
    options: ['O(n + m) time, O(1) space', 'O(n*m) time, O(n*m) space', 'O(n log n) time, O(n) space', 'O(2^n) time, O(n) space'],
    answer: 'O(n*m) time, O(n*m) space',
    explanation: 'LCS fills an n×m DP table where n and m are the string lengths. Both time and space are O(n*m). Space can be reduced to O(min(n,m)) with only two rows.',
  },
  {
    id: 'algo-aho-corasick',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'The Aho-Corasick algorithm is used for:',
    options: [
      'Single pattern string search',
      'Multi-pattern string search in O(n + total_pattern_length + number_of_matches)',
      'Approximate string matching',
      'Compressing strings',
    ],
    answer: 'Multi-pattern string search in O(n + total_pattern_length + number_of_matches)',
    explanation: 'Aho-Corasick builds a trie of all patterns with failure links. It searches a text for all patterns simultaneously in linear time — used in firewalls, virus scanners, etc.',
  },
  {
    id: 'algo-convex-hull',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the convex hull of a set of 2D points represent?',
    options: [
      'The minimum bounding rectangle',
      'The smallest convex polygon enclosing all the points',
      'The centroid of all points',
      'The Voronoi diagram of the points',
    ],
    answer: 'The smallest convex polygon enclosing all the points',
    explanation: 'The convex hull is the smallest convex polygon containing all given points — like stretching a rubber band around nails. Algorithms like Graham scan run in O(n log n).',
  },
  {
    id: 'algo-stable-sort-radix',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Radix sort can achieve O(nk) time where k is the number of digits. When is this better than O(n log n)?',
    options: [
      'Always',
      'When k < log n, i.e., the key length is small compared to log n',
      'Only for floating point numbers',
      'When n is very small',
    ],
    answer: 'When k < log n, i.e., the key length is small compared to log n',
    explanation: 'Radix sort is linear in n for fixed-width keys. If the key length k is small (e.g., 32-bit integers have k=32 bits), it beats O(n log n) for large n.',
  },
  {
    id: 'algo-randomized-quicksort',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Randomized quicksort chooses a random pivot. What is its expected time complexity?',
    options: ['O(n^2)', 'O(n log n)', 'O(n)', 'O(n^1.5)'],
    answer: 'O(n log n)',
    explanation: 'Randomization breaks worst-case input patterns. The expected time is O(n log n) across all inputs since a bad pivot is unlikely on average.',
  },
  {
    id: 'algo-cache-oblivious',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'A cache-oblivious algorithm:',
    options: [
      'Avoids using the CPU cache',
      'Is optimal for any cache size without knowing the cache size at design time',
      'Only works on machines with no cache',
      'Uses explicit prefetch instructions',
    ],
    answer: 'Is optimal for any cache size without knowing the cache size at design time',
    explanation: 'Cache-oblivious algorithms achieve optimal cache performance for any memory hierarchy without being tuned to a specific cache size — e.g., cache-oblivious merge sort.',
  },
  {
    id: 'algo-splay-tree',
    category: 'algorithms',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'A splay tree achieves O(log n) amortized time by:',
    options: [
      'Rebalancing after every operation like AVL',
      'Moving recently accessed nodes to the root via rotations',
      'Using a fixed height of 2*log n',
      'Maintaining red-black invariants',
    ],
    answer: 'Moving recently accessed nodes to the root via rotations',
    explanation: 'Splay trees move every accessed node to the root through a series of rotations ("splaying"). This provides good locality for frequently accessed elements and O(log n) amortized cost.',
  },
];

export default algorithms;
