import type { Question } from '../types';

const bash: Question[] = [
  // --- easy (20) ---
  {
    id: 'bash-echo',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command prints text to the terminal in bash?',
    options: ['print', 'say', 'echo', 'write'],
    answer: 'echo',
    explanation: 'echo prints its arguments to stdout. echo "hello world" prints: hello world',
  },
  {
    id: 'bash-pwd',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command prints the current working directory?',
    options: ['cwd', 'dir', 'pwd', 'where'],
    answer: 'pwd',
    explanation: 'pwd (print working directory) outputs the absolute path of the current directory.',
  },
  {
    id: 'bash-mkdir',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command creates a new directory called "mydir"?',
    options: ['create mydir', 'touch mydir', 'mkdir mydir', 'newdir mydir'],
    answer: 'mkdir mydir',
    explanation: 'mkdir (make directory) creates a new directory. mkdir -p creates nested directories and does not fail if they already exist.',
  },
  {
    id: 'bash-touch',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>touch file.txt</code> do if file.txt does not exist?',
    options: ['Throws an error', 'Creates an empty file', 'Opens the file for editing', 'Compresses the file'],
    answer: 'Creates an empty file',
    explanation: 'touch creates an empty file if it does not exist. If it does exist, touch updates its last-modified timestamp.',
  },
  {
    id: 'bash-cat',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>cat file.txt</code> do?',
    options: ['Copies the file', 'Edits the file', 'Prints the file contents to stdout', 'Deletes the file'],
    answer: 'Prints the file contents to stdout',
    explanation: 'cat (concatenate) prints file contents to stdout. It can also concatenate multiple files: cat a.txt b.txt',
  },
  {
    id: 'bash-cp',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command copies a file?',
    options: ['mv', 'cp', 'copy', 'clone'],
    answer: 'cp',
    explanation: 'cp source dest copies a file. cp -r copies directories recursively.',
  },
  {
    id: 'bash-mv',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>mv old.txt new.txt</code> do?',
    options: ['Copies the file', 'Renames or moves the file', 'Merges two files', 'Creates a link'],
    answer: 'Renames or moves the file',
    explanation: 'mv moves or renames files/directories. mv old.txt new.txt renames the file. mv file.txt /tmp/ moves it to /tmp/.',
  },
  {
    id: 'bash-shebang',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does the shebang line <code>#!/bin/bash</code> at the top of a script do?',
    options: [
      'Comments out the first line',
      'Specifies the interpreter to use for the script',
      'Sets the script permission',
      'Defines the script version',
    ],
    answer: 'Specifies the interpreter to use for the script',
    explanation: 'The shebang (#!) tells the OS which interpreter to run the script with. #!/bin/bash means: run this script with bash.',
  },
  {
    id: 'bash-exit-code',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What exit code indicates success in a bash script?',
    options: ['1', '-1', '0', '255'],
    answer: '0',
    explanation: 'Exit code 0 means success. Non-zero exit codes indicate errors. $? holds the exit code of the last command.',
  },
  {
    id: 'bash-if-syntax',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the correct syntax for an if statement in bash?',
    options: [
      'if (condition) { ... }',
      'if [condition]: ... fi',
      'if [ condition ]; then ... fi',
      'if condition then ... end',
    ],
    answer: 'if [ condition ]; then ... fi',
    explanation: 'Bash if syntax: if [ condition ]; then commands; fi. Note the spaces inside brackets — they are required.',
  },
  {
    id: 'bash-dollar-zero',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In a bash script, what does <code>$0</code> represent?',
    options: ['The first argument', 'The script name', 'The process ID', 'The exit code'],
    answer: 'The script name',
    explanation: '$0 is the name of the script being run. $1, $2, etc. are positional arguments. $# is the argument count. $@ is all arguments.',
  },
  {
    id: 'bash-semicolon',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In bash, what does separating two commands with <code>;</code> do?',
    options: [
      'Runs the second only if the first succeeds',
      'Runs both commands in parallel',
      'Runs them sequentially, regardless of exit codes',
      'Pipes output from one to the other',
    ],
    answer: 'Runs them sequentially, regardless of exit codes',
    explanation: 'Semicolons separate commands and run them sequentially no matter what. Use && to run only on success, || to run only on failure.',
  },
  {
    id: 'bash-double-ampersand',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In bash, <code>cmd1 && cmd2</code> means:',
    options: [
      'Run both in parallel',
      'Run cmd2 only if cmd1 succeeds (exit code 0)',
      'Run cmd2 only if cmd1 fails',
      'Merge the output of both',
    ],
    answer: 'Run cmd2 only if cmd1 succeeds (exit code 0)',
    explanation: '&& is the AND operator. cmd2 runs only if cmd1 exits with 0. Useful for chaining: mkdir dir && cd dir',
  },
  {
    id: 'bash-double-pipe',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In bash, <code>cmd1 || cmd2</code> means:',
    options: [
      'Run both in parallel',
      'Pipe cmd1 output to cmd2',
      'Run cmd2 only if cmd1 fails',
      'Run cmd2 only if cmd1 succeeds',
    ],
    answer: 'Run cmd2 only if cmd1 fails',
    explanation: '|| is the OR operator. cmd2 runs only if cmd1 exits with a non-zero code. Useful for fallbacks.',
  },
  {
    id: 'bash-for-loop',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which bash snippet loops over items in a list?',
    options: [
      'for i in 1 2 3; do echo $i; done',
      'loop [1 2 3] { echo $i }',
      'foreach i (1 2 3) echo $i',
      'repeat 3 echo',
    ],
    answer: 'for i in 1 2 3; do echo $i; done',
    explanation: 'The bash for loop syntax: for variable in list; do commands; done. $i holds the current item.',
  },
  {
    id: 'bash-read',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>read name</code> do in bash?',
    options: [
      'Reads a file named "name"',
      'Reads a line from stdin into the variable "name"',
      'Prints the variable "name"',
      'Sets name to an empty string',
    ],
    answer: 'Reads a line from stdin into the variable "name"',
    explanation: 'read reads one line from stdin and assigns it to the given variable. Used for user input in scripts.',
  },
  {
    id: 'bash-hash-comment',
    category: 'bash',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'In bash, lines starting with <code>#</code> are treated as comments.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: '# starts a comment in bash. Everything after # on that line is ignored (except the shebang #! on line 1 which is special).',
  },
  {
    id: 'bash-which',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command shows the full path of an executable?',
    options: ['locate', 'whereis', 'which', 'path'],
    answer: 'which',
    explanation: 'which searches PATH and returns the full path of the named executable. which python3 might return /usr/bin/python3.',
  },
  {
    id: 'bash-man',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command displays the manual page for a command?',
    options: ['help', 'info', 'man', 'docs'],
    answer: 'man',
    explanation: 'man (manual) displays the manual page for a command. man ls, man grep, etc. Press q to quit.',
  },
  {
    id: 'bash-history',
    category: 'bash',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In bash, what does pressing <code>Ctrl+R</code> do?',
    options: ['Refreshes the terminal', 'Runs the last command', 'Starts reverse-search of command history', 'Clears the screen'],
    answer: 'Starts reverse-search of command history',
    explanation: 'Ctrl+R activates reverse incremental search through command history. Type characters to find matching past commands.',
  },

  // --- medium (20) ---
  {
    id: 'bash-arrays',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'How do you access the third element (index 2) of a bash array <code>arr</code>?',
    options: ['$arr[2]', '${arr[2]}', 'arr[2]', '$(arr 2)'],
    answer: '${arr[2]}',
    explanation: 'Bash array elements are accessed with ${arr[index]}. $arr alone only gives the first element.',
  },
  {
    id: 'bash-set-e',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>set -e</code> do in a bash script?',
    options: [
      'Enables debug mode (print each command)',
      'Exits the script immediately if any command returns a non-zero exit code',
      'Disables globbing',
      'Enables extended glob patterns',
    ],
    answer: 'Exits the script immediately if any command returns a non-zero exit code',
    explanation: 'set -e (errexit) makes the script exit immediately on any error. Commonly paired with set -u (unset variables are errors) and set -o pipefail.',
  },
  {
    id: 'bash-subshell',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does wrapping commands in <code>( )</code> do in bash?',
    options: [
      'Groups them for conditional logic',
      'Runs them in a subshell, so variable changes do not affect the parent shell',
      'Makes them run in parallel',
      'Treats them as a function',
    ],
    answer: 'Runs them in a subshell, so variable changes do not affect the parent shell',
    explanation: '( commands ) creates a subshell. Changes to variables or the current directory inside do not persist after the subshell exits.',
  },
  {
    id: 'bash-trap',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>trap "cleanup" EXIT</code> do?',
    options: [
      'Runs "cleanup" on error only',
      'Runs the "cleanup" command whenever the script exits (normally or on error)',
      'Catches keyboard interrupts',
      'Defines a function called EXIT',
    ],
    answer: 'Runs the "cleanup" command whenever the script exits (normally or on error)',
    explanation: 'trap registers a command to run when a signal is received. EXIT fires on any exit — normal, error, or signal — making it ideal for cleanup.',
  },
  {
    id: 'bash-brace-expansion',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>echo {a,b,c}.txt</code> output?',
    options: ['{a,b,c}.txt', 'a.txt b.txt c.txt', 'a,b,c.txt', 'Error'],
    answer: 'a.txt b.txt c.txt',
    explanation: 'Brace expansion generates multiple strings. {a,b,c}.txt expands to a.txt b.txt c.txt. Useful for creating multiple files or paths at once.',
  },
  {
    id: 'bash-parameter-expansion',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>${var:-default}</code> do?',
    options: [
      'Sets var to "default"',
      'Returns "default" if var is unset or empty, without changing var',
      'Removes "default" from var',
      'Appends "default" to var',
    ],
    answer: 'Returns "default" if var is unset or empty, without changing var',
    explanation: '${var:-default} is a parameter expansion default: if var is unset or empty, substitute "default". var is not changed. ${var:=default} would also assign it.',
  },
  {
    id: 'bash-command-substitution',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>files=$(ls)</code> do?',
    options: [
      'Assigns the string "ls" to files',
      'Runs ls and assigns its output to the variable files',
      'Pipes ls into files',
      'Creates an alias',
    ],
    answer: 'Runs ls and assigns its output to the variable files',
    explanation: '$( ) is command substitution. The command runs and its stdout becomes the value. The older backtick syntax (`ls`) does the same thing.',
  },
  {
    id: 'bash-arithmetic',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'How do you perform integer arithmetic in bash?',
    options: ['$[2 + 2]', '$(( 2 + 2 ))', 'calc 2 + 2', '${2 + 2}'],
    answer: '$(( 2 + 2 ))',
    explanation: '$(( )) is the arithmetic expansion syntax in bash. It evaluates integer expressions. The result of $(( 2 + 2 )) is 4.',
  },
  {
    id: 'bash-here-doc',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the syntax for a heredoc in bash?',
    options: [
      'cat | "text"',
      'cat <<EOF\ntext\nEOF',
      'echo <(text)',
      '<<TEXT ... TEXT',
    ],
    answer: 'cat <<EOF\ntext\nEOF',
    explanation: 'A heredoc redirects a multi-line block as stdin: command <<DELIMITER ... DELIMITER. The delimiter (EOF, END, etc.) must match exactly on its own line.',
  },
  {
    id: 'bash-glob',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>ls *.txt</code> match?',
    options: ['Only a file named exactly "*.txt"', 'All files ending in .txt', 'All files containing "txt"', 'All text files'],
    answer: 'All files ending in .txt',
    explanation: '* is a glob wildcard matching any string. *.txt matches all filenames ending in .txt in the current directory.',
  },
  {
    id: 'bash-pipefail',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>set -o pipefail</code> do?',
    options: [
      'Makes pipes bidirectional',
      'Causes a pipeline to return the exit code of the first failed command',
      'Prevents stdout/stderr mixing in pipes',
      'Disables globbing in pipes',
    ],
    answer: 'Causes a pipeline to return the exit code of the first failed command',
    explanation: 'By default, a pipe\'s exit code is the last command\'s. pipefail makes it the exit code of the first failed command. Combines with set -e to catch pipe failures.',
  },
  {
    id: 'bash-test-brackets',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the difference between <code>[ ]</code> and <code>[[ ]]</code> in bash conditionals?',
    options: [
      'They are identical',
      '[[ ]] is a bash keyword with more features (regex, &&, || inside); [ ] is POSIX',
      '[ ] is only for numbers, [[ ]] for strings',
      '[[ ]] requires quotes around all variables',
    ],
    answer: '[[ ]] is a bash keyword with more features (regex, &&, || inside); [ ] is POSIX',
    explanation: '[[ ]] is a bash built-in that supports =~, && and || inside, and does not require quoting variables. [ ] is POSIX sh compatible but more fragile with unquoted variables.',
  },
  {
    id: 'bash-while-loop',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which reads a file line by line in bash?',
    options: [
      'foreach line in file.txt; do echo $line; done',
      'while IFS= read -r line; do echo "$line"; done < file.txt',
      'for line in $(cat file.txt); do echo $line; done',
      'read --all file.txt | while echo $line',
    ],
    answer: 'while IFS= read -r line; do echo "$line"; done < file.txt',
    explanation: 'This is the correct idiom: IFS= prevents stripping leading/trailing whitespace, -r prevents backslash interpretation, and < file.txt redirects the file to the while loop.',
  },
  {
    id: 'bash-function',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'How do you define a function named "greet" in bash?',
    options: [
      'function greet() { echo "hi"; }',
      'def greet: echo "hi"',
      'greet() => echo "hi"',
      'fn greet { echo "hi" }',
    ],
    answer: 'function greet() { echo "hi"; }',
    explanation: 'Bash functions use: function name() { commands; } or name() { commands; }. The function keyword is optional.',
  },
  {
    id: 'bash-stderr-redirect',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>command 2>&1</code> do?',
    options: [
      'Redirects stdout to stderr',
      'Redirects stderr (fd 2) to wherever stdout (fd 1) currently points',
      'Duplicates the command output',
      'Sends stderr to /dev/null',
    ],
    answer: 'Redirects stderr (fd 2) to wherever stdout (fd 1) currently points',
    explanation: '2>&1 redirects file descriptor 2 (stderr) to file descriptor 1 (stdout). Combined with > file.txt it captures both streams: command > file.txt 2>&1',
  },
  {
    id: 'bash-null-redirect',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>command > /dev/null 2>&1</code> do?',
    options: [
      'Saves output to a file',
      'Suppresses all output (both stdout and stderr)',
      'Redirects to the terminal',
      'Logs to syslog',
    ],
    answer: 'Suppresses all output (both stdout and stderr)',
    explanation: '/dev/null is a discard device. Redirecting stdout and stderr there silences the command completely — useful for cron jobs or quiet commands.',
  },
  {
    id: 'bash-source',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the difference between running <code>./script.sh</code> and <code>source script.sh</code>?',
    options: [
      'source runs faster',
      './script.sh runs in a subshell; source runs in the current shell, so variable changes persist',
      'They are identical',
      'source requires no execute permission',
    ],
    answer: './script.sh runs in a subshell; source runs in the current shell, so variable changes persist',
    explanation: 'source (or .) runs the script in the current shell process. Variable and directory changes persist. ./script.sh forks a subshell; its changes vanish after it exits.',
  },
  {
    id: 'bash-sort-uniq',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>sort file.txt | uniq -c</code> do?',
    options: [
      'Sorts and removes all duplicates',
      'Sorts lines and counts consecutive duplicate occurrences',
      'Counts total lines in the file',
      'Sorts by frequency',
    ],
    answer: 'Sorts lines and counts consecutive duplicate occurrences',
    explanation: 'sort sorts lines; uniq -c counts consecutive duplicates. Together they count how many times each unique line appears, useful for frequency analysis.',
  },
  {
    id: 'bash-curl',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>curl -o output.html https://example.com</code> do?',
    options: [
      'Opens the URL in a browser',
      'Downloads the URL and saves it to output.html',
      'Sends a POST request',
      'Opens a WebSocket connection',
    ],
    answer: 'Downloads the URL and saves it to output.html',
    explanation: 'curl transfers data from URLs. -o saves the response to a file. -O (uppercase) saves with the remote filename. -s silences progress output.',
  },
  {
    id: 'bash-ps',
    category: 'bash',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>ps aux</code> show?',
    options: [
      'Disk usage',
      'All running processes with their user, PID, CPU/memory usage',
      'Open network connections',
      'Logged-in users',
    ],
    answer: 'All running processes with their user, PID, CPU/memory usage',
    explanation: 'ps aux shows all processes on the system: a (all users), u (user format), x (include processes without a tty). Combined with grep to find specific processes.',
  },

  // --- hard (15) ---
  {
    id: 'bash-getopts',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is <code>getopts</code> used for in bash?',
    options: [
      'Parsing long options like --verbose',
      'Parsing short options (like -v -f) from script arguments',
      'Getting environment variables',
      'Fetching remote configuration',
    ],
    answer: 'Parsing short options (like -v -f) from script arguments',
    explanation: 'getopts is the POSIX-standard bash built-in for parsing short options. It handles -v, -f file, etc. For long options, external tools like getopt (without s) are needed.',
  },
  {
    id: 'bash-associative-array',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'How do you declare an associative array (hash map) in bash?',
    options: [
      'declare -a mymap',
      'declare -A mymap',
      'typeset -h mymap',
      'mymap={}',
    ],
    answer: 'declare -A mymap',
    explanation: 'declare -A declares an associative array (key-value). Access: mymap["key"]="value" and ${mymap["key"]}. declare -a is for regular indexed arrays.',
  },
  {
    id: 'bash-nameref',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>declare -n ref=other_var</code> do in bash?',
    options: [
      'Creates a numeric alias',
      'Creates a name reference (reference to another variable)',
      'Declares ref as a null variable',
      'Makes ref read-only',
    ],
    answer: 'Creates a name reference (reference to another variable)',
    explanation: 'declare -n creates a nameref — a variable that is an alias for another. Assigning to ref changes other_var. Available in bash 4.3+.',
  },
  {
    id: 'bash-extglob',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>shopt -s extglob</code> enable?',
    options: [
      'Extended history',
      'Extended glob patterns like !(pattern) and +(pattern)',
      'Case-insensitive globbing',
      'Recursive ** glob',
    ],
    answer: 'Extended glob patterns like !(pattern) and +(pattern)',
    explanation: 'extglob enables patterns like !(*.txt) (anything except .txt), +(a|b) (one or more of a or b), ?(x) (zero or one x), *(x) (zero or more x), @(x) (exactly one x).',
  },
  {
    id: 'bash-printf',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Why might you prefer <code>printf</code> over <code>echo</code> for output in scripts?',
    options: [
      'printf is faster',
      'printf supports format strings and is more portable across shells',
      'echo cannot handle variables',
      'printf can write to files directly',
    ],
    answer: 'printf supports format strings and is more portable across shells',
    explanation: 'echo behavior varies across systems (some interpret -n and \\n, others do not). printf is consistent and supports format strings like C\'s printf — better for portable scripts.',
  },
  {
    id: 'bash-regex-match',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'How do you test if a variable matches a regex in bash?',
    options: [
      '[[ $var =~ regex ]]',
      '[ $var ~ regex ]',
      'grep "regex" <<< "$var"',
      '$var matches "regex"',
    ],
    answer: '[[ $var =~ regex ]]',
    explanation: 'The =~ operator inside [[ ]] tests a string against an ERE (extended regular expression). The match is accessible via BASH_REMATCH.',
  },
  {
    id: 'bash-coproc',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the <code>coproc</code> keyword do in bash?',
    options: [
      'Runs a command and waits for it',
      'Starts a coprocess — a background process with bidirectional pipes connected to the shell',
      'Copies a process\'s environment',
      'Creates a coroutine',
    ],
    answer: 'Starts a coprocess — a background process with bidirectional pipes connected to the shell',
    explanation: 'coproc starts a command as a coprocess. The shell can write to its stdin and read from its stdout via special file descriptors, enabling two-way communication.',
  },
  {
    id: 'bash-fd-redirect',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>exec 3>file.txt</code> do in bash?',
    options: [
      'Replaces the shell process with a redirect',
      'Opens file.txt for writing on file descriptor 3',
      'Forks a new shell with file.txt',
      'Closes file descriptor 3',
    ],
    answer: 'Opens file.txt for writing on file descriptor 3',
    explanation: 'exec N>file opens a custom file descriptor. Later, echo "text" >&3 writes to it. exec 3>&- closes it. Useful for managing multiple output streams.',
  },
  {
    id: 'bash-mapfile',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>mapfile -t arr < file.txt</code> do?',
    options: [
      'Maps a file to an associative array by line numbers',
      'Reads lines from file.txt into indexed array arr, stripping trailing newlines',
      'Creates a memory-mapped file',
      'Reads key=value pairs into a hash',
    ],
    answer: 'Reads lines from file.txt into indexed array arr, stripping trailing newlines',
    explanation: 'mapfile (alias readarray) reads lines from a file or stdin into an array. -t strips trailing newlines from each element.',
  },
  {
    id: 'bash-signal-handling',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In bash, what does <code>trap "echo INT" INT</code> do?',
    options: [
      'Disables Ctrl+C',
      'Echoes "INT" when the script receives the SIGINT signal (Ctrl+C)',
      'Sets the interrupt handler for the terminal',
      'Traps all signals',
    ],
    answer: 'Echoes "INT" when the script receives the SIGINT signal (Ctrl+C)',
    explanation: 'trap command SIGNAL registers a handler for a signal. When SIGINT is received (Ctrl+C), the shell runs the trap command instead of exiting immediately.',
  },
  {
    id: 'bash-process-group',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>kill -- -$$</code> do in bash?',
    options: [
      'Kills the current shell',
      'Kills the current script and all its child processes by sending SIGTERM to the process group',
      'Kills the last background job',
      'Sends a null signal to the current process',
    ],
    answer: 'Kills the current script and all its child processes by sending SIGTERM to the process group',
    explanation: 'Negating a PID (- prefix) sends the signal to the entire process group. $$ is the current shell PID. kill -- -$$ kills all processes in the script\'s group.',
  },
  {
    id: 'bash-inode',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is an inode in a Unix filesystem?',
    options: [
      'A directory entry',
      'A data structure storing file metadata (permissions, size, timestamps, block pointers) but not the filename',
      'The first 128 bytes of a file',
      'A type of hard link',
    ],
    answer: 'A data structure storing file metadata (permissions, size, timestamps, block pointers) but not the filename',
    explanation: 'An inode stores everything about a file except its name. The directory maps filenames to inode numbers. Hard links are multiple directory entries pointing to the same inode.',
  },
  {
    id: 'bash-strace',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>strace -p <pid></code> do?',
    options: [
      'Stops the process',
      'Attaches to the process and traces all system calls it makes',
      'Shows the stack trace of the process',
      'Profiles CPU usage',
    ],
    answer: 'Attaches to the process and traces all system calls it makes',
    explanation: 'strace traces system calls and signals. -p attaches to a running process. Used for debugging hangs, unexpected file accesses, or network issues.',
  },
  {
    id: 'bash-tmpfile',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Why is <code>mktemp</code> preferred over manually creating temp files like <code>/tmp/myfile.txt</code>?',
    options: [
      'mktemp is faster',
      'mktemp creates a uniquely named file atomically, preventing race conditions and symlink attacks',
      'mktemp creates files in /dev/shm for better performance',
      'Manually created files are not deleted automatically',
    ],
    answer: 'mktemp creates a uniquely named file atomically, preventing race conditions and symlink attacks',
    explanation: 'A predictable temp filename is a security risk — an attacker can create a symlink to a sensitive file. mktemp creates a random, unique filename atomically and safely.',
  },
  {
    id: 'bash-strict-mode',
    category: 'bash',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>set -euo pipefail</code> do at the top of a bash script?',
    options: [
      'Enables verbose output mode',
      'Sets strict mode: exit on error, treat unset variables as errors, and fail on pipe errors',
      'Prevents globbing and expansion',
      'Enables POSIX compatibility mode',
    ],
    answer: 'Sets strict mode: exit on error, treat unset variables as errors, and fail on pipe errors',
    explanation: 'set -e: exit on error. set -u: unset variables are errors. set -o pipefail: pipe fails if any command fails. Together they make scripts more robust and catch common bugs.',
  },
];

export default bash;
