import type { Question } from '../types';

const databases: Question[] = [
  // --- easy (20) ---
  {
    id: 'db-select',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which SQL clause retrieves all rows from a table named "users"?',
    options: ['GET * FROM users', 'SELECT * FROM users', 'FETCH ALL users', 'READ users'],
    answer: 'SELECT * FROM users',
    explanation: 'SELECT is the SQL statement for querying data. * means all columns. FROM specifies the table.',
  },
  {
    id: 'db-where',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which SQL clause filters rows based on a condition?',
    options: ['FILTER', 'HAVING', 'WHERE', 'LIMIT'],
    answer: 'WHERE',
    explanation: 'WHERE filters rows before grouping. HAVING filters after GROUP BY. Example: SELECT * FROM users WHERE age > 18.',
  },
  {
    id: 'db-primary-key',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is a primary key in a relational database?',
    options: [
      'The first column in a table',
      'A unique identifier for each row in a table',
      'A column linking two tables',
      'The column with the highest cardinality',
    ],
    answer: 'A unique identifier for each row in a table',
    explanation: 'A primary key uniquely identifies each record. It must be unique and not null. A table can only have one primary key (though it can be composite).',
  },
  {
    id: 'db-foreign-key',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does a foreign key do?',
    options: [
      'Encrypts a column',
      'Creates a unique index',
      'References the primary key of another table, establishing a relationship',
      'Sets the default value of a column',
    ],
    answer: 'References the primary key of another table, establishing a relationship',
    explanation: 'A foreign key creates a referential link between two tables. It ensures that the value in the referencing column exists in the referenced table.',
  },
  {
    id: 'db-insert',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which SQL statement adds a new row to a table?',
    options: ['ADD INTO', 'INSERT INTO', 'PUT INTO', 'CREATE ROW'],
    answer: 'INSERT INTO',
    explanation: 'INSERT INTO table (columns) VALUES (values) adds a new row. All NOT NULL columns without defaults must be provided.',
  },
  {
    id: 'db-update',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which SQL statement modifies existing rows?',
    options: ['MODIFY', 'CHANGE', 'ALTER', 'UPDATE'],
    answer: 'UPDATE',
    explanation: 'UPDATE table SET col = value WHERE condition. Without WHERE, ALL rows are updated — a common mistake.',
  },
  {
    id: 'db-delete',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which SQL statement removes rows from a table?',
    options: ['REMOVE', 'DROP', 'PURGE', 'DELETE'],
    answer: 'DELETE',
    explanation: 'DELETE FROM table WHERE condition removes matching rows. Without WHERE, all rows are deleted. DROP TABLE removes the table structure entirely.',
  },
  {
    id: 'db-null',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which operator correctly checks if a value is NULL in SQL?',
    options: ['= NULL', '== NULL', 'IS NULL', 'EQUALS NULL'],
    answer: 'IS NULL',
    explanation: 'NULL cannot be compared with = because NULL is not a value — it represents the absence of a value. Use IS NULL or IS NOT NULL.',
  },
  {
    id: 'db-order-by',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which SQL clause sorts the result set?',
    options: ['SORT BY', 'ARRANGE BY', 'ORDER BY', 'RANK BY'],
    answer: 'ORDER BY',
    explanation: 'ORDER BY column ASC/DESC sorts the result set. Default order is ASC (ascending). Multiple columns can be used: ORDER BY last_name, first_name.',
  },
  {
    id: 'db-count',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which SQL aggregate function counts rows?',
    options: ['SUM()', 'TOTAL()', 'COUNT()', 'NUM()'],
    answer: 'COUNT()',
    explanation: 'COUNT(*) counts all rows. COUNT(column) counts non-null values in that column.',
  },
  {
    id: 'db-acid',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does ACID stand for in databases?',
    options: [
      'Atomicity, Consistency, Isolation, Durability',
      'Availability, Concurrency, Integrity, Distribution',
      'Atomicity, Concurrency, Idempotency, Durability',
      'Accuracy, Consistency, Integrity, Design',
    ],
    answer: 'Atomicity, Consistency, Isolation, Durability',
    explanation: 'ACID properties ensure reliable database transactions: Atomicity (all-or-nothing), Consistency (valid state transitions), Isolation (concurrent transactions do not interfere), Durability (committed data persists).',
  },
  {
    id: 'db-index-purpose',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the primary purpose of a database index?',
    options: [
      'To store backup copies of data',
      'To speed up data retrieval at the cost of additional write overhead',
      'To enforce uniqueness',
      'To encrypt column data',
    ],
    answer: 'To speed up data retrieval at the cost of additional write overhead',
    explanation: 'Indexes speed up SELECT queries by avoiding full table scans. They slow down INSERT/UPDATE/DELETE because the index must also be maintained.',
  },
  {
    id: 'db-relational',
    category: 'databases',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'A relational database organizes data into tables with rows and columns.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Relational databases (MySQL, PostgreSQL, SQLite) organize data in tables. Tables have a fixed schema with columns (attributes) and rows (records).',
  },
  {
    id: 'db-nosql',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which of the following is a NoSQL database?',
    options: ['PostgreSQL', 'MySQL', 'MongoDB', 'SQLite'],
    answer: 'MongoDB',
    explanation: 'MongoDB is a document-oriented NoSQL database. PostgreSQL, MySQL, and SQLite are relational SQL databases.',
  },
  {
    id: 'db-group-by',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>GROUP BY</code> do in SQL?',
    options: [
      'Joins two tables',
      'Groups rows with the same value so aggregate functions apply per group',
      'Sorts the result set',
      'Filters results after SELECT',
    ],
    answer: 'Groups rows with the same value so aggregate functions apply per group',
    explanation: 'GROUP BY groups rows with the same column values. Used with aggregate functions (COUNT, SUM, AVG) to compute results per group.',
  },
  {
    id: 'db-drop-vs-delete',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the difference between <code>DROP TABLE</code> and <code>DELETE FROM table</code>?',
    options: [
      'DROP TABLE is slower',
      'DELETE removes rows; DROP TABLE removes the table structure and all data',
      'DROP TABLE only deletes rows with NULL values',
      'They are identical',
    ],
    answer: 'DELETE removes rows; DROP TABLE removes the table structure and all data',
    explanation: 'DELETE removes rows (optionally filtered by WHERE). DROP TABLE removes the table definition and all its data from the database entirely.',
  },
  {
    id: 'db-transaction',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does a database transaction provide?',
    options: [
      'A permanent link between two tables',
      'A unit of work that is either fully committed or fully rolled back',
      'A way to speed up bulk inserts',
      'A read-only snapshot of the database',
    ],
    answer: 'A unit of work that is either fully committed or fully rolled back',
    explanation: 'A transaction groups multiple operations. If any fails, a ROLLBACK undoes all changes. If all succeed, a COMMIT makes them permanent.',
  },
  {
    id: 'db-varchar',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the difference between <code>CHAR(10)</code> and <code>VARCHAR(10)</code>?',
    options: [
      'CHAR stores Unicode, VARCHAR stores ASCII',
      'CHAR is always 10 bytes; VARCHAR stores only as many bytes as needed up to 10',
      'CHAR is for numbers, VARCHAR for text',
      'They are the same',
    ],
    answer: 'CHAR is always 10 bytes; VARCHAR stores only as many bytes as needed up to 10',
    explanation: 'CHAR is fixed-length (padded with spaces). VARCHAR is variable-length, using only what is needed. Use CHAR for fixed-size data (ISO codes), VARCHAR for variable text.',
  },
  {
    id: 'db-limit',
    category: 'databases',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>SELECT * FROM users LIMIT 10</code> do?',
    options: [
      'Returns users with ID up to 10',
      'Returns only the first 10 rows of the result',
      'Caps the table at 10 rows',
      'Limits execution time to 10 seconds',
    ],
    answer: 'Returns only the first 10 rows of the result',
    explanation: 'LIMIT restricts the number of rows returned. Combine with OFFSET for pagination: LIMIT 10 OFFSET 20 returns rows 21-30.',
  },
  {
    id: 'db-sql-case-sensitivity',
    category: 'databases',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'SQL keywords like SELECT and WHERE are case-sensitive.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'SQL keywords are case-insensitive. SELECT, select, and Select are all valid. Data values may be case-sensitive depending on the collation settings.',
  },

  // --- medium (20) ---
  {
    id: 'db-inner-join',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does an INNER JOIN return?',
    options: [
      'All rows from both tables',
      'Only rows where there is a match in both tables',
      'All rows from the left table and matching from the right',
      'The Cartesian product of both tables',
    ],
    answer: 'Only rows where there is a match in both tables',
    explanation: 'INNER JOIN returns rows that have matching values in both joined tables. Rows without a match are excluded from the result.',
  },
  {
    id: 'db-left-join',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A LEFT JOIN returns:',
    options: [
      'All rows from the right table and matching from the left',
      'All rows from the left table and matching rows from the right; unmatched right rows are NULL',
      'Only rows with NULLs',
      'The intersection of both tables',
    ],
    answer: 'All rows from the left table and matching rows from the right; unmatched right rows are NULL',
    explanation: 'LEFT JOIN keeps all rows from the left table. Where there is no match in the right table, right columns are NULL.',
  },
  {
    id: 'db-normalization',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the main goal of database normalization?',
    options: [
      'To maximize query performance',
      'To eliminate data redundancy and improve data integrity',
      'To compress data storage',
      'To partition tables across servers',
    ],
    answer: 'To eliminate data redundancy and improve data integrity',
    explanation: 'Normalization organizes columns and tables to reduce data duplication. Normal forms (1NF, 2NF, 3NF, BCNF) progressively eliminate different types of redundancy.',
  },
  {
    id: 'db-stored-procedure',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a stored procedure?',
    options: [
      'A query that is cached by the database',
      'A precompiled SQL code block stored in the database that can be called by name',
      'A backup copy of a table',
      'An automatic trigger on INSERT',
    ],
    answer: 'A precompiled SQL code block stored in the database that can be called by name',
    explanation: 'Stored procedures are named SQL code blocks stored on the server. They can accept parameters, run logic, and be called from applications, reducing round-trips.',
  },
  {
    id: 'db-trigger',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A database trigger fires:',
    options: [
      'On a schedule (like a cron job)',
      'Automatically before or after INSERT, UPDATE, or DELETE on a table',
      'When a stored procedure is called',
      'Only during transactions',
    ],
    answer: 'Automatically before or after INSERT, UPDATE, or DELETE on a table',
    explanation: 'Triggers are automatic procedures that fire on table events. BEFORE triggers can modify the data; AFTER triggers typically log or sync.',
  },
  {
    id: 'db-view',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a database view?',
    options: [
      'A physical copy of a table',
      'A virtual table defined by a stored SELECT query',
      'A read-only backup',
      'An index on multiple columns',
    ],
    answer: 'A virtual table defined by a stored SELECT query',
    explanation: 'A view is a named query stored in the database. Querying a view executes the underlying SELECT. Some views are updatable, others are not.',
  },
  {
    id: 'db-isolation-levels',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which isolation level prevents dirty reads but still allows non-repeatable reads?',
    options: ['Serializable', 'Read Uncommitted', 'Read Committed', 'Repeatable Read'],
    answer: 'Read Committed',
    explanation: 'Read Committed (the default in many DBs) prevents reading uncommitted data (dirty reads) but allows non-repeatable reads — the same row read twice may differ if another transaction commits between reads.',
  },
  {
    id: 'db-n-plus-one',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the N+1 query problem?',
    options: [
      'Running one query for the full table then one query per relationship',
      'Having more than N queries in a single transaction',
      'Joining more than N tables in one query',
      'Running a query N times in a loop',
    ],
    answer: 'Running one query for the full table then one query per relationship',
    explanation: 'N+1: 1 query fetches N records, then N more queries fetch related data for each record. Solved by JOIN or eager loading.',
  },
  {
    id: 'db-denormalization',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Denormalization trades what for what?',
    options: [
      'Write speed for read speed',
      'Data integrity for query performance',
      'Storage space for CPU efficiency',
      'ACID compliance for availability',
    ],
    answer: 'Data integrity for query performance',
    explanation: 'Denormalization intentionally introduces redundancy to reduce JOIN complexity and improve read performance. It increases the risk of update anomalies.',
  },
  {
    id: 'db-document-db',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'In a document database like MongoDB, data is stored as:',
    options: [
      'Rows and columns like SQL',
      'Key-value pairs only',
      'Semi-structured documents (typically JSON/BSON)',
      'Graph nodes and edges',
    ],
    answer: 'Semi-structured documents (typically JSON/BSON)',
    explanation: 'Document databases store JSON-like documents. Each document can have a different structure, making them flexible for evolving schemas.',
  },
  {
    id: 'db-index-tradeoff',
    category: 'databases',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'Adding more indexes always improves overall database performance.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Indexes speed up reads but slow down writes (INSERT/UPDATE/DELETE must update every index). They also use disk space. Too many indexes can degrade write-heavy workloads.',
  },
  {
    id: 'db-cursor',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a database cursor?',
    options: [
      'A pointer used to iterate row by row through a query result set',
      'An index that improves query performance',
      'A way to lock rows during updates',
      'A type of stored procedure',
    ],
    answer: 'A pointer used to iterate row by row through a query result set',
    explanation: 'Cursors allow processing one row at a time in stored procedures. They are often inefficient compared to set-based SQL operations and should be used sparingly.',
  },
  {
    id: 'db-optimistic-locking',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Optimistic locking works by:',
    options: [
      'Locking a row at read time until the transaction completes',
      'Checking a version/timestamp at write time to detect if another transaction modified the row',
      'Preventing concurrent reads of the same row',
      'Automatically retrying failed transactions',
    ],
    answer: 'Checking a version/timestamp at write time to detect if another transaction modified the row',
    explanation: 'Optimistic locking assumes conflicts are rare. It reads without locking, then at write time checks if the version changed. If so, the transaction is rejected and must retry.',
  },
  {
    id: 'db-explain',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>EXPLAIN</code> do in SQL?',
    options: [
      'Returns a human-readable description of the table schema',
      'Shows the query execution plan, including which indexes are used',
      'Runs the query in debug mode',
      'Validates the SQL syntax',
    ],
    answer: 'Shows the query execution plan, including which indexes are used',
    explanation: 'EXPLAIN (or EXPLAIN ANALYZE in PostgreSQL) shows how the database plans to execute a query — scans, joins, index usage. Essential for query optimization.',
  },
  {
    id: 'db-sharding',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Database sharding means:',
    options: [
      'Replicating the database across servers',
      'Partitioning data horizontally across multiple servers',
      'Encrypting each row separately',
      'Splitting a table into two tables by column',
    ],
    answer: 'Partitioning data horizontally across multiple servers',
    explanation: 'Sharding splits data across multiple database servers (shards) based on a shard key. Each shard holds a subset of rows. It scales writes but adds complexity.',
  },
  {
    id: 'db-replication',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is database replication?',
    options: [
      'Copying data to a backup file',
      'Copying data from one database server to one or more replicas',
      'Normalizing a database schema',
      'Partitioning tables by row',
    ],
    answer: 'Copying data from one database server to one or more replicas',
    explanation: 'Replication keeps copies of the database synchronized across servers. Primary-replica replication routes writes to the primary and reads to replicas, improving read throughput.',
  },
  {
    id: 'db-having',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Why can\'t you use WHERE on aggregate functions? What do you use instead?',
    options: [
      'Use FILTER instead of WHERE for aggregates',
      'WHERE runs after GROUP BY; use HAVING to filter on aggregates',
      'WHERE runs before GROUP BY; use HAVING to filter on aggregates',
      'You must use a subquery',
    ],
    answer: 'WHERE runs before GROUP BY; use HAVING to filter on aggregates',
    explanation: 'WHERE filters individual rows before aggregation. HAVING filters after GROUP BY, so it can reference aggregates like COUNT(*) or SUM(amount).',
  },
  {
    id: 'db-subquery',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a correlated subquery?',
    options: [
      'A subquery that returns multiple rows',
      'A subquery that references a column from the outer query and runs once per outer row',
      'A subquery inside a HAVING clause',
      'A subquery that runs only once',
    ],
    answer: 'A subquery that references a column from the outer query and runs once per outer row',
    explanation: 'Correlated subqueries re-execute for each row of the outer query because they reference outer columns. They can be slow — often replaceable with JOINs.',
  },
  {
    id: 'db-b-tree-index',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Most relational databases use which data structure for indexes by default?',
    options: ['Hash table', 'B-tree (or B+ tree)', 'Binary search tree', 'Skip list'],
    answer: 'B-tree (or B+ tree)',
    explanation: 'B+ trees are the default index structure. They support equality and range queries efficiently and stay balanced. Hash indexes only support equality.',
  },
  {
    id: 'db-window-function',
    category: 'databases',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does a window function like <code>ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC)</code> do?',
    options: [
      'Groups rows and returns one row per group',
      'Assigns a row number within each department partition ordered by salary',
      'Deletes duplicate rows',
      'Creates a temporary column',
    ],
    answer: 'Assigns a row number within each department partition ordered by salary',
    explanation: 'Window functions compute values across related rows without collapsing them. PARTITION BY defines the window; ORDER BY determines ordering within. Row numbers restart per department.',
  },

  // --- hard (15) ---
  {
    id: 'db-mvcc',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is MVCC (Multi-Version Concurrency Control)?',
    options: [
      'A locking strategy that blocks all reads during writes',
      'A technique where each transaction sees a consistent snapshot of data, with multiple versions kept simultaneously',
      'A replication protocol for multi-master databases',
      'A way to compress old table versions',
    ],
    answer: 'A technique where each transaction sees a consistent snapshot of data, with multiple versions kept simultaneously',
    explanation: 'MVCC (used in PostgreSQL, MySQL InnoDB) maintains multiple versions of rows. Readers see a consistent snapshot without blocking writers. Writers create new versions instead of overwriting.',
  },
  {
    id: 'db-wal',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is a Write-Ahead Log (WAL)?',
    options: [
      'A queue for pending write operations',
      'A log file written before data pages are modified, enabling crash recovery and replication',
      'A buffer for batching writes',
      'A history of all SELECT queries',
    ],
    answer: 'A log file written before data pages are modified, enabling crash recovery and replication',
    explanation: 'WAL writes changes to a log before modifying actual data. On crash, the DB replays the WAL to restore consistency. It also enables replication by shipping the WAL.',
  },
  {
    id: 'db-phantom-read',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is a phantom read in database transactions?',
    options: [
      'Reading a row that was deleted mid-transaction',
      'A query returning different rows on re-execution because another transaction inserted matching rows',
      'Reading uncommitted data',
      'A read that is rolled back',
    ],
    answer: 'A query returning different rows on re-execution because another transaction inserted matching rows',
    explanation: 'Phantom reads: a query for "all users with age > 30" returns different rows when run twice in the same transaction because another transaction inserted/deleted rows in between. Serializable isolation prevents this.',
  },
  {
    id: 'db-two-phase-commit',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is the two-phase commit (2PC) protocol used for?',
    options: [
      'Running transactions in two steps for performance',
      'Ensuring atomicity of transactions distributed across multiple databases',
      'Locking rows in two passes to prevent deadlocks',
      'Compressing commit logs',
    ],
    answer: 'Ensuring atomicity of transactions distributed across multiple databases',
    explanation: '2PC coordinates a distributed transaction: Phase 1 (prepare) asks all participants if they can commit. Phase 2 (commit/abort) finalizes based on responses. Ensures all-or-nothing across nodes.',
  },
  {
    id: 'db-column-store',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is the main advantage of a columnar storage database over row-based storage for analytics?',
    options: [
      'Columnar databases are better for transactional writes',
      'Columnar storage reads only needed columns, enabling high compression and fast aggregations',
      'Columnar databases support more data types',
      'Columnar databases are easier to shard',
    ],
    answer: 'Columnar storage reads only needed columns, enabling high compression and fast aggregations',
    explanation: 'Columnar stores (Redshift, BigQuery, Parquet) store each column together. Analytics queries that access few columns skip unused ones, and similar values compress well.',
  },
  {
    id: 'db-crdt',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is a CRDT (Conflict-free Replicated Data Type)?',
    options: [
      'A database schema for conflict detection',
      'A data structure that can be updated concurrently across replicas and merged without conflicts',
      'A cryptographic hashing technique for data integrity',
      'A cache invalidation strategy',
    ],
    answer: 'A data structure that can be updated concurrently across replicas and merged without conflicts',
    explanation: 'CRDTs are designed so any two replicas can be merged automatically. Used in distributed systems (Riak, Redis, Cassandra counters) to allow writes without coordination.',
  },
  {
    id: 'db-partial-index',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is a partial index in PostgreSQL?',
    options: [
      'An index on a subset of columns',
      'An index that only covers rows matching a WHERE condition',
      'A compressed index for large tables',
      'A non-unique index',
    ],
    answer: 'An index that only covers rows matching a WHERE condition',
    explanation: 'A partial index (CREATE INDEX ON t(col) WHERE condition) indexes only qualifying rows. Smaller and faster than a full index when queries often filter the same condition.',
  },
  {
    id: 'db-explain-analyze',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In PostgreSQL, what is the key difference between <code>EXPLAIN</code> and <code>EXPLAIN ANALYZE</code>?',
    options: [
      'EXPLAIN shows the plan, ANALYZE validates the SQL syntax',
      'EXPLAIN ANALYZE actually executes the query and shows real vs estimated row counts and timing',
      'EXPLAIN is read-only, ANALYZE can modify data',
      'EXPLAIN ANALYZE only works on SELECT statements',
    ],
    answer: 'EXPLAIN ANALYZE actually executes the query and shows real vs estimated row counts and timing',
    explanation: 'EXPLAIN shows the planner\'s estimated plan. EXPLAIN ANALYZE runs the query and compares estimates to actual rows and timing — revealing planner estimation errors.',
  },
  {
    id: 'db-seq-scan-vs-index',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'When might a database planner choose a sequential scan over an index scan?',
    options: [
      'When the index is fragmented',
      'When the query returns a large percentage of the table (index overhead not worth it)',
      'When the WHERE clause uses IS NULL',
      'Sequential scans are never faster',
    ],
    answer: 'When the query returns a large percentage of the table (index overhead not worth it)',
    explanation: 'If most rows match the query, a sequential scan is faster because index lookups involve random I/O. The planner uses table statistics to estimate row counts and choose.',
  },
  {
    id: 'db-hot-update',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In PostgreSQL, what is a HOT (Heap Only Tuple) update?',
    options: [
      'An update that bypasses the WAL',
      'An update that does not modify indexed columns, allowing the new row version to be found without updating indexes',
      'An in-memory update',
      'An update during a hot standby state',
    ],
    answer: 'An update that does not modify indexed columns, allowing the new row version to be found without updating indexes',
    explanation: 'HOT updates occur when an updated row\'s new version fits on the same page and no indexed column changed. This avoids index maintenance, improving update performance.',
  },
  {
    id: 'db-event-sourcing',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In event sourcing, what is the source of truth for application state?',
    options: [
      'The current state of the database tables',
      'The log of all events that have occurred',
      'A distributed cache',
      'A snapshot taken at startup',
    ],
    answer: 'The log of all events that have occurred',
    explanation: 'Event sourcing stores all changes as an immutable sequence of events. Current state is derived by replaying events. This enables audit logs, time travel, and event replay.',
  },
  {
    id: 'db-range-partition',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is the benefit of range partitioning a large time-series table by date?',
    options: [
      'Queries are automatically parallelized',
      'Queries with date range filters only scan relevant partitions, and old partitions can be dropped quickly',
      'Data is compressed per partition',
      'Inserts are evenly distributed',
    ],
    answer: 'Queries with date range filters only scan relevant partitions, and old partitions can be dropped quickly',
    explanation: 'Range partitioning (by month/year) enables partition pruning — the planner skips irrelevant partitions. Dropping old partitions (vs DELETE) is near-instant and reclaims disk space.',
  },
  {
    id: 'db-json-query',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In PostgreSQL, what does the <code>-></code> operator do on a JSONB column?',
    options: [
      'Casts the column to text',
      'Returns a JSON object field as a JSON value',
      'Inserts a new key into the JSON',
      'Checks if a key exists',
    ],
    answer: 'Returns a JSON object field as a JSON value',
    explanation: 'data->\'key\' returns the JSON value for that key. data->>\'key\' returns it as text. Use #> for nested paths. GIN indexes on JSONB enable fast key/value queries.',
  },
  {
    id: 'db-deadlock-detect',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'How do databases typically detect deadlocks?',
    options: [
      'By setting a query timeout',
      'By maintaining a wait-for graph and detecting cycles',
      'By rolling back all transactions after 1 second',
      'By preventing concurrent writes',
    ],
    answer: 'By maintaining a wait-for graph and detecting cycles',
    explanation: 'The database maintains a wait-for graph where nodes are transactions and edges represent "waiting for lock". A cycle means deadlock. One transaction is chosen as the victim and rolled back.',
  },
  {
    id: 'db-vectorized-exec',
    category: 'databases',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is vectorized query execution?',
    options: [
      'Running queries in parallel threads',
      'Processing data in batches (vectors) per operator instead of one row at a time, improving CPU efficiency',
      'Using GPU acceleration for queries',
      'Converting row storage to column storage at query time',
    ],
    answer: 'Processing data in batches (vectors) per operator instead of one row at a time, improving CPU efficiency',
    explanation: 'Vectorized execution passes batches of column values (vectors) through operators instead of one row at a time. This reduces function call overhead and enables SIMD CPU instructions. Used in DuckDB, ClickHouse.',
  },
];

export default databases;
