import type { Question } from '../types';

const generalcs: Question[] = [
  // --- easy (20) ---
  {
    id: 'cs-binary-base',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'The binary number system uses which base?',
    options: ['Base 8', 'Base 10', 'Base 2', 'Base 16'],
    answer: 'Base 2',
    explanation: 'Binary uses only 0 and 1 (base 2). Octal is base 8, decimal is base 10, hexadecimal is base 16.',
  },
  {
    id: 'cs-bit-byte',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'How many bits are in a byte?',
    options: ['4', '8', '16', '32'],
    answer: '8',
    explanation: 'A byte consists of 8 bits. This is a fundamental unit in computing.',
  },
  {
    id: 'cs-stack-lifo',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'A stack follows which ordering principle?',
    options: ['FIFO', 'LIFO', 'Random access', 'Priority'],
    answer: 'LIFO',
    explanation: 'A stack is Last In, First Out — the most recently added item is the first to be removed. Like a stack of plates.',
  },
  {
    id: 'cs-queue-fifo',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'A queue follows which ordering principle?',
    options: ['LIFO', 'FIFO', 'Random access', 'Priority'],
    answer: 'FIFO',
    explanation: 'A queue is First In, First Out — like a line at a store. Items are removed in the order they were added.',
  },
  {
    id: 'cs-cpu-purpose',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does CPU stand for?',
    options: ['Central Processing Unit', 'Core Processing Utility', 'Central Program Utility', 'Core Processor Unit'],
    answer: 'Central Processing Unit',
    explanation: 'CPU stands for Central Processing Unit — the main chip that executes program instructions.',
  },
  {
    id: 'cs-ram-volatile',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'RAM is volatile memory — its contents are lost when power is removed.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'RAM (Random Access Memory) requires power to retain data. When the computer is turned off, RAM contents are erased.',
  },
  {
    id: 'cs-boolean-two-values',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'A Boolean value can only be true or false.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Booleans represent binary logic with exactly two values: true and false (or 1 and 0 in hardware terms).',
  },
  {
    id: 'cs-recursion-base',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What must every recursive function have to prevent infinite recursion?',
    options: ['A loop', 'A base case', 'A return type', 'A global variable'],
    answer: 'A base case',
    explanation: 'A base case is a condition that stops the recursion. Without it, the function will call itself forever until a stack overflow.',
  },
  {
    id: 'cs-compile-vs-interpret',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which best describes a compiled language?',
    options: [
      'Code is translated to machine code at runtime',
      'Code is translated to machine code before execution',
      'Code runs inside a virtual machine',
      'Code is always faster than interpreted',
    ],
    answer: 'Code is translated to machine code before execution',
    explanation: 'Compiled languages (like C, C++) convert source code to machine code before running. Interpreted languages (like Python) translate and execute line by line at runtime.',
  },
  {
    id: 'cs-ip-address',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does IP stand for in networking?',
    options: ['Internet Protocol', 'Internal Process', 'Input Port', 'Interface Program'],
    answer: 'Internet Protocol',
    explanation: 'IP stands for Internet Protocol — the fundamental communication standard that defines addressing and routing of packets on the internet.',
  },
  {
    id: 'cs-oop-four',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which is NOT one of the four pillars of object-oriented programming?',
    options: ['Encapsulation', 'Polymorphism', 'Recursion', 'Abstraction'],
    answer: 'Recursion',
    explanation: 'The four OOP pillars are Encapsulation, Abstraction, Inheritance, and Polymorphism. Recursion is a programming technique, not an OOP pillar.',
  },
  {
    id: 'cs-float-precision',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Floating-point numbers can represent all decimal values exactly in binary.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Many decimal fractions (like 0.1) cannot be represented exactly in binary floating-point. This is why 0.1 + 0.2 != 0.3 in most languages.',
  },
  {
    id: 'cs-linked-list-node',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'A node in a singly linked list typically contains what?',
    options: [
      'A value and a pointer to the previous node',
      'A value and a pointer to the next node',
      'Two values',
      'A key, value, and hash',
    ],
    answer: 'A value and a pointer to the next node',
    explanation: 'A singly linked list node holds data and a pointer (reference) to the next node. The last node\'s pointer is null.',
  },
  {
    id: 'cs-http-port',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the default port for HTTP?',
    options: ['443', '21', '80', '8080'],
    answer: '80',
    explanation: 'HTTP uses port 80 by default. HTTPS uses port 443. These are well-known port numbers defined by IANA.',
  },
  {
    id: 'cs-big-o-constant',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does O(1) time complexity mean?',
    options: [
      'The operation takes 1 millisecond',
      'The operation\'s time grows linearly with input',
      'The operation takes constant time regardless of input size',
      'The operation is done in one CPU cycle',
    ],
    answer: 'The operation\'s time grows linearly with input',
    explanation: 'Wait — O(1) means constant time: the operation\'s duration does not depend on input size. Array index access is O(1).',
  },
  {
    id: 'cs-big-o-constant-fix',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'An O(1) operation always takes less time than an O(n) operation.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Big O describes how time scales with input size, not absolute time. For small inputs, an O(n) operation may be faster than an O(1) one with a large constant factor.',
  },
  {
    id: 'cs-os-kernel',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the kernel in an operating system?',
    options: [
      'The user interface layer',
      'The core component that manages hardware resources and system calls',
      'The bootloader',
      'The file system driver',
    ],
    answer: 'The core component that manages hardware resources and system calls',
    explanation: 'The kernel is the OS core that interfaces with hardware, manages memory, processes, and I/O, and provides system calls to user programs.',
  },
  {
    id: 'cs-dns',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does DNS do?',
    options: [
      'Encrypts network traffic',
      'Translates domain names to IP addresses',
      'Routes packets across the internet',
      'Assigns IP addresses to devices',
    ],
    answer: 'Translates domain names to IP addresses',
    explanation: 'DNS (Domain Name System) maps human-readable domain names (like example.com) to IP addresses that computers use to communicate.',
  },
  {
    id: 'cs-thread-vs-process',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the main difference between a thread and a process?',
    options: [
      'A process is faster than a thread',
      'Threads share memory within a process; processes have separate memory',
      'A thread is larger than a process',
      'Processes can run concurrently, threads cannot',
    ],
    answer: 'Threads share memory within a process; processes have separate memory',
    explanation: 'Processes are independent with separate address spaces. Threads are lightweight units within a process that share the same memory space.',
  },
  {
    id: 'cs-ascii',
    category: 'general-cs',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'How many characters does ASCII define?',
    options: ['64', '128', '256', '512'],
    answer: '128',
    explanation: 'ASCII defines 128 characters (0-127), including control characters, digits, uppercase/lowercase letters, and symbols. Extended ASCII uses 256 characters.',
  },

  // --- medium (20) ---
  {
    id: 'cs-hash-collision',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'In a hash table, what is a collision?',
    options: [
      'When two keys produce the same hash value',
      'When the table runs out of memory',
      'When a key is deleted while being looked up',
      'When two values are equal',
    ],
    answer: 'When two keys produce the same hash value',
    explanation: 'A collision occurs when two different keys map to the same hash bucket. Hash tables handle collisions with chaining (linked list per bucket) or open addressing.',
  },
  {
    id: 'cs-tree-balanced',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the time complexity of search in a balanced Binary Search Tree?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 'O(log n)',
    explanation: 'A balanced BST halves the search space at each node. With n nodes the depth is log n, giving O(log n) search time.',
  },
  {
    id: 'cs-deadlock',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a deadlock in concurrent programming?',
    options: [
      'A program crash due to stack overflow',
      'Two or more threads permanently blocking each other waiting for resources the other holds',
      'A memory access outside allocated bounds',
      'A thread that never terminates',
    ],
    answer: 'Two or more threads permanently blocking each other waiting for resources the other holds',
    explanation: 'Deadlock: Thread A holds lock 1 and waits for lock 2; Thread B holds lock 2 and waits for lock 1. Neither can proceed.',
  },
  {
    id: 'cs-little-endian',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'In little-endian byte order, how is the value stored in memory?',
    options: [
      'Most significant byte first',
      'Least significant byte first',
      'Alternating bytes',
      'Depends on the value',
    ],
    answer: 'Least significant byte first',
    explanation: 'Little-endian (used by x86/x64) stores the least significant byte at the lowest address. Big-endian (used by network protocols) stores the most significant byte first.',
  },
  {
    id: 'cs-cache-hit',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a cache hit?',
    options: [
      'When the cache is full',
      'When requested data is found in the cache',
      'When the cache needs to be invalidated',
      'When two cache entries conflict',
    ],
    answer: 'When requested data is found in the cache',
    explanation: 'A cache hit means the requested data is already in the cache (no need to fetch from slower storage). A cache miss means it is not and must be fetched.',
  },
  {
    id: 'cs-virtual-memory',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is virtual memory?',
    options: [
      'Memory on a remote server',
      'An abstraction that lets a process use more memory than physically available using disk as overflow',
      'GPU memory',
      'Memory reserved for the OS kernel',
    ],
    answer: 'An abstraction that lets a process use more memory than physically available using disk as overflow',
    explanation: 'Virtual memory maps a process\'s logical address space to physical RAM and disk (swap space). Pages not in RAM are stored on disk and swapped in when needed.',
  },
  {
    id: 'cs-tcp-udp',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which protocol prioritizes speed over reliability, with no guaranteed delivery?',
    options: ['TCP', 'HTTP', 'UDP', 'HTTPS'],
    answer: 'UDP',
    explanation: 'UDP (User Datagram Protocol) is connectionless and does not guarantee delivery or ordering. It is used where speed matters — video streaming, gaming, DNS.',
  },
  {
    id: 'cs-mutex',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a mutex used for in concurrency?',
    options: [
      'Multiplexing network connections',
      'Ensuring only one thread accesses a shared resource at a time',
      'Limiting CPU usage of a thread',
      'Sending messages between processes',
    ],
    answer: 'Ensuring only one thread accesses a shared resource at a time',
    explanation: 'A mutex (mutual exclusion lock) is a synchronization primitive. A thread acquires it before accessing shared state and releases it after. Others block until it is free.',
  },
  {
    id: 'cs-graph-bfs',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Breadth-First Search (BFS) uses which data structure?',
    options: ['Stack', 'Heap', 'Queue', 'Priority queue'],
    answer: 'Queue',
    explanation: 'BFS explores nodes level by level using a queue (FIFO). Depth-First Search (DFS) uses a stack (or the call stack via recursion).',
  },
  {
    id: 'cs-two-complement',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which representation is most commonly used to store negative integers in modern hardware?',
    options: ["Sign and magnitude", "One's complement", "Two's complement", 'BCD'],
    answer: "Two's complement",
    explanation: "Two's complement is the standard because addition/subtraction work without special cases. Flipping all bits and adding 1 gives the negation.",
  },
  {
    id: 'cs-immutable-benefits',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which is a key benefit of immutability in concurrent programs?',
    options: [
      'Reduces CPU usage',
      'Eliminates the need for synchronization since data cannot change',
      'Reduces memory usage',
      'Improves garbage collection speed',
    ],
    answer: 'Eliminates the need for synchronization since data cannot change',
    explanation: 'Immutable data cannot be modified after creation, so multiple threads can read it simultaneously without locks or synchronization.',
  },
  {
    id: 'cs-dfs-stack',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'Depth-First Search (DFS) can be implemented iteratively using a stack.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'DFS explores as deep as possible before backtracking. It naturally uses the call stack in recursion, but can also be implemented with an explicit stack.',
  },
  {
    id: 'cs-race-condition',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a race condition?',
    options: [
      'A performance competition between two algorithms',
      'A bug where outcome depends on the timing of concurrent operations',
      'A scheduling algorithm in the OS',
      'When two processes access the same file at once without issue',
    ],
    answer: 'A bug where outcome depends on the timing of concurrent operations',
    explanation: 'A race condition occurs when the correctness of a program depends on the relative timing or interleaving of multiple threads or processes accessing shared state.',
  },
  {
    id: 'cs-osi-layers',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'How many layers does the OSI model have?',
    options: ['4', '5', '6', '7'],
    answer: '7',
    explanation: 'The OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application.',
  },
  {
    id: 'cs-inheritance-poly',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which OOP concept allows a subclass to override a parent class method and be called through the parent type?',
    options: ['Encapsulation', 'Abstraction', 'Polymorphism', 'Composition'],
    answer: 'Polymorphism',
    explanation: 'Polymorphism allows objects of different subclasses to be treated as their parent type, with method calls dispatched to the appropriate subclass implementation.',
  },
  {
    id: 'cs-heap-vs-stack-mem',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'In memory management, what is stored on the stack vs the heap?',
    options: [
      'Stack: global variables. Heap: local variables',
      'Stack: local variables and function call frames. Heap: dynamically allocated memory',
      'Stack: all variables. Heap: code',
      'They store the same things',
    ],
    answer: 'Stack: local variables and function call frames. Heap: dynamically allocated memory',
    explanation: 'The call stack holds local variables, return addresses, and function frames. The heap is for dynamically allocated objects (malloc/new). The heap grows unpredictably; the stack grows/shrinks with function calls.',
  },
  {
    id: 'cs-memoization',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is memoization?',
    options: [
      'Storing the algorithm in memory for faster lookup',
      'Caching the results of expensive function calls based on their inputs',
      'Compiling code to native instructions',
      'Recording program execution for replay',
    ],
    answer: 'Caching the results of expensive function calls based on their inputs',
    explanation: 'Memoization stores the result of a function call keyed by its arguments. Subsequent calls with the same arguments return the cached result, avoiding recomputation.',
  },
  {
    id: 'cs-solid-single',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does the "S" in SOLID stand for?',
    options: [
      'Separation of Concerns',
      'Single Responsibility Principle',
      'Substitution Principle',
      'Static Typing',
    ],
    answer: 'Single Responsibility Principle',
    explanation: 'S in SOLID is the Single Responsibility Principle: a class should have only one reason to change — it should do one thing.',
  },
  {
    id: 'cs-latency-bandwidth',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the difference between latency and bandwidth?',
    options: [
      'Latency is max data rate; bandwidth is delay',
      'Latency is the delay for data to travel; bandwidth is the max data transfer rate',
      'They mean the same thing',
      'Bandwidth is measured in ms; latency in Mbps',
    ],
    answer: 'Latency is the delay for data to travel; bandwidth is the max data transfer rate',
    explanation: 'Latency (ms) is how long it takes a packet to travel from source to destination. Bandwidth (Mbps/Gbps) is the maximum throughput of a connection.',
  },
  {
    id: 'cs-encapsulation',
    category: 'general-cs',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Encapsulation in OOP primarily refers to:',
    options: [
      'Making all methods static',
      'Hiding internal state and requiring interaction through a public interface',
      'Using generics for type safety',
      'Avoiding global variables',
    ],
    answer: 'Hiding internal state and requiring interaction through a public interface',
    explanation: 'Encapsulation bundles data and the methods that operate on it, hiding internal implementation details and exposing only what is needed.',
  },

  // --- hard (15) ---
  {
    id: 'cs-cap-theorem',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the CAP theorem state about distributed systems?',
    options: [
      'A system can have Consistency, Availability, and Partition tolerance simultaneously',
      'A system can guarantee at most two of: Consistency, Availability, and Partition tolerance',
      'Consistency is always more important than Availability',
      'Partition tolerance can be eliminated with good network design',
    ],
    answer: 'A system can guarantee at most two of: Consistency, Availability, and Partition tolerance',
    explanation: 'CAP theorem: in a distributed system, during a network partition you must choose between Consistency (every read gets the latest write) and Availability (every request gets a response).',
  },
  {
    id: 'cs-amortized',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does amortized O(1) mean for dynamic array append?',
    options: [
      'Every single append takes O(1) time',
      'The average cost per append across many operations is O(1), even though occasional resizes cost O(n)',
      'Appends only cost O(1) after the array is full',
      'Amortized means the constant is very small',
    ],
    answer: 'The average cost per append across many operations is O(1), even though occasional resizes cost O(n)',
    explanation: 'Dynamic arrays double in size when full. Resizing is O(n) but rare. Spread over all operations, each append costs O(1) on average — this is amortized analysis.',
  },
  {
    id: 'cs-p-vs-np',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In complexity theory, what does the P vs NP problem ask?',
    options: [
      'Whether parallel algorithms are always faster than sequential ones',
      'Whether problems whose solutions can be verified in polynomial time can also be solved in polynomial time',
      'Whether all O(n^2) algorithms can be reduced to O(n log n)',
      'Whether deterministic and non-deterministic Turing machines are equivalent',
    ],
    answer: 'Whether problems whose solutions can be verified in polynomial time can also be solved in polynomial time',
    explanation: 'P is the class of problems solvable in polynomial time. NP is the class verifiable in polynomial time. P vs NP asks if every NP problem is also in P. It is an unsolved million-dollar problem.',
  },
  {
    id: 'cs-turing-complete',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What makes a system Turing complete?',
    options: [
      'It can run any program within a set time limit',
      'It can simulate any Turing machine — i.e., compute any computable function given enough time and memory',
      'It supports assembly language',
      'It has both RAM and CPU',
    ],
    answer: 'It can simulate any Turing machine — i.e., compute any computable function given enough time and memory',
    explanation: 'A system is Turing complete if it can simulate a Turing machine. Practically, this means it can express any algorithm. Most general-purpose programming languages are Turing complete.',
  },
  {
    id: 'cs-consistent-hashing',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What problem does consistent hashing solve in distributed systems?',
    options: [
      'Preventing hash collisions',
      'Minimizing data remapping when nodes are added or removed from a cluster',
      'Ensuring hash functions are collision-resistant',
      'Balancing CPU load across servers',
    ],
    answer: 'Minimizing data remapping when nodes are added or removed from a cluster',
    explanation: 'Consistent hashing ensures that when a node is added/removed, only a fraction of keys need to be remapped (vs. all keys with modulo hashing), minimizing data movement.',
  },
  {
    id: 'cs-bloom-filter',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'A Bloom filter can produce false positives but not false negatives. What does this mean?',
    options: [
      'It may say an item is absent when it is present',
      'It may say an item is present when it is not, but will never say absent when present',
      'It is always correct',
      'It may say an item is absent when it is present and vice versa',
    ],
    answer: 'It may say an item is present when it is not, but will never say absent when present',
    explanation: 'A Bloom filter may return "probably present" for something never inserted (false positive), but "definitely absent" is always correct (no false negatives). It is a space-efficient probabilistic structure.',
  },
  {
    id: 'cs-lsm-tree',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'An LSM tree (Log-Structured Merge Tree) optimizes for which operation?',
    options: ['Random reads', 'Sequential reads', 'High-throughput writes', 'In-place updates'],
    answer: 'High-throughput writes',
    explanation: 'LSM trees buffer writes in memory (memtable) and flush to sorted on-disk segments (SSTables). Writes are sequential, avoiding random I/O. Used in LevelDB, Cassandra, RocksDB.',
  },
  {
    id: 'cs-amdahl-law',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: "Amdahl's Law states that the maximum speedup from parallelism is limited by:",
    options: [
      'The number of processors available',
      'The sequential (non-parallelizable) fraction of the program',
      'The memory bandwidth',
      'The clock speed of individual cores',
    ],
    answer: 'The sequential (non-parallelizable) fraction of the program',
    explanation: "Amdahl's Law: if 5% of a program is sequential, no amount of parallelism can make it more than 20x faster. The serial portion is the ceiling.",
  },
  {
    id: 'cs-functor',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In functional programming, a functor is:',
    options: [
      'A function that takes another function as input',
      'A type that implements a map operation preserving structure',
      'A pure function with no side effects',
      'A function that returns a function',
    ],
    answer: 'A type that implements a map operation preserving structure',
    explanation: 'A functor is a type (like a container) that can be mapped over with a function that transforms its contents while preserving the structure. Arrays with .map() are functors.',
  },
  {
    id: 'cs-merkle-tree',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is a Merkle tree primarily used for?',
    options: [
      'Efficient range queries',
      'Efficient integrity verification of data blocks',
      'Storing sorted key-value pairs',
      'Compressing tree traversal paths',
    ],
    answer: 'Efficient integrity verification of data blocks',
    explanation: 'A Merkle tree hashes each data block, then hashes pairs of hashes up to a root hash. Changing any leaf changes the root. Used in Git, Bitcoin, and distributed file systems.',
  },
  {
    id: 'cs-tail-recursion',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What distinguishes tail recursion from regular recursion?',
    options: [
      'It is always faster',
      'The recursive call is the last operation before returning, enabling stack reuse',
      'It uses a different algorithm',
      'It works on trees but not lists',
    ],
    answer: 'The recursive call is the last operation before returning, enabling stack reuse',
    explanation: 'In tail recursion, the recursive call is the final action. A compiler/interpreter can optimize this to reuse the current stack frame, preventing stack overflow.',
  },
  {
    id: 'cs-cqrs',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'CQRS stands for:',
    options: [
      'Command Query Result Separation',
      'Command Query Responsibility Segregation',
      'Concurrent Queue Request System',
      'Cache Query Read Strategy',
    ],
    answer: 'Command Query Responsibility Segregation',
    explanation: 'CQRS separates read (query) and write (command) models. It allows independent scaling and optimization of reads and writes, often paired with event sourcing.',
  },
  {
    id: 'cs-moore-law',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'true-false',
    prompt: "Moore's Law predicts that transistor count doubles approximately every two years.",
    options: ['True', 'False'],
    answer: 'True',
    explanation: "Moore's Law, observed by Gordon Moore in 1965, states that the number of transistors on a chip doubles roughly every two years. It has largely held but is slowing as physical limits are reached.",
  },
  {
    id: 'cs-eventual-consistency',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does eventual consistency guarantee in distributed systems?',
    options: [
      'All nodes always have the same data',
      'If no new updates are made, all replicas will eventually converge to the same value',
      'Writes are always immediately visible',
      'The system is always available during partitions',
    ],
    answer: 'If no new updates are made, all replicas will eventually converge to the same value',
    explanation: 'Eventual consistency: given enough time with no new writes, all replicas converge to the same state. It trades immediate consistency for higher availability and partition tolerance.',
  },
  {
    id: 'cs-vector-clock',
    category: 'general-cs',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What do vector clocks track in distributed systems?',
    options: [
      'Physical wall clock time per node',
      'Causal ordering of events across multiple nodes',
      'Network latency between nodes',
      'Number of messages sent per node',
    ],
    answer: 'Causal ordering of events across multiple nodes',
    explanation: 'Vector clocks assign a vector of counters (one per node) to events. By comparing vectors, you can determine whether two events are causally related or concurrent.',
  },
];

export default generalcs;
