import type { Question } from '../types';

const gitcli: Question[] = [
  // --- easy (20) ---
  {
    id: 'git-init',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command initializes a new Git repository?',
    options: ['git start', 'git create', 'git init', 'git new'],
    answer: 'git init',
    explanation: 'git init creates a new .git directory in the current folder, initializing an empty repository.',
  },
  {
    id: 'git-status',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command shows the working tree status (modified, staged, untracked files)?',
    options: ['git log', 'git diff', 'git status', 'git show'],
    answer: 'git status',
    explanation: 'git status displays the state of the working directory and staging area — what is staged, modified, or untracked.',
  },
  {
    id: 'git-add-all',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command stages all changes in the current directory for commit?',
    options: ['git commit -a', 'git add .', 'git stage all', 'git push'],
    answer: 'git add .',
    explanation: 'git add . stages all new and modified files in the current directory (and subdirectories). It does not stage deletions in older Git versions; git add -A does.',
  },
  {
    id: 'git-commit-m',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which flag adds an inline commit message?',
    options: ['-msg', '-m', '--message-inline', '--commit'],
    answer: '-m',
    explanation: 'git commit -m "message" provides the commit message inline. Without -m, Git opens the configured text editor.',
  },
  {
    id: 'git-clone',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command downloads a remote repository to your local machine?',
    options: ['git pull', 'git fetch', 'git clone', 'git download'],
    answer: 'git clone',
    explanation: 'git clone copies a remote repository to a new local directory, setting up remote tracking branches.',
  },
  {
    id: 'git-branch-list',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command lists all local branches?',
    options: ['git show branches', 'git branch', 'git branches --list', 'git log --branches'],
    answer: 'git branch',
    explanation: 'git branch (no arguments) lists local branches with the current branch marked with *.',
  },
  {
    id: 'git-checkout-b',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command creates and switches to a new branch named "feature"?',
    options: ['git branch feature && git switch feature', 'git checkout -b feature', 'git new feature', 'git create feature'],
    answer: 'git checkout -b feature',
    explanation: 'git checkout -b branch creates a new branch and checks it out in one step. git switch -c branch is the modern equivalent.',
  },
  {
    id: 'git-push-origin',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'How do you push the current branch to the remote "origin"?',
    options: ['git upload origin', 'git send origin', 'git push origin HEAD', 'git push'],
    answer: 'git push origin HEAD',
    explanation: 'git push origin HEAD pushes the current branch to its matching remote branch. git push (with tracking set up) is the short form.',
  },
  {
    id: 'git-pull',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>git pull</code> do?',
    options: [
      'Fetches and merges remote changes into the current branch',
      'Uploads local commits to the remote',
      'Creates a new branch from the remote',
      'Reverts the last commit',
    ],
    answer: 'Fetches and merges remote changes into the current branch',
    explanation: 'git pull = git fetch + git merge (or rebase with --rebase). It downloads remote changes and integrates them into your current branch.',
  },
  {
    id: 'git-log',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command shows commit history?',
    options: ['git show', 'git history', 'git log', 'git commits'],
    answer: 'git log',
    explanation: 'git log displays the commit history of the current branch, showing commit hash, author, date, and message.',
  },
  {
    id: 'git-merge',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command merges branch "feature" into the current branch?',
    options: ['git combine feature', 'git merge feature', 'git join feature', 'git apply feature'],
    answer: 'git merge feature',
    explanation: 'git merge branch integrates the specified branch into the current branch by creating a merge commit (unless it fast-forwards).',
  },
  {
    id: 'git-staging-area',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the Git staging area (index)?',
    options: [
      'The remote repository',
      'A preparation area where you assemble changes before committing',
      'The last commit',
      'The working directory',
    ],
    answer: 'A preparation area where you assemble changes before committing',
    explanation: 'The staging area (index) holds a snapshot of changes to be included in the next commit. git add moves changes from the working directory into the staging area.',
  },
  {
    id: 'git-diff',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>git diff</code> show by default?',
    options: [
      'Staged changes vs the last commit',
      'Unstaged changes in the working directory',
      'All commits since origin',
      'Differences between two branches',
    ],
    answer: 'Unstaged changes in the working directory',
    explanation: 'git diff (no args) shows changes in the working directory not yet staged. git diff --staged shows staged changes vs the last commit.',
  },
  {
    id: 'git-remote-add',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which command adds a remote named "origin"?',
    options: ['git remote add origin <url>', 'git add remote origin <url>', 'git push -u origin', 'git remote set origin <url>'],
    answer: 'git remote add origin <url>',
    explanation: 'git remote add <name> <url> registers a remote repository under the given name. "origin" is the conventional name for the primary remote.',
  },
  {
    id: 'git-stash',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>git stash</code> do?',
    options: [
      'Deletes uncommitted changes',
      'Saves uncommitted changes to a temporary stack so the working directory is clean',
      'Creates a backup branch',
      'Commits with a "stash" message',
    ],
    answer: 'Saves uncommitted changes to a temporary stack so the working directory is clean',
    explanation: 'git stash shelves your changes so you can switch context. git stash pop restores them. Useful before pulling or switching branches.',
  },
  {
    id: 'git-gitignore',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the purpose of the <code>.gitignore</code> file?',
    options: [
      'Lists collaborators on the project',
      'Specifies files and directories Git should not track',
      'Stores Git configuration',
      'Lists branches to delete on merge',
    ],
    answer: 'Specifies files and directories Git should not track',
    explanation: '.gitignore contains patterns for files that Git should ignore — like node_modules, build artifacts, and environment files.',
  },
  {
    id: 'git-head',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In Git, what does HEAD refer to?',
    options: [
      'The first commit in the repo',
      'The current branch or commit that the working directory is based on',
      'The remote origin',
      'The most recent tag',
    ],
    answer: 'The current branch or commit that the working directory is based on',
    explanation: 'HEAD is a pointer to the currently checked-out commit or branch tip. It represents "where you are now" in the commit history.',
  },
  {
    id: 'git-ls',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In a Unix/Linux shell, which command lists files in the current directory?',
    options: ['dir', 'list', 'ls', 'show'],
    answer: 'ls',
    explanation: 'ls lists directory contents. Common flags: -l (long format), -a (show hidden files), -h (human-readable sizes).',
  },
  {
    id: 'git-cd',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which CLI command changes the current directory?',
    options: ['mv', 'go', 'cd', 'dir'],
    answer: 'cd',
    explanation: 'cd (change directory) moves the shell to a specified directory. cd .. goes up one level. cd ~ goes to the home directory.',
  },
  {
    id: 'git-rm',
    category: 'git-cli',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which CLI command removes a file?',
    options: ['del', 'erase', 'rm', 'remove'],
    answer: 'rm',
    explanation: 'rm removes files. rm -r removes directories recursively. rm -f forces removal without confirmation. Use with caution — there is no trash.',
  },

  // --- medium (20) ---
  {
    id: 'git-rebase',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>git rebase main</code> do when run on a feature branch?',
    options: [
      'Merges main into the feature branch creating a merge commit',
      'Replays the feature branch commits on top of the latest main, creating a linear history',
      'Resets the feature branch to main',
      'Deletes the feature branch and recreates it from main',
    ],
    answer: 'Replays the feature branch commits on top of the latest main, creating a linear history',
    explanation: 'Rebase rewrites commit history by replaying commits from the current branch on top of the specified base, resulting in a cleaner linear history without merge commits.',
  },
  {
    id: 'git-cherry-pick',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>git cherry-pick &lt;hash&gt;</code> do?',
    options: [
      'Reverts a specific commit',
      'Applies the changes of a specific commit to the current branch',
      'Moves a commit from one branch to another',
      'Creates a tag at a specific commit',
    ],
    answer: 'Applies the changes of a specific commit to the current branch',
    explanation: 'cherry-pick applies the changes from a specific commit onto the current branch, creating a new commit with the same changes but a different hash.',
  },
  {
    id: 'git-reset-soft',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>git reset --soft HEAD~1</code> do?',
    options: [
      'Deletes the last commit and all its changes',
      'Undoes the last commit but keeps changes staged',
      'Undoes the last commit and unstages the changes',
      'Rewrites the last commit message',
    ],
    answer: 'Undoes the last commit but keeps changes staged',
    explanation: '--soft moves HEAD back one commit but leaves changes in the staging area. --mixed unstages them (but keeps them in the working tree). --hard discards them entirely.',
  },
  {
    id: 'git-fetch-vs-pull',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the difference between <code>git fetch</code> and <code>git pull</code>?',
    options: [
      'fetch downloads changes and merges them; pull only downloads',
      'pull downloads and merges; fetch only downloads without merging',
      'They are identical',
      'fetch is for tags, pull is for branches',
    ],
    answer: 'pull downloads and merges; fetch only downloads without merging',
    explanation: 'git fetch downloads remote changes into remote-tracking branches but does not merge. git pull = git fetch + git merge (or rebase).',
  },
  {
    id: 'git-interactive-rebase',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does interactive rebase (<code>git rebase -i</code>) allow you to do?',
    options: [
      'Rebase without a base branch',
      'Squash, reorder, edit, or drop commits in your history',
      'Interactively resolve merge conflicts',
      'Rebase multiple branches at once',
    ],
    answer: 'Squash, reorder, edit, or drop commits in your history',
    explanation: 'Interactive rebase opens an editor where you can reorder, squash (combine), edit, or drop commits before replaying them — great for cleaning up before merging.',
  },
  {
    id: 'git-tag',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the difference between a lightweight tag and an annotated tag in Git?',
    options: [
      'Lightweight tags can be pushed; annotated cannot',
      'Annotated tags store metadata (tagger, date, message) and are signed; lightweight tags are just pointers',
      'Lightweight tags are stored remotely; annotated are local',
      'There is no functional difference',
    ],
    answer: 'Annotated tags store metadata (tagger, date, message) and are signed; lightweight tags are just pointers',
    explanation: 'Annotated tags (git tag -a) are full objects in Git with metadata and can be GPG signed. Lightweight tags are just named pointers to commits.',
  },
  {
    id: 'git-reflog',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>git reflog</code> show?',
    options: [
      'Remote branch history',
      'A log of all HEAD movements including resets, checkouts, and rebases',
      'The diff of the last 10 commits',
      'Files changed in each commit',
    ],
    answer: 'A log of all HEAD movements including resets, checkouts, and rebases',
    explanation: 'reflog records every time HEAD changed, even after resets and rebases. It is a safety net — you can use it to recover "lost" commits.',
  },
  {
    id: 'git-bisect',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is <code>git bisect</code> used for?',
    options: [
      'Splitting a repository into two',
      'Binary search through commits to find the one that introduced a bug',
      'Comparing two branches',
      'Bisecting a merge conflict',
    ],
    answer: 'Binary search through commits to find the one that introduced a bug',
    explanation: 'git bisect performs a binary search: you mark commits as good or bad and Git narrows down to the first bad commit. Efficient for finding regression introductions.',
  },
  {
    id: 'git-squash',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Squashing commits means:',
    options: [
      'Splitting one commit into multiple',
      'Combining multiple commits into one',
      'Reverting a sequence of commits',
      'Copying commits to another branch',
    ],
    answer: 'Combining multiple commits into one',
    explanation: 'Squashing collapses multiple commits into a single commit. Done with interactive rebase or "squash merge" pull requests to keep history clean.',
  },
  {
    id: 'git-hooks',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Where does Git store local hook scripts?',
    options: ['.git/hooks/', '.hooks/', 'hooks.git/', '.gitconfig/hooks/'],
    answer: '.git/hooks/',
    explanation: 'Git hook scripts live in .git/hooks/. Hooks like pre-commit, commit-msg, and pre-push are shell scripts that run at specific points in the Git workflow.',
  },
  {
    id: 'git-worktree',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>git worktree add</code> do?',
    options: [
      'Adds a file to the working directory',
      'Checks out a branch into a separate directory alongside the main working tree',
      'Creates a new repository',
      'Adds a remote branch as a local branch',
    ],
    answer: 'Checks out a branch into a separate directory alongside the main working tree',
    explanation: 'git worktree lets you check out multiple branches simultaneously in separate directories. Each worktree shares the same .git history.',
  },
  {
    id: 'git-submodule',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a Git submodule?',
    options: [
      'A partial clone of a large repository',
      'A nested Git repository inside another, tracked at a specific commit',
      'A branch that cannot be merged',
      'A read-only remote repository',
    ],
    answer: 'A nested Git repository inside another, tracked at a specific commit',
    explanation: 'A submodule embeds another Git repository at a specific commit pointer. git submodule update --init fetches and checks out the pinned commit.',
  },
  {
    id: 'git-grep',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which Unix command searches file contents for a pattern?',
    options: ['find', 'search', 'grep', 'locate'],
    answer: 'grep',
    explanation: 'grep searches files for lines matching a pattern. Common flags: -r (recursive), -n (line numbers), -i (case insensitive), -l (filenames only).',
  },
  {
    id: 'git-pipe',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'In the command <code>ls | grep ".txt"</code>, what does the pipe (<code>|</code>) do?',
    options: [
      'Runs both commands in parallel',
      'Sends the output of ls as input to grep',
      'Redirects output to a file',
      'Chains commands to run regardless of success',
    ],
    answer: 'Sends the output of ls as input to grep',
    explanation: 'The pipe | connects the stdout of one command to the stdin of the next. ls | grep ".txt" filters ls output to lines containing ".txt".',
  },
  {
    id: 'git-redirect',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>echo "hello" > file.txt</code> do?',
    options: [
      'Appends "hello" to file.txt',
      'Writes "hello" to file.txt, overwriting it',
      'Prints "hello" and pipes it to file.txt',
      'Creates a symlink',
    ],
    answer: 'Writes "hello" to file.txt, overwriting it',
    explanation: '> redirects stdout to a file, overwriting it. >> appends. So echo "hello" > file.txt overwrites file.txt with "hello".',
  },
  {
    id: 'git-chmod',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>chmod +x script.sh</code> do?',
    options: [
      'Compresses the script',
      'Executes the script',
      'Makes the script executable by adding the execute permission',
      'Removes write permission',
    ],
    answer: 'Makes the script executable by adding the execute permission',
    explanation: 'chmod +x adds execute permission to a file. Without this, you cannot run a shell script directly (./script.sh would give "Permission denied").',
  },
  {
    id: 'git-env-vars',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'How do you print the value of environment variable <code>HOME</code> in bash?',
    options: ['print $HOME', 'echo $HOME', 'env HOME', 'echo HOME'],
    answer: 'echo $HOME',
    explanation: 'Environment variables are accessed with $NAME. echo $HOME prints the value. Use printenv HOME for a dedicated command. env alone lists all environment variables.',
  },
  {
    id: 'git-find',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which command finds all <code>.log</code> files recursively under the current directory?',
    options: ['ls -r *.log', 'grep -r .log .', 'find . -name "*.log"', 'search . *.log'],
    answer: 'find . -name "*.log"',
    explanation: 'find . -name "*.log" recursively searches from . (current dir) for files matching the name pattern. find is very powerful with -type, -mtime, and -exec flags.',
  },
  {
    id: 'git-ssh-keygen',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>ssh-keygen -t ed25519</code> generate?',
    options: [
      'A TLS certificate',
      'An SSH key pair using the Ed25519 algorithm',
      'A GPG signing key',
      'A random password',
    ],
    answer: 'An SSH key pair using the Ed25519 algorithm',
    explanation: 'ssh-keygen creates public/private key pairs for SSH authentication. -t ed25519 uses the Ed25519 algorithm (modern, fast, secure). The public key is added to GitHub/server.',
  },
  {
    id: 'git-force-push',
    category: 'git-cli',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Why is <code>git push --force</code> dangerous on shared branches?',
    options: [
      'It deletes the remote branch',
      'It overwrites the remote history, discarding others\' commits',
      'It requires admin permission',
      'It cannot be undone',
    ],
    answer: 'It overwrites the remote history, discarding others\' commits',
    explanation: '--force overwrites the remote branch with your local version. If others have pushed commits, those are lost. Use --force-with-lease instead, which fails if the remote has new commits.',
  },

  // --- hard (15) ---
  {
    id: 'git-three-way-merge',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In a Git three-way merge, what are the three commits involved?',
    options: [
      'HEAD, MERGE_HEAD, and their common ancestor',
      'HEAD, origin/main, and origin/HEAD',
      'The first commit, last commit, and current HEAD',
      'Staged, unstaged, and committed versions',
    ],
    answer: 'HEAD, MERGE_HEAD, and their common ancestor',
    explanation: 'A three-way merge uses: the current branch tip (HEAD), the branch being merged (MERGE_HEAD), and their common ancestor. The ancestor helps resolve which changes are new.',
  },
  {
    id: 'git-rerere',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does Git\'s <code>rerere</code> feature do?',
    options: [
      'Automatically rebases on push',
      'Records conflict resolutions and reuses them when the same conflict appears again',
      'Reruns failed CI checks',
      'Renames remote branches',
    ],
    answer: 'Records conflict resolutions and reuses them when the same conflict appears again',
    explanation: 'rerere (Reuse Recorded Resolution) stores how you resolved conflicts. If the same conflict appears again (e.g., on repeated rebases), Git applies the stored resolution automatically.',
  },
  {
    id: 'git-objects',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Which types of objects does Git store internally?',
    options: ['files, folders, commits', 'blob, tree, commit, tag', 'snapshot, delta, patch', 'diff, hash, ref'],
    answer: 'blob, tree, commit, tag',
    explanation: 'Git stores four object types: blob (file content), tree (directory structure), commit (snapshot metadata and pointers), and tag (annotated tag object).',
  },
  {
    id: 'git-pack-file',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What are Git packfiles?',
    options: [
      'Compressed archives of the working directory',
      'Efficient binary files that store multiple objects using delta compression',
      'Bundle files for sending repos via email',
      'Compressed commit messages',
    ],
    answer: 'Efficient binary files that store multiple objects using delta compression',
    explanation: 'Packfiles (.pack) bundle many loose Git objects using delta compression (storing differences between similar blobs), dramatically reducing repository size.',
  },
  {
    id: 'git-sparse-checkout',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>git sparse-checkout</code> do?',
    options: [
      'Clones only the latest commit without history',
      'Checks out only a subset of a repository\'s files',
      'Skips binary files during clone',
      'Fetches only branches matching a pattern',
    ],
    answer: 'Checks out only a subset of a repository\'s files',
    explanation: 'Sparse checkout lets you check out only specific paths from a repository, useful for large monorepos where you only need certain directories.',
  },
  {
    id: 'git-awk',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>awk \'{print $2}\' file.txt</code> do?',
    options: [
      'Prints the second line of every paragraph',
      'Prints the second column (whitespace-delimited field) of each line',
      'Replaces line 2 with an empty line',
      'Counts lines with 2 words',
    ],
    answer: 'Prints the second column (whitespace-delimited field) of each line',
    explanation: 'awk splits each line into fields by whitespace. $2 is the second field. awk is a powerful text-processing tool for extracting and transforming structured text.',
  },
  {
    id: 'git-sed',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>sed -i \'s/foo/bar/g\' file.txt</code> do?',
    options: [
      'Prints lines containing "foo"',
      'Replaces all occurrences of "foo" with "bar" in file.txt in place',
      'Deletes lines containing "foo"',
      'Counts occurrences of "foo"',
    ],
    answer: 'Replaces all occurrences of "foo" with "bar" in file.txt in place',
    explanation: 'sed s/foo/bar/g substitutes "foo" with "bar" globally per line. -i edits the file in place. Without -i, sed prints to stdout without changing the file.',
  },
  {
    id: 'git-xargs',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>find . -name "*.tmp" | xargs rm</code> do?',
    options: [
      'Lists all .tmp files',
      'Moves .tmp files to a trash folder',
      'Finds all .tmp files and deletes them',
      'Compresses all .tmp files',
    ],
    answer: 'Finds all .tmp files and deletes them',
    explanation: 'xargs reads stdin and passes each line as arguments to a command. The pipe sends found .tmp paths to xargs rm, which deletes each one.',
  },
  {
    id: 'git-signal',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is the difference between <code>kill -9</code> and <code>kill -15</code>?',
    options: [
      'kill -9 is for system processes; kill -15 is for user processes',
      'kill -15 (SIGTERM) asks the process to terminate gracefully; kill -9 (SIGKILL) forces immediate termination',
      'kill -9 pauses the process; kill -15 resumes it',
      'kill -15 kills all child processes; kill -9 only kills the parent',
    ],
    answer: 'kill -15 (SIGTERM) asks the process to terminate gracefully; kill -9 (SIGKILL) forces immediate termination',
    explanation: 'SIGTERM (15) is a polite shutdown request — the process can clean up. SIGKILL (9) is immediate and cannot be caught or ignored by the process.',
  },
  {
    id: 'git-tee',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the <code>tee</code> command do?',
    options: [
      'Splits a file into two equal halves',
      'Reads stdin and writes it to both stdout and a file simultaneously',
      'Merges two files line by line',
      'Compresses stdin',
    ],
    answer: 'Reads stdin and writes it to both stdout and a file simultaneously',
    explanation: 'tee reads stdin and writes to both stdout and a file, so you can see the output on screen and save it: command | tee output.log',
  },
  {
    id: 'git-process-substitution',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does bash process substitution <code>diff <(sort a.txt) <(sort b.txt)</code> do?',
    options: [
      'Sorts both files and saves them',
      'Compares the sorted contents of two files by treating the output of sort as a file',
      'Pipes one file into the other',
      'Creates temp files named (sort a.txt)',
    ],
    answer: 'Compares the sorted contents of two files by treating the output of sort as a file',
    explanation: 'Process substitution <(...) runs a command and presents its output as if it were a file descriptor. This lets commands expecting file arguments receive command output.',
  },
  {
    id: 'git-here-string',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does a here-document (heredoc) do in bash?',
    options: [
      'Includes another script file inline',
      'Passes a multi-line string as stdin to a command',
      'Defines a multi-line variable',
      'Redirects stdout to a heredoc file',
    ],
    answer: 'Passes a multi-line string as stdin to a command',
    explanation: 'A heredoc (<<EOF ... EOF) passes a multi-line block of text as stdin to a command. Useful for feeding multi-line input without temporary files.',
  },
  {
    id: 'git-cron',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the cron expression <code>0 3 * * 1</code> mean?',
    options: [
      'Every 3 minutes on Mondays',
      'At 3:00 AM every Monday',
      'At 3:00 AM every first day of the month',
      'Every hour, 3 times on Monday',
    ],
    answer: 'At 3:00 AM every Monday',
    explanation: 'Cron fields: minute(0) hour(3) day-of-month(*) month(*) day-of-week(1=Monday). So: at 03:00, any day of month, any month, on Monday.',
  },
  {
    id: 'git-git-log-format',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>git log --oneline --graph --all</code> show?',
    options: [
      'Only the latest commit',
      'All commits as a text graph of all branches with one line per commit',
      'The diff for every commit',
      'Remote branches only',
    ],
    answer: 'All commits as a text graph of all branches with one line per commit',
    explanation: '--oneline compresses each commit to one line; --graph draws ASCII branch/merge lines; --all includes all branches and tags. Together they give a visual history overview.',
  },
  {
    id: 'git-detached-head',
    category: 'git-cli',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does it mean for Git to be in a "detached HEAD" state?',
    options: [
      'The last commit was deleted',
      'HEAD points directly to a commit hash, not a branch — new commits will not update any branch',
      'The remote and local HEAD are out of sync',
      'The repository is corrupted',
    ],
    answer: 'HEAD points directly to a commit hash, not a branch — new commits will not update any branch',
    explanation: 'Detached HEAD: HEAD points to a specific commit instead of a branch reference. Commits are still made but are not part of any branch and can be lost after switching away.',
  },
];

export default gitcli;
