import type { Question } from '../types';

const javascript: Question[] = [
  // --- easy (20) ---
  {
    id: 'js-typeof-null',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: '<code>typeof null === "object"</code> evaluates to <code>true</code>.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'This is a well-known JavaScript quirk. typeof null returns "object" even though null is not an object — it is a historical bug in the language.',
  },
  {
    id: 'js-let-block',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Variables declared with <code>let</code> are block-scoped.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'let and const are block-scoped, meaning they exist only within the nearest enclosing {} block. var is function-scoped.',
  },
  {
    id: 'js-triple-equals',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: '<code>0 == false</code> evaluates to <code>true</code> in JavaScript.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'The == operator performs type coercion. 0 is falsy and false coerces to 0, so they are loosely equal.',
  },
  {
    id: 'js-triple-equals-strict',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: '<code>0 === false</code> evaluates to <code>true</code> in JavaScript.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: '=== is strict equality — it does not coerce types. 0 is a number and false is a boolean, so they are not strictly equal.',
  },
  {
    id: 'js-array-typeof',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>typeof []</code> return in JavaScript?',
    options: ['array', 'object', 'undefined', 'null'],
    answer: 'object',
    explanation: 'Arrays in JavaScript are objects. typeof [] returns "object". Use Array.isArray() to check if something is an array.',
  },
  {
    id: 'js-undefined-declared',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'A variable declared with <code>var</code> but not assigned has the value <code>undefined</code>.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Declared but uninitialized var variables are automatically set to undefined by the JavaScript engine.',
  },
  {
    id: 'js-nan-type',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the type of <code>NaN</code> in JavaScript?',
    options: ['undefined', 'nan', 'number', 'string'],
    answer: 'number',
    explanation: 'Despite standing for "Not a Number", NaN has type "number". This is another JavaScript quirk.',
  },
  {
    id: 'js-string-concat',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>"5" + 3</code> evaluate to?',
    options: ['8', '53', '"8"', 'TypeError'],
    answer: '53',
    explanation: 'When the + operator is used with a string, it performs string concatenation. "5" + 3 becomes "53".',
  },
  {
    id: 'js-loose-null-undefined',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: '<code>null == undefined</code> evaluates to <code>true</code>.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'null and undefined are loosely equal to each other (and only to each other) in JavaScript.',
  },
  {
    id: 'js-const-reassign',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'You can reassign a new value to a variable declared with <code>const</code>.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'const prevents reassignment of the binding. Attempting to reassign a const throws a TypeError at runtime.',
  },
  {
    id: 'js-falsy-empty-string',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'An empty string <code>""</code> is falsy in JavaScript.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'The falsy values in JavaScript are: false, 0, -0, 0n, "", null, undefined, and NaN.',
  },
  {
    id: 'js-function-hoisting',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Function declarations are hoisted to the top of their scope.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Function declarations are fully hoisted — both the name and the body. This means you can call a function before its declaration in the source code.',
  },
  {
    id: 'js-array-length',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>[1, 2, 3].length</code> return?',
    options: ['2', '3', '4', 'undefined'],
    answer: '3',
    explanation: 'The length property of an array returns the number of elements. [1, 2, 3] has 3 elements.',
  },
  {
    id: 'js-arrow-this',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Arrow functions have their own <code>this</code> binding.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Arrow functions do not have their own this. They inherit this from the surrounding lexical scope.',
  },
  {
    id: 'js-push-returns',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>Array.prototype.push()</code> return?',
    options: ['The pushed element', 'The modified array', 'The new length of the array', 'undefined'],
    answer: 'The new length of the array',
    explanation: 'push() mutates the array in place and returns the new length of the array after the element is added.',
  },
  {
    id: 'js-strict-mode',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which string enables strict mode in a JavaScript file?',
    options: ['"use strict"', '"strict mode"', '"enable strict"', '// strict'],
    answer: '"use strict"',
    explanation: 'Placing the string literal "use strict" at the top of a file or function enables strict mode, which catches common mistakes.',
  },
  {
    id: 'js-object-keys',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which method returns an array of an object\'s own enumerable property names?',
    options: ['Object.values()', 'Object.entries()', 'Object.keys()', 'Object.props()'],
    answer: 'Object.keys()',
    explanation: 'Object.keys() returns an array of strings representing the object\'s own enumerable property names.',
  },
  {
    id: 'js-ternary',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>true ? "yes" : "no"</code> evaluate to?',
    options: ['"no"', '"yes"', 'true', 'undefined'],
    answer: '"yes"',
    explanation: 'The ternary operator returns the first expression when the condition is truthy, and the second when falsy.',
  },
  {
    id: 'js-typeof-function',
    category: 'javascript',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>typeof function(){}</code> return?',
    options: ['object', 'function', 'callable', 'undefined'],
    answer: 'function',
    explanation: 'typeof returns "function" for functions, which is a special case — functions are objects but typeof differentiates them.',
  },
  {
    id: 'js-nan-equal',
    category: 'javascript',
    difficulty: 'easy',
    format: 'true-false',
    prompt: '<code>NaN === NaN</code> evaluates to <code>true</code>.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'NaN is the only value in JavaScript that is not equal to itself. Use Number.isNaN() to check for NaN.',
  },

  // --- medium (20) ---
  {
    id: 'js-closure',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a closure in JavaScript?',
    options: [
      'A function that is immediately invoked',
      'A function that has access to its outer scope even after the outer function has returned',
      'A private method on a class',
      'A function with no return value',
    ],
    answer: 'A function that has access to its outer scope even after the outer function has returned',
    explanation: 'A closure is formed when an inner function retains access to variables in the outer function\'s scope, even after the outer function has finished executing.',
  },
  {
    id: 'js-promise-states',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which of the following is NOT a valid Promise state?',
    options: ['pending', 'fulfilled', 'rejected', 'resolved'],
    answer: 'resolved',
    explanation: 'The three Promise states are pending, fulfilled, and rejected. "resolved" is sometimes used informally but it is not an official state name.',
  },
  {
    id: 'js-event-loop',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which executes first: a resolved Promise callback or a setTimeout with 0ms delay?',
    options: [
      'setTimeout (0ms)',
      'The resolved Promise callback',
      'They execute at the same time',
      'It depends on the browser',
    ],
    answer: 'The resolved Promise callback',
    explanation: 'Promise callbacks go to the microtask queue, which is drained before the macrotask queue (where setTimeout callbacks go), regardless of delay.',
  },
  {
    id: 'js-proto-chain',
    category: 'javascript',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'Every JavaScript object has a prototype, except for the object created by <code>Object.create(null)</code>.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Object.create(null) creates an object with no prototype (its [[Prototype]] is null), making it a truly "bare" object with no inherited properties.',
  },
  {
    id: 'js-spread-shallow',
    category: 'javascript',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'The spread operator (<code>...</code>) performs a deep clone of an object.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Spread performs a shallow copy. Nested objects are copied by reference, not cloned. Changes to nested objects in the copy will affect the original.',
  },
  {
    id: 'js-async-await',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does an <code>async</code> function always return?',
    options: ['A value', 'A Promise', 'undefined', 'An Observable'],
    answer: 'A Promise',
    explanation: 'async functions always return a Promise. If the function returns a non-Promise value, it is automatically wrapped in Promise.resolve().',
  },
  {
    id: 'js-symbol',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is unique about Symbol values in JavaScript?',
    options: [
      'They can only be used as array keys',
      'Two Symbols with the same description are always equal',
      'Every Symbol() call produces a unique value',
      'They are a subtype of string',
    ],
    answer: 'Every Symbol() call produces a unique value',
    explanation: 'Symbol() creates a guaranteed unique identifier each time it is called. Even Symbol("name") !== Symbol("name").',
  },
  {
    id: 'js-map-vs-object',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is one advantage of using a <code>Map</code> over a plain object for key-value storage?',
    options: [
      'Maps serialize to JSON automatically',
      'Map keys can be any value including objects and functions',
      'Maps are always faster than objects',
      'Maps do not allow duplicate values',
    ],
    answer: 'Map keys can be any value including objects and functions',
    explanation: 'Plain object keys are always strings or Symbols. Map keys can be any type — functions, objects, primitives.',
  },
  {
    id: 'js-generator',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What keyword pauses a generator function and yields a value to the caller?',
    options: ['return', 'pause', 'yield', 'await'],
    answer: 'yield',
    explanation: 'yield pauses execution of a generator function and passes a value back to the caller. The generator resumes on the next .next() call.',
  },
  {
    id: 'js-var-hoisting',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is logged by: <code>console.log(x); var x = 5;</code>?',
    options: ['5', 'ReferenceError', 'undefined', 'null'],
    answer: 'undefined',
    explanation: 'var declarations are hoisted but not their assignments. The declaration is moved to the top, so x exists but is undefined before the assignment.',
  },
  {
    id: 'js-optional-chaining',
    category: 'javascript',
    difficulty: 'medium',
    format: 'true-false',
    prompt: '<code>obj?.foo?.bar</code> throws a TypeError if <code>obj</code> is <code>null</code>.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Optional chaining (?.) short-circuits and returns undefined if the left side is null or undefined, instead of throwing.',
  },
  {
    id: 'js-destructure-default',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>const { a = 10 } = {}</code> give <code>a</code>?',
    options: ['undefined', 'null', '10', 'TypeError'],
    answer: '10',
    explanation: 'Destructuring default values are used when the property is undefined. Since {} has no property a, a falls back to 10.',
  },
  {
    id: 'js-set-unique',
    category: 'javascript',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'A JavaScript <code>Set</code> can contain duplicate primitive values.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'A Set stores unique values only. Adding a duplicate value has no effect. It uses SameValueZero equality for comparison.',
  },
  {
    id: 'js-call-apply',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the difference between <code>.call()</code> and <code>.apply()</code>?',
    options: [
      'call is async, apply is sync',
      'call takes arguments one by one, apply takes an array of arguments',
      'apply takes arguments one by one, call takes an array',
      'There is no difference',
    ],
    answer: 'call takes arguments one by one, apply takes an array of arguments',
    explanation: 'Both invoke a function with a given this, but call(thisArg, arg1, arg2) takes individual args while apply(thisArg, [arg1, arg2]) takes an array.',
  },
  {
    id: 'js-proto-method',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'When you add a method to <code>Array.prototype</code>, which arrays see it?',
    options: [
      'Only arrays created after the method was added',
      'Only the specific array instance you modify',
      'All arrays, past and future',
      'Only arrays in the same module',
    ],
    answer: 'All arrays, past and future',
    explanation: 'Prototype modifications affect all instances that inherit from that prototype, including those already created, because prototype lookup is dynamic.',
  },
  {
    id: 'js-iife',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does IIFE stand for?',
    options: [
      'Immediately Invoked Function Expression',
      'Internal Isolated Function Execution',
      'Implicit Inline Function Evaluation',
      'Iterated Inline Function Expression',
    ],
    answer: 'Immediately Invoked Function Expression',
    explanation: 'An IIFE is a function that is defined and called immediately: (function() { ... })(). It creates a private scope.',
  },
  {
    id: 'js-event-delegation',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Event delegation relies on which DOM behavior?',
    options: ['Event capturing', 'Event bubbling', 'Event cloning', 'Shadow DOM'],
    answer: 'Event bubbling',
    explanation: 'Event delegation attaches a single listener to a parent element and relies on events bubbling up from child elements to the parent.',
  },
  {
    id: 'js-structuredclone',
    category: 'javascript',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which built-in function produces a deep clone of a value in modern JavaScript?',
    options: ['Object.assign()', 'JSON.parse(JSON.stringify())', 'structuredClone()', 'Object.freeze()'],
    answer: 'structuredClone()',
    explanation: 'structuredClone() is the native deep clone API introduced in 2022. JSON.parse(JSON.stringify()) works but loses functions and special values.',
  },
  {
    id: 'js-weakref',
    category: 'javascript',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'A <code>WeakMap</code> key must be an object (or a non-registered Symbol).',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'WeakMap keys must be objects (or non-registered Symbols in modern engines). Primitive keys like strings are not allowed.',
  },
  {
    id: 'js-for-of-string',
    category: 'javascript',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'A <code>for...of</code> loop can iterate over a string character by character.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Strings implement the iterable protocol, so for...of iterates over Unicode code points (not UTF-16 code units like a regular index loop).',
  },

  // --- hard (15) ---
  {
    id: 'js-temporal-dead-zone',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What happens when you access a <code>let</code> variable before its declaration in the same block?',
    options: [
      'Returns undefined',
      'Returns null',
      'Throws a ReferenceError due to the Temporal Dead Zone',
      'The variable is hoisted with undefined like var',
    ],
    answer: 'Throws a ReferenceError due to the Temporal Dead Zone',
    explanation: 'let and const are hoisted but not initialized — this gap is the Temporal Dead Zone (TDZ). Accessing them before the declaration throws a ReferenceError.',
  },
  {
    id: 'js-promise-all-vs-allsettled',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'How does <code>Promise.allSettled()</code> differ from <code>Promise.all()</code>?',
    options: [
      'allSettled rejects as soon as one Promise rejects',
      'allSettled waits for all Promises regardless of rejection, returning status for each',
      'all waits for all Promises and allSettled races them',
      'There is no difference in modern engines',
    ],
    answer: 'allSettled waits for all Promises regardless of rejection, returning status for each',
    explanation: 'Promise.all() short-circuits on the first rejection. Promise.allSettled() always waits for every Promise and returns an array of { status, value/reason } objects.',
  },
  {
    id: 'js-proxy-trap',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Which Proxy trap intercepts property read access?',
    options: ['set', 'get', 'read', 'intercept'],
    answer: 'get',
    explanation: 'The get trap fires when a property is read from the proxied object. set fires on assignment, has on the "in" operator, deleteProperty on delete.',
  },
  {
    id: 'js-reflect-own',
    category: 'javascript',
    difficulty: 'hard',
    format: 'true-false',
    prompt: '<code>Reflect</code> methods correspond one-to-one with Proxy trap names.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'The Reflect API is designed to mirror Proxy traps. Every Proxy trap has a corresponding Reflect method that performs the default behavior.',
  },
  {
    id: 'js-generator-return',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'When a generator\'s <code>.return(value)</code> is called, what happens to the generator?',
    options: [
      'It resumes execution from where it paused',
      'The generator finishes and subsequent .next() calls return { done: true, value: undefined }',
      'It throws a TypeError',
      'It resets the generator to the beginning',
    ],
    answer: 'The generator finishes and subsequent .next() calls return { done: true, value: undefined }',
    explanation: '.return(value) immediately terminates the generator. The generator\'s done state is set to true, and any further .next() calls return { value: undefined, done: true }.',
  },
  {
    id: 'js-module-live-binding',
    category: 'javascript',
    difficulty: 'hard',
    format: 'true-false',
    prompt: 'ES module imports are live bindings — if the exported value changes in the source module, the import reflects the change.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'ES modules use live bindings. If a module mutates an exported variable, all importers see the updated value. This differs from CommonJS, which copies values at require time.',
  },
  {
    id: 'js-finalizationregistry',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is <code>FinalizationRegistry</code> used for?',
    options: [
      'Preventing garbage collection of objects',
      'Running a callback when a registered object is garbage collected',
      'Detecting memory leaks',
      'Clearing circular references manually',
    ],
    answer: 'Running a callback when a registered object is garbage collected',
    explanation: 'FinalizationRegistry lets you register a cleanup callback that fires after an object is garbage collected. It is non-deterministic — the callback may not fire immediately.',
  },
  {
    id: 'js-tagged-template',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In a tagged template literal <code>fn`Hello ${name}`</code>, what is the first argument passed to <code>fn</code>?',
    options: [
      'The full interpolated string',
      'An array of string parts between expressions',
      'The first interpolated value',
      'A TemplateStringsArray object with both strings and values',
    ],
    answer: 'An array of string parts between expressions',
    explanation: 'Tagged templates receive (strings, ...values). strings is a frozen array of the literal parts (["Hello ", ""] in this case) and values are the interpolated expressions.',
  },
  {
    id: 'js-error-cause',
    category: 'javascript',
    difficulty: 'hard',
    format: 'true-false',
    prompt: 'You can pass a <code>cause</code> property when constructing an <code>Error</code> to chain errors.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'ES2022 added error cause: new Error("message", { cause: originalError }). This allows chaining errors with context, and the original is accessible as err.cause.',
  },
  {
    id: 'js-class-private',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'How are private class fields declared in modern JavaScript?',
    options: [
      'With the private keyword: private name',
      'With an underscore prefix: _name',
      'With a # prefix: #name',
      'By using a Symbol as the key',
    ],
    answer: 'With a # prefix: #name',
    explanation: 'True private class fields use the # prefix (class MyClass { #count = 0; }). They are inaccessible outside the class at the language level, unlike _ conventions.',
  },
  {
    id: 'js-in-operator-class',
    category: 'javascript',
    difficulty: 'hard',
    format: 'true-false',
    prompt: 'The <code>in</code> operator can be used to check whether a private class field exists on an object.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'ES2022 "ergonomic brand checks" allow: #field in obj to test whether obj has the private field. This is used to write type guards for private fields.',
  },
  {
    id: 'js-object-freeze-nested',
    category: 'javascript',
    difficulty: 'hard',
    format: 'true-false',
    prompt: '<code>Object.freeze()</code> deeply freezes nested objects.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Object.freeze() is shallow — it only prevents modifications to the top-level object. Nested objects remain mutable unless explicitly frozen as well.',
  },
  {
    id: 'js-tail-call',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is a tail call optimization (TCO)?',
    options: [
      'Inlining the last function call in a loop',
      'The engine reusing the current stack frame when the last action of a function is a call to another function',
      'Moving function calls to a microtask queue',
      'Memoizing recursive function results',
    ],
    answer: 'The engine reusing the current stack frame when the last action of a function is a call to another function',
    explanation: 'TCO allows the engine to avoid growing the call stack when a function\'s last action is calling another function. Specified in ES2015 but only implemented in strict mode by some engines.',
  },
  {
    id: 'js-atomics',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is the purpose of the <code>Atomics</code> object in JavaScript?',
    options: [
      'To perform mathematical operations on atomic numbers',
      'To provide atomic read/write operations on SharedArrayBuffer for multi-threaded safety',
      'To create immutable objects',
      'To optimize JIT compilation',
    ],
    answer: 'To provide atomic read/write operations on SharedArrayBuffer for multi-threaded safety',
    explanation: 'Atomics provides atomic operations (read, write, add, etc.) on SharedArrayBuffer, ensuring safe access when multiple workers share memory.',
  },
  {
    id: 'js-iterator-protocol',
    category: 'javascript',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'An object implements the iterator protocol when it has a <code>next()</code> method that returns an object with which two properties?',
    options: ['key and value', 'index and item', 'value and done', 'current and finished'],
    answer: 'value and done',
    explanation: 'The iterator protocol requires next() to return { value: any, done: boolean }. When done is true, iteration is complete. value is the current value or undefined when done.',
  },
];

export default javascript;
