import type { Question } from '../types';

const python: Question[] = [
  // --- easy (20) ---
  {
    id: 'py-list-mutable',
    category: 'python',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Python lists are mutable.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Lists are mutable — you can change their contents after creation. Tuples are the immutable counterpart.',
  },
  {
    id: 'py-tuple-immutable',
    category: 'python',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Python tuples are immutable.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Tuples cannot be modified after creation. Attempts to assign to a tuple index raise a TypeError.',
  },
  {
    id: 'py-none-type',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the type of <code>None</code> in Python?',
    options: ['bool', 'null', 'NoneType', 'undefined'],
    answer: 'NoneType',
    explanation: 'None is the sole instance of the NoneType class. type(None) returns <class \'NoneType\'>.',
  },
  {
    id: 'py-indentation',
    category: 'python',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Python uses indentation to define code blocks instead of curly braces.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Python enforces meaningful indentation. Indentation defines the scope of loops, conditionals, functions, and classes.',
  },
  {
    id: 'py-range-exclude',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'How many numbers does <code>range(1, 5)</code> produce?',
    options: ['5', '4', '3', '6'],
    answer: '4',
    explanation: 'range(1, 5) produces 1, 2, 3, 4. The stop value (5) is excluded. The count is stop - start = 4.',
  },
  {
    id: 'py-len-builtin',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which built-in function returns the number of items in a list?',
    options: ['count()', 'size()', 'len()', 'length()'],
    answer: 'len()',
    explanation: 'len() is the built-in function for getting the length of sequences (lists, strings, tuples, etc.).',
  },
  {
    id: 'py-string-immutable',
    category: 'python',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Strings in Python are immutable.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Python strings cannot be modified in place. Operations like replace() or upper() return a new string.',
  },
  {
    id: 'py-dict-key',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which of the following CANNOT be used as a dictionary key in Python?',
    options: ['str', 'int', 'tuple', 'list'],
    answer: 'list',
    explanation: 'Dictionary keys must be hashable. Lists are mutable and not hashable, so they cannot be used as keys.',
  },
  {
    id: 'py-bool-subclass',
    category: 'python',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'In Python, <code>bool</code> is a subclass of <code>int</code>.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'bool inherits from int. True == 1 and False == 0 in Python. isinstance(True, int) returns True.',
  },
  {
    id: 'py-print-function',
    category: 'python',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'In Python 3, <code>print</code> is a function (not a statement).',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'In Python 2, print was a statement. Python 3 made it a function: print("hello"). Parentheses are required.',
  },
  {
    id: 'py-list-concat',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>[1, 2] + [3, 4]</code> produce?',
    options: ['[4, 6]', '[1, 2, 3, 4]', 'TypeError', '[1, 2][3, 4]'],
    answer: '[1, 2, 3, 4]',
    explanation: 'The + operator on lists concatenates them into a new list.',
  },
  {
    id: 'py-in-operator',
    category: 'python',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'The <code>in</code> operator can check for membership in a list, tuple, or string.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'in tests membership. "a" in "cat" is True, 2 in [1,2,3] is True, 5 in (3,5,7) is True.',
  },
  {
    id: 'py-def-keyword',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which keyword is used to define a function in Python?',
    options: ['function', 'func', 'def', 'fn'],
    answer: 'def',
    explanation: 'Functions in Python are defined with the def keyword: def my_function():',
  },
  {
    id: 'py-list-comprehension',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>[x * 2 for x in range(3)]</code> produce?',
    options: ['[1, 2, 3]', '[0, 2, 4]', '[0, 1, 2]', '[2, 4, 6]'],
    answer: '[0, 2, 4]',
    explanation: 'range(3) produces 0, 1, 2. Each is doubled: [0*2, 1*2, 2*2] = [0, 2, 4].',
  },
  {
    id: 'py-class-keyword',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the first parameter of a Python instance method by convention?',
    options: ['this', 'cls', 'self', 'me'],
    answer: 'self',
    explanation: 'By convention (and requirement when calling on instances), the first parameter of an instance method is self, which refers to the instance.',
  },
  {
    id: 'py-negative-index',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>[1, 2, 3, 4][-1]</code> return?',
    options: ['1', '4', 'None', 'IndexError'],
    answer: '4',
    explanation: 'Negative indices count from the end. -1 is the last element, -2 is second-to-last, etc.',
  },
  {
    id: 'py-pass-statement',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the purpose of the <code>pass</code> statement in Python?',
    options: [
      'Skip to the next loop iteration',
      'Exit a function',
      'Act as a no-op placeholder where a statement is syntactically required',
      'Exit a conditional block',
    ],
    answer: 'Act as a no-op placeholder where a statement is syntactically required',
    explanation: 'pass does nothing. It is used as a placeholder in empty functions, classes, or blocks where Python syntax requires at least one statement.',
  },
  {
    id: 'py-enumerate',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does <code>enumerate(["a", "b", "c"])</code> yield?',
    options: [
      'The list unchanged',
      'Index-value pairs: (0, "a"), (1, "b"), (2, "c")',
      'A dictionary {"a":0, "b":1, "c":2}',
      'A reversed list',
    ],
    answer: 'Index-value pairs: (0, "a"), (1, "b"), (2, "c")',
    explanation: 'enumerate() yields (index, value) tuples. It is the idiomatic way to loop with an index in Python.',
  },
  {
    id: 'py-is-vs-eq',
    category: 'python',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'The <code>is</code> operator checks for value equality in Python.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'is checks identity (same object in memory), not equality. Use == for value comparison. Small integers and interned strings may mislead, but is tests object identity.',
  },
  {
    id: 'py-multiline-string',
    category: 'python',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which syntax creates a multi-line string in Python?',
    options: ['Single quotes with \\n', 'Triple quotes (""" or \'\'\')', 'Backticks (`)', 'The multiline() function'],
    answer: 'Triple quotes (""" or \'\'\')',
    explanation: 'Triple-quoted strings (""" ... """ or \'\'\' ... \'\'\') can span multiple lines and may include newlines literally.',
  },

  // --- medium (20) ---
  {
    id: 'py-generator-yield',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A Python function that contains a <code>yield</code> statement returns what kind of object?',
    options: ['A list', 'A coroutine', 'A generator', 'An iterator class'],
    answer: 'A generator',
    explanation: 'Any function with yield is a generator function. Calling it returns a generator object, which is a lazy iterator.',
  },
  {
    id: 'py-args-kwargs',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What type does <code>**kwargs</code> collect into inside a function?',
    options: ['A list of tuples', 'A set', 'A dictionary', 'A tuple'],
    answer: 'A dictionary',
    explanation: '**kwargs collects extra keyword arguments into a dictionary. *args collects positional arguments into a tuple.',
  },
  {
    id: 'py-mutable-default',
    category: 'python',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'Using a mutable object (like a list) as a default argument in Python is safe because it is re-created on each call.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Default argument values are evaluated once when the function is defined. Mutating a mutable default persists across calls. Use None as default and create inside the function.',
  },
  {
    id: 'py-context-manager',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A context manager must implement which two methods?',
    options: ['__open__ and __close__', '__start__ and __end__', '__enter__ and __exit__', '__init__ and __del__'],
    answer: '__enter__ and __exit__',
    explanation: 'Context managers implement __enter__ (runs at the start of the with block) and __exit__ (runs at the end, even on exceptions).',
  },
  {
    id: 'py-list-copy-slice',
    category: 'python',
    difficulty: 'medium',
    format: 'true-false',
    prompt: '<code>b = a[:]</code> creates a shallow copy of list <code>a</code>.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'The [:] slice syntax copies the top level of the list. Nested mutable objects are still shared references.',
  },
  {
    id: 'py-decorator',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does a decorator do in Python?',
    options: [
      'Adds type annotations to a function',
      'Wraps a function to extend or modify its behavior',
      'Compiles the function for performance',
      'Makes the function private',
    ],
    answer: 'Wraps a function to extend or modify its behavior',
    explanation: 'A decorator is a callable that takes a function and returns a new function. @my_decorator is syntactic sugar for func = my_decorator(func).',
  },
  {
    id: 'py-lambda',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which best describes a Python <code>lambda</code>?',
    options: [
      'A named function stored in a variable',
      'An anonymous function that can only have one expression',
      'A class method',
      'An async function shorthand',
    ],
    answer: 'An anonymous function that can only have one expression',
    explanation: 'lambdas are small anonymous functions: lambda x: x * 2. They are limited to a single expression and cannot contain statements.',
  },
  {
    id: 'py-dunder-str',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which dunder method is called by <code>str(obj)</code> and <code>print(obj)</code>?',
    options: ['__repr__', '__str__', '__format__', '__display__'],
    answer: '__str__',
    explanation: '__str__ is called when you convert an object to a string for display. __repr__ is the developer representation, used in the REPL and for debugging.',
  },
  {
    id: 'py-set-ops',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>{1, 2, 3} & {2, 3, 4}</code> return?',
    options: ['{1, 2, 3, 4}', '{2, 3}', '{1, 4}', 'TypeError'],
    answer: '{2, 3}',
    explanation: 'The & operator on sets returns the intersection — elements that appear in both sets.',
  },
  {
    id: 'py-walrus',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does the walrus operator <code>:=</code> do in Python 3.8+?',
    options: [
      'Defines a constant',
      'Assigns a value and returns it as part of an expression',
      'Compares values without coercion',
      'Creates a named tuple',
    ],
    answer: 'Assigns a value and returns it as part of an expression',
    explanation: ':= is the assignment expression operator. It assigns and returns a value within an expression, useful in while loops and comprehensions.',
  },
  {
    id: 'py-global-keyword',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does the <code>global</code> keyword do inside a function?',
    options: [
      'Creates a module-level variable',
      'Declares that a name refers to the module-level variable, not a local one',
      'Makes a variable accessible from other modules',
      'Prevents a variable from being garbage collected',
    ],
    answer: 'Declares that a name refers to the module-level variable, not a local one',
    explanation: 'global x inside a function makes all references to x in that function point to the module-level x, allowing modification of it.',
  },
  {
    id: 'py-zip',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>list(zip([1,2], ["a","b","c"]))</code> return?',
    options: [
      '[(1,"a"),(2,"b"),(None,"c")]',
      '[(1,"a"),(2,"b")]',
      '[(1,"a"),(2,"b"),(0,"c")]',
      'ValueError',
    ],
    answer: '[(1,"a"),(2,"b")]',
    explanation: 'zip() stops at the shortest iterable. The third element "c" has no pair, so it is dropped.',
  },
  {
    id: 'py-abstractmethod',
    category: 'python',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'You can instantiate a class that inherits from <code>ABC</code> and does not implement all abstract methods.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'If a class inherits from ABC (AbstractBaseClass) and has unimplemented abstract methods, Python raises a TypeError on instantiation.',
  },
  {
    id: 'py-property',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does the <code>@property</code> decorator allow you to do?',
    options: [
      'Make a method static',
      'Access a method like an attribute without calling it',
      'Prevent subclassing',
      'Cache a method\'s return value',
    ],
    answer: 'Access a method like an attribute without calling it',
    explanation: '@property lets you define a getter method that is accessed like obj.name instead of obj.name().',
  },
  {
    id: 'py-unpacking',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>a, *b, c = [1, 2, 3, 4, 5]</code> give <code>b</code>?',
    options: ['[2]', '[2, 3, 4]', '[2, 3, 4, 5]', '[1, 5]'],
    answer: '[2, 3, 4]',
    explanation: 'The starred variable *b collects all items not consumed by the other targets. a=1, c=5, and b gets the middle: [2, 3, 4].',
  },
  {
    id: 'py-dict-merge',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'In Python 3.9+, which operator merges two dictionaries?',
    options: ['&', '+', '|', '^'],
    answer: '|',
    explanation: 'The | operator merges dicts (d1 | d2), returning a new dict. |= updates in place. Earlier Python used {**d1, **d2}.',
  },
  {
    id: 'py-match-statement',
    category: 'python',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'Python 3.10 introduced structural pattern matching with the <code>match</code> statement.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'PEP 634 introduced match/case in Python 3.10. It supports pattern matching on values, sequences, mappings, and class instances.',
  },
  {
    id: 'py-class-method',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>@classmethod</code> pass as its first argument?',
    options: ['The instance', 'The module', 'The class itself', 'None'],
    answer: 'The class itself',
    explanation: '@classmethod methods receive the class (cls) as their first argument instead of the instance (self). They can be called on the class or an instance.',
  },
  {
    id: 'py-slots',
    category: 'python',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the primary benefit of using <code>__slots__</code> in a Python class?',
    options: [
      'Enables multiple inheritance',
      'Reduces memory usage by preventing a per-instance __dict__',
      'Makes attributes read-only',
      'Allows dynamic attribute creation',
    ],
    answer: 'Reduces memory usage by preventing a per-instance __dict__',
    explanation: '__slots__ replaces the per-instance __dict__ with a fixed structure, saving memory when you have many instances with known attributes.',
  },
  {
    id: 'py-type-hints',
    category: 'python',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'Python type hints are enforced at runtime by default.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Type hints are annotations only — they are not enforced at runtime. Static type checkers (like mypy) analyze them. Use runtime validation libraries if enforcement is needed.',
  },

  // --- hard (15) ---
  {
    id: 'py-gil',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the Global Interpreter Lock (GIL) prevent in CPython?',
    options: [
      'Multiple threads from running Python bytecode simultaneously',
      'Importing the same module twice',
      'Accessing global variables from multiple functions',
      'Running C extensions',
    ],
    answer: 'Multiple threads from running Python bytecode simultaneously',
    explanation: 'The GIL is a mutex in CPython that allows only one thread to execute Python bytecode at a time. This limits true parallelism in CPU-bound threaded code.',
  },
  {
    id: 'py-descriptor',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'A Python descriptor is an object that defines any of which methods?',
    options: ['__call__, __str__, __repr__', '__get__, __set__, __delete__', '__init__, __new__, __del__', '__enter__, __exit__, __get__'],
    answer: '__get__, __set__, __delete__',
    explanation: 'Descriptors define attribute access protocol via __get__, __set__, and/or __delete__. @property is implemented using the descriptor protocol.',
  },
  {
    id: 'py-metaclass',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In Python, what is a metaclass?',
    options: [
      'A class that cannot be instantiated',
      'A class whose instances are classes',
      'A base class for all data models',
      'A decorator that modifies class methods',
    ],
    answer: 'A class whose instances are classes',
    explanation: 'Metaclasses are classes of classes. type is the default metaclass. A custom metaclass allows you to customize class creation (e.g., add methods, validate attributes).',
  },
  {
    id: 'py-asyncio-gather',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>asyncio.gather()</code> do?',
    options: [
      'Runs coroutines sequentially',
      'Runs multiple coroutines concurrently and collects their results',
      'Cancels all running tasks',
      'Creates a new event loop',
    ],
    answer: 'Runs multiple coroutines concurrently and collects their results',
    explanation: 'asyncio.gather() schedules multiple coroutines to run concurrently and returns their results in order when all complete.',
  },
  {
    id: 'py-dataclass-frozen',
    category: 'python',
    difficulty: 'hard',
    format: 'true-false',
    prompt: 'A <code>@dataclass(frozen=True)</code> generates <code>__hash__</code> based on the fields.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'frozen=True makes the dataclass immutable (raises FrozenInstanceError on mutation) and auto-generates __hash__ based on the fields, making it usable as a dict key or in a set.',
  },
  {
    id: 'py-protocol',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is the purpose of <code>typing.Protocol</code> in Python?',
    options: [
      'To define network communication protocols',
      'To enable structural subtyping (duck typing) with static type checking',
      'To enforce method overriding',
      'To create singleton classes',
    ],
    answer: 'To enable structural subtyping (duck typing) with static type checking',
    explanation: 'Protocol allows you to define structural interfaces. A class satisfies a Protocol if it has the right methods/attributes, without needing to explicitly inherit from it.',
  },
  {
    id: 'py-cython-vs-cpython',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is the key difference between CPython and Cython?',
    options: [
      'CPython is compiled, Cython is interpreted',
      'CPython is the reference Python interpreter, Cython is a compiler that transpiles Python to C',
      'Cython is the official Python, CPython is a third-party implementation',
      'CPython only runs on Linux, Cython is cross-platform',
    ],
    answer: 'CPython is the reference Python interpreter, Cython is a compiler that transpiles Python to C',
    explanation: 'CPython is the standard Python interpreter written in C. Cython is a separate tool that compiles Python (with optional type annotations) to C extensions for performance.',
  },
  {
    id: 'py-generator-send',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does calling <code>generator.send(value)</code> do differently from <code>next(generator)</code>?',
    options: [
      'It sends the value to the next yield expression and resumes the generator',
      'It queues the value to be processed on the next iteration',
      'It sets the generator\'s return value',
      'It has the same effect as next()',
    ],
    answer: 'It sends the value to the next yield expression and resumes the generator',
    explanation: 'send(value) resumes the generator and makes the yield expression evaluate to value. next() is equivalent to send(None).',
  },
  {
    id: 'py-weakref',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is a weak reference in Python?',
    options: [
      'A reference that can only be held by one variable',
      'A reference that does not prevent the object from being garbage collected',
      'A reference stored in a WeakDict',
      'A reference to a deprecated object',
    ],
    answer: 'A reference that does not prevent the object from being garbage collected',
    explanation: 'A weak reference (from the weakref module) refers to an object without increasing its reference count, so the GC can collect it when no strong references remain.',
  },
  {
    id: 'py-slots-inheritance',
    category: 'python',
    difficulty: 'hard',
    format: 'true-false',
    prompt: 'If a parent class does not define <code>__slots__</code>, a subclass that defines <code>__slots__</code> will still have a <code>__dict__</code>.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'If any class in the MRO lacks __slots__, instances will have a __dict__. The __slots__ optimization only works when all classes in the inheritance chain define it.',
  },
  {
    id: 'py-lru-cache',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What restriction do arguments have when using <code>@functools.lru_cache</code>?',
    options: [
      'Arguments must be integers',
      'Arguments must be hashable',
      'There can be at most 2 arguments',
      'Arguments must be positional only',
    ],
    answer: 'Arguments must be hashable',
    explanation: 'lru_cache uses arguments as dictionary keys. All arguments must be hashable. Passing mutable objects (like lists or dicts) raises a TypeError.',
  },
  {
    id: 'py-type-var',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is <code>TypeVar</code> used for in Python typing?',
    options: [
      'To declare a variable with a fixed type',
      'To define a type alias',
      'To create a generic placeholder type for use in generic functions and classes',
      'To annotate variadic function arguments',
    ],
    answer: 'To create a generic placeholder type for use in generic functions and classes',
    explanation: 'TypeVar creates a generic type variable: T = TypeVar("T"). Used in function signatures to express that input and output share the same type.',
  },
  {
    id: 'py-import-hook',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Where does Python look for custom import hooks?',
    options: ['sys.path only', 'sys.meta_path and sys.path_hooks', 'importlib only', 'PYTHONPATH environment variable'],
    answer: 'sys.meta_path and sys.path_hooks',
    explanation: 'sys.meta_path holds finder objects tried first; sys.path_hooks holds path-entry finder factories. Custom hooks can intercept imports before the default file system is searched.',
  },
  {
    id: 'py-c3-linearization',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Python uses which algorithm to determine Method Resolution Order (MRO) in multiple inheritance?',
    options: ['Depth-first search', 'C3 linearization', 'Breadth-first search', 'Topological sort'],
    answer: 'C3 linearization',
    explanation: 'Python 3 uses C3 linearization (also called C3 superclass linearization) to compute a consistent and predictable MRO. It ensures left-to-right and bottom-up ordering.',
  },
  {
    id: 'py-new-vs-init',
    category: 'python',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is the difference between <code>__new__</code> and <code>__init__</code> in Python?',
    options: [
      '__new__ initializes state, __init__ allocates the object',
      '__new__ creates and returns the instance, __init__ initializes it',
      '__init__ is called only for subclasses, __new__ is always called',
      'There is no practical difference',
    ],
    answer: '__new__ creates and returns the instance, __init__ initializes it',
    explanation: '__new__ is the constructor — it creates and returns a new instance. __init__ receives the already-created instance and sets its initial state. __new__ is rarely overridden except in metaclasses and singletons.',
  },
];

export default python;
