import type { Question } from '../types';

const web: Question[] = [
  // --- easy (20) ---
  {
    id: 'web-html-stands-for',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does HTML stand for?',
    options: ['HyperText Markup Language', 'HighText Machine Language', 'HyperTransfer Markup Language', 'HyperText Modern Language'],
    answer: 'HyperText Markup Language',
    explanation: 'HTML stands for HyperText Markup Language — the standard language for structuring content on the web.',
  },
  {
    id: 'web-css-stands-for',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does CSS stand for?',
    options: ['Creative Style Sheets', 'Cascading Style Sheets', 'Computer Style Syntax', 'Colorful Style System'],
    answer: 'Cascading Style Sheets',
    explanation: 'CSS stands for Cascading Style Sheets — the language used to style and lay out HTML documents.',
  },
  {
    id: 'web-http-200',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does HTTP status code 200 mean?',
    options: ['Not Found', 'Redirect', 'OK (success)', 'Server Error'],
    answer: 'OK (success)',
    explanation: '200 OK is the standard response for a successful HTTP request.',
  },
  {
    id: 'web-http-404',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What does HTTP status code 404 indicate?',
    options: ['Server error', 'Redirect', 'Unauthorized', 'Resource not found'],
    answer: 'Resource not found',
    explanation: '404 Not Found means the server could not find the requested resource.',
  },
  {
    id: 'web-semantic-html',
    category: 'web',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Using semantic HTML elements like <code>&lt;header&gt;</code> and <code>&lt;nav&gt;</code> improves accessibility and SEO.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'Semantic elements convey meaning to browsers and assistive technologies. They improve accessibility for screen readers and give search engines structural context.',
  },
  {
    id: 'web-css-box-model',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'The CSS box model consists of (from inside out): content, then what three layers?',
    options: [
      'Padding, border, margin',
      'Border, padding, margin',
      'Margin, padding, border',
      'Padding, margin, border',
    ],
    answer: 'Padding, border, margin',
    explanation: 'The CSS box model layers are: content, padding (inside border), border, margin (outside border).',
  },
  {
    id: 'web-alt-attribute',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the purpose of the <code>alt</code> attribute on an <code>&lt;img&gt;</code> element?',
    options: [
      'Sets the image size',
      'Provides alternative text for accessibility and when the image fails to load',
      'Links the image to a URL',
      'Sets the image format',
    ],
    answer: 'Provides alternative text for accessibility and when the image fails to load',
    explanation: 'The alt attribute provides descriptive text for screen readers and is shown when the image cannot load.',
  },
  {
    id: 'web-flexbox-axis',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In CSS Flexbox, <code>justify-content</code> aligns items along which axis?',
    options: ['Cross axis', 'Main axis', 'Vertical axis', 'Block axis'],
    answer: 'Main axis',
    explanation: 'justify-content aligns flex items along the main axis (row direction by default). align-items works on the cross axis.',
  },
  {
    id: 'web-https-secure',
    category: 'web',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'HTTPS encrypts data in transit between the client and server.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'HTTPS uses TLS/SSL to encrypt the HTTP connection, protecting data from eavesdropping and tampering.',
  },
  {
    id: 'web-doctype',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the purpose of <code>&lt;!DOCTYPE html&gt;</code> at the top of an HTML file?',
    options: [
      'Loads an external stylesheet',
      'Declares the document type to tell the browser to use standard HTML5 rendering',
      'Defines the HTML version',
      'Initializes JavaScript',
    ],
    answer: 'Declares the document type to tell the browser to use standard HTML5 rendering',
    explanation: '<!DOCTYPE html> tells the browser this is an HTML5 document, preventing quirks mode rendering.',
  },
  {
    id: 'web-id-vs-class',
    category: 'web',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'An HTML <code>id</code> attribute value must be unique within a page.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'IDs must be unique per page. Classes can be shared across multiple elements. Duplicate IDs cause invalid HTML and unreliable JavaScript behavior.',
  },
  {
    id: 'web-display-inline',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which CSS <code>display</code> value makes an element not start on a new line and only take up as much width as needed?',
    options: ['block', 'inline', 'flex', 'grid'],
    answer: 'inline',
    explanation: 'inline elements flow with text, do not start on new lines, and only occupy as much width as their content (like <span> or <a>).',
  },
  {
    id: 'web-get-vs-post',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In HTTP, which method is typically used to retrieve data without side effects?',
    options: ['POST', 'PUT', 'GET', 'DELETE'],
    answer: 'GET',
    explanation: 'GET is used to retrieve data. It should have no side effects (idempotent and safe). POST is used to send data that causes a change on the server.',
  },
  {
    id: 'web-meta-viewport',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'What is the purpose of <code>&lt;meta name="viewport" content="width=device-width"&gt;</code>?',
    options: [
      'Sets the page background color',
      'Makes the page responsive by matching the viewport width to the device width',
      'Prevents the page from being indexed',
      'Defines the character encoding',
    ],
    answer: 'Makes the page responsive by matching the viewport width to the device width',
    explanation: 'The viewport meta tag controls how the browser scales the page on mobile. Without it, mobile browsers zoom out and pages look like desktop on a small screen.',
  },
  {
    id: 'web-css-specificity-order',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In CSS specificity, which selector type has the highest weight?',
    options: ['Element selectors (div)', 'Class selectors (.class)', 'ID selectors (#id)', 'Attribute selectors'],
    answer: 'ID selectors (#id)',
    explanation: 'Specificity weight: inline styles > ID selectors > class/attribute selectors > element selectors. IDs beat classes.',
  },
  {
    id: 'web-form-action',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'In an HTML <code>&lt;form&gt;</code>, the <code>action</code> attribute specifies:',
    options: ['The HTTP method', 'Where to send the form data when submitted', 'The form\'s CSS class', 'The form\'s ID'],
    answer: 'Where to send the form data when submitted',
    explanation: 'The action attribute is the URL to which the form data is sent on submit. If omitted, data is sent to the current page URL.',
  },
  {
    id: 'web-local-storage',
    category: 'web',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'Data stored in <code>localStorage</code> persists after the browser is closed.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'localStorage data persists with no expiration until explicitly cleared. sessionStorage data is cleared when the browser session ends.',
  },
  {
    id: 'web-head-vs-body',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: 'Which HTML element contains metadata like the title and stylesheet links?',
    options: ['<body>', '<head>', '<html>', '<meta>'],
    answer: '<head>',
    explanation: '<head> contains metadata not directly rendered on the page: <title>, <meta>, <link>, <style>, and <script> tags.',
  },
  {
    id: 'web-css-em-rem',
    category: 'web',
    difficulty: 'easy',
    format: 'multiple-choice',
    prompt: '<code>rem</code> in CSS is relative to:',
    options: ['The parent element\'s font size', 'The root element\'s font size', 'The viewport width', 'The screen resolution'],
    answer: 'The root element\'s font size',
    explanation: 'rem (root em) is relative to the root <html> element\'s font size. em is relative to the current element\'s font size.',
  },
  {
    id: 'web-css-position-sticky',
    category: 'web',
    difficulty: 'easy',
    format: 'true-false',
    prompt: 'A CSS element with <code>position: sticky</code> behaves like <code>relative</code> until it crosses a scroll threshold, then sticks.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'position: sticky toggles between relative and fixed based on the scroll position. It sticks to the nearest scrollable ancestor when it reaches the offset.',
  },

  // --- medium (20) ---
  {
    id: 'web-cors',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does CORS stand for and what problem does it solve?',
    options: [
      'Cross-Origin Resource Sharing — allows browsers to make requests to different domains securely',
      'Cross-Origin Request Security — prevents XSS attacks',
      'Content Origin Routing System — caches cross-domain assets',
      'Client Origin Request Sharing — shares cookies across domains',
    ],
    answer: 'Cross-Origin Resource Sharing — allows browsers to make requests to different domains securely',
    explanation: 'CORS is a browser mechanism allowing servers to declare which origins can access their resources. The browser blocks cross-origin requests without proper CORS headers.',
  },
  {
    id: 'web-csp',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A Content Security Policy (CSP) header primarily helps prevent which attack?',
    options: ['SQL injection', 'CSRF', 'Cross-Site Scripting (XSS)', 'Man-in-the-middle'],
    answer: 'Cross-Site Scripting (XSS)',
    explanation: 'CSP allows servers to whitelist sources of executable scripts. This mitigates XSS by preventing the browser from running scripts from unauthorized sources.',
  },
  {
    id: 'web-http2-benefits',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which is a key feature of HTTP/2 over HTTP/1.1?',
    options: [
      'HTTP/2 requires HTTPS',
      'Multiplexing: multiple requests over a single TCP connection',
      'HTTP/2 is text-based',
      'HTTP/2 eliminated cookies',
    ],
    answer: 'Multiplexing: multiple requests over a single TCP connection',
    explanation: 'HTTP/2 multiplexes multiple concurrent requests over one connection, eliminating head-of-line blocking and reducing connection overhead vs. HTTP/1.1.',
  },
  {
    id: 'web-csrf',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'A CSRF token is used to prevent what type of attack?',
    options: [
      'Cross-Site Scripting',
      'SQL injection',
      'Cross-Site Request Forgery',
      'Clickjacking',
    ],
    answer: 'Cross-Site Request Forgery',
    explanation: 'CSRF tokens ensure that form submissions originate from the genuine site. CSRF attacks trick users into submitting authenticated requests from another site.',
  },
  {
    id: 'web-service-worker',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does a Service Worker enable in web applications?',
    options: [
      'Server-side rendering',
      'Offline functionality and background sync by intercepting network requests',
      'Direct database access from the browser',
      'Multi-threaded DOM manipulation',
    ],
    answer: 'Offline functionality and background sync by intercepting network requests',
    explanation: 'Service Workers are background scripts that intercept requests, cache resources, and enable Progressive Web App features like offline support.',
  },
  {
    id: 'web-grid-vs-flex',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the main difference between CSS Grid and Flexbox?',
    options: [
      'Grid is for styling, Flexbox is for layout',
      'Grid is two-dimensional (rows and columns), Flexbox is one-dimensional',
      'Flexbox is newer than Grid',
      'Grid only works in Chrome',
    ],
    answer: 'Grid is two-dimensional (rows and columns), Flexbox is one-dimensional',
    explanation: 'CSS Grid handles two-dimensional layout (both rows and columns). Flexbox is designed for one-dimensional layout — either a row or a column.',
  },
  {
    id: 'web-preload',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>&lt;link rel="preload"&gt;</code> do?',
    options: [
      'Lazy-loads the resource',
      'Tells the browser to fetch a resource early before it is needed',
      'Defers script execution',
      'Prefetches next-page resources',
    ],
    answer: 'Tells the browser to fetch a resource early before it is needed',
    explanation: 'preload tells the browser to download a critical resource (font, script, CSS) early in the page lifecycle, before it would otherwise be discovered.',
  },
  {
    id: 'web-rest-idempotent',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which HTTP methods are idempotent (calling them multiple times has the same effect as calling once)?',
    options: ['GET, POST, PUT', 'GET, PUT, DELETE', 'POST, DELETE, PATCH', 'GET and POST only'],
    answer: 'GET, PUT, DELETE',
    explanation: 'GET, PUT, and DELETE are idempotent. Calling GET/PUT/DELETE multiple times produces the same server state as one call. POST is not idempotent — repeated calls may create multiple resources.',
  },
  {
    id: 'web-shadow-dom',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does the Shadow DOM provide?',
    options: [
      'Server-side rendering',
      'Encapsulated DOM and CSS scoped to a component',
      'Direct GPU access for animations',
      'Lazy loading of HTML fragments',
    ],
    answer: 'Encapsulated DOM and CSS scoped to a component',
    explanation: 'Shadow DOM encapsulates a component\'s markup and styles so they do not leak in or out. It is the basis for Web Components.',
  },
  {
    id: 'web-http-cache-control',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What does <code>Cache-Control: max-age=3600</code> tell the browser?',
    options: [
      'The resource must be revalidated every hour',
      'The resource can be cached for 3600 seconds (1 hour)',
      'The resource expires in 3600 days',
      'The resource is not cacheable',
    ],
    answer: 'The resource can be cached for 3600 seconds (1 hour)',
    explanation: 'max-age=3600 means the browser can use its cached copy for up to 3600 seconds. After that, it makes a new request.',
  },
  {
    id: 'web-css-custom-props',
    category: 'web',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'CSS custom properties (variables) declared in <code>:root</code> are accessible throughout the entire document.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: ':root is the highest-level selector. CSS variables declared there are global to the document. Variables follow cascade and inheritance rules.',
  },
  {
    id: 'web-sse-vs-ws',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the key difference between Server-Sent Events (SSE) and WebSockets?',
    options: [
      'SSE is bidirectional, WebSockets are server-to-client only',
      'SSE is server-to-client only, WebSockets are bidirectional',
      'WebSockets are only for binary data',
      'SSE requires a separate port',
    ],
    answer: 'SSE is server-to-client only, WebSockets are bidirectional',
    explanation: 'SSE is a one-way channel from server to browser over HTTP. WebSockets provide full-duplex communication, allowing both sides to send messages freely.',
  },
  {
    id: 'web-critical-rendering',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Why does placing <code>&lt;script&gt;</code> tags at the bottom of <code>&lt;body&gt;</code> improve page load performance?',
    options: [
      'Scripts execute faster at the bottom',
      'It prevents the browser from blocking HTML parsing to load and execute the script',
      'CSS is loaded before scripts',
      'It enables async execution automatically',
    ],
    answer: 'It prevents the browser from blocking HTML parsing to load and execute the script',
    explanation: 'By default, <script> blocks HTML parsing. Placing scripts at the bottom lets the browser parse and render the HTML first, then run scripts.',
  },
  {
    id: 'web-http3',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'HTTP/3 uses which transport protocol instead of TCP?',
    options: ['UDP', 'QUIC (which runs over UDP)', 'WebSockets', 'TLS 1.3'],
    answer: 'QUIC (which runs over UDP)',
    explanation: 'HTTP/3 uses QUIC, a transport protocol built on UDP, to eliminate TCP\'s head-of-line blocking and reduce connection setup time via 0-RTT handshakes.',
  },
  {
    id: 'web-media-query',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'In a mobile-first approach, media queries use <code>min-width</code>. What does this mean?',
    options: [
      'Styles apply when the viewport is narrower than the breakpoint',
      'Base styles apply to the smallest screens; breakpoints add styles for wider screens',
      'All styles are applied at once',
      'CSS is only applied on desktop',
    ],
    answer: 'Base styles apply to the smallest screens; breakpoints add styles for wider screens',
    explanation: 'Mobile-first: write default (base) styles for mobile, then use min-width media queries to add/override styles for progressively wider viewports.',
  },
  {
    id: 'web-json-types',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'Which data type is NOT valid in JSON?',
    options: ['string', 'boolean', 'undefined', 'null'],
    answer: 'undefined',
    explanation: 'JSON supports: string, number, boolean, null, array, and object. undefined is a JavaScript concept and is not part of the JSON spec.',
  },
  {
    id: 'web-rest-vs-graphql',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is a key advantage of GraphQL over REST?',
    options: [
      'GraphQL is always faster',
      'Clients can request exactly the fields they need, preventing over- and under-fetching',
      'GraphQL uses less bandwidth by default',
      'GraphQL does not require a server',
    ],
    answer: 'Clients can request exactly the fields they need, preventing over- and under-fetching',
    explanation: 'GraphQL lets clients specify exactly what data they need in a single query. REST endpoints return fixed shapes, often including unneeded data or requiring multiple requests.',
  },
  {
    id: 'web-wasm',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is WebAssembly (Wasm)?',
    options: [
      'A new JavaScript framework',
      'A low-level binary format that runs in browsers at near-native speed',
      'A server-side scripting language',
      'A CSS preprocessor',
    ],
    answer: 'A low-level binary format that runs in browsers at near-native speed',
    explanation: 'WebAssembly is a binary instruction format designed for near-native performance in browsers. Code from C, C++, Rust, etc. can be compiled to Wasm and run alongside JavaScript.',
  },
  {
    id: 'web-cookie-httponly',
    category: 'web',
    difficulty: 'medium',
    format: 'true-false',
    prompt: 'A cookie with the <code>HttpOnly</code> flag cannot be accessed by JavaScript.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'HttpOnly cookies are not accessible via document.cookie in JavaScript, protecting them from XSS attacks. They are only sent with HTTP requests.',
  },
  {
    id: 'web-css-will-change',
    category: 'web',
    difficulty: 'medium',
    format: 'multiple-choice',
    prompt: 'What is the purpose of the CSS property <code>will-change</code>?',
    options: [
      'Prevents elements from being animated',
      'Hints to the browser that an element will change, enabling GPU layer promotion and optimization',
      'Forces a synchronous layout recalculation',
      'Disables transitions on hover',
    ],
    answer: 'Hints to the browser that an element will change, enabling GPU layer promotion and optimization',
    explanation: 'will-change: transform (or other properties) tells the browser to promote the element to a GPU compositing layer ahead of time, reducing jank during animations.',
  },

  // --- hard (15) ---
  {
    id: 'web-hsts',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does HSTS (HTTP Strict Transport Security) do?',
    options: [
      'Encrypts cookies',
      'Forces the browser to only connect via HTTPS for a specified duration',
      'Prevents mixed content',
      'Sets a Content Security Policy',
    ],
    answer: 'Forces the browser to only connect via HTTPS for a specified duration',
    explanation: 'HSTS tells browsers to always use HTTPS for a domain for a specified max-age. Even if a user types http://, the browser upgrades to HTTPS automatically.',
  },
  {
    id: 'web-speculative-parsing',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Modern browsers use speculative (preload) scanning while parsing HTML. What does this mean?',
    options: [
      'The browser renders the page before scripts run',
      'A secondary thread scans HTML for resources to fetch while the main parser is blocked',
      'The browser caches all resources before parsing begins',
      'JavaScript is executed speculatively before the DOM is ready',
    ],
    answer: 'A secondary thread scans HTML for resources to fetch while the main parser is blocked',
    explanation: 'While the main HTML parser is blocked (e.g., waiting for a script), the preload scanner looks ahead in the HTML to discover and fetch other resources in parallel.',
  },
  {
    id: 'web-content-negotiation',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What HTTP header does a client use for content negotiation to specify acceptable response formats?',
    options: ['Content-Type', 'Accept', 'Authorization', 'Vary'],
    answer: 'Accept',
    explanation: 'The Accept header lists MIME types the client can handle (e.g., Accept: application/json). The server uses it to choose the response format.',
  },
  {
    id: 'web-304',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does HTTP status 304 Not Modified mean?',
    options: [
      'The resource was permanently moved',
      'The cached response is still valid; no body is sent',
      'The server rejected the request',
      'The resource was partially sent',
    ],
    answer: 'The cached response is still valid; no body is sent',
    explanation: '304 tells the browser its cached version is still current. The server sends no body, saving bandwidth. Used with ETag and Last-Modified conditional requests.',
  },
  {
    id: 'web-etag',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What is an ETag HTTP header used for?',
    options: [
      'Tagging resources for CDN routing',
      'Identifying a specific version of a resource for cache validation',
      'Encrypting the response body',
      'Setting resource expiration',
    ],
    answer: 'Identifying a specific version of a resource for cache validation',
    explanation: 'An ETag is a hash or token representing a resource version. The browser sends it in If-None-Match; if it matches, the server responds with 304 Not Modified.',
  },
  {
    id: 'web-render-blocking',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Why is a CSS file in <code>&lt;head&gt;</code> render-blocking by default?',
    options: [
      'Because CSS files are large',
      'The browser must finish building the CSSOM before it can render to avoid flash of unstyled content',
      'CSS blocks JavaScript parsing',
      'CSS is always loaded synchronously regardless of placement',
    ],
    answer: 'The browser must finish building the CSSOM before it can render to avoid flash of unstyled content',
    explanation: 'Rendering requires both the DOM and CSSOM. The browser blocks rendering until CSS is downloaded and parsed so it can compute final styles before painting.',
  },
  {
    id: 'web-cookie-samesite',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the <code>SameSite=Strict</code> cookie attribute do?',
    options: [
      'Sends the cookie over HTTPS only',
      'Prevents the cookie from being sent on any cross-site requests',
      'Restricts the cookie to first-party subdomains',
      'Limits the cookie lifetime to the session',
    ],
    answer: 'Prevents the cookie from being sent on any cross-site requests',
    explanation: 'SameSite=Strict means the cookie is only sent when navigating within the same site. Any cross-site navigation (clicking a link from another domain) will not include the cookie, preventing CSRF.',
  },
  {
    id: 'web-link-preconnect',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does <code>&lt;link rel="preconnect"&gt;</code> do?',
    options: [
      'Downloads the resource immediately',
      'Establishes a TCP connection, TLS handshake, and DNS lookup to an origin ahead of time',
      'Prefetches HTML pages for navigation',
      'Defers the resource until after first paint',
    ],
    answer: 'Establishes a TCP connection, TLS handshake, and DNS lookup to an origin ahead of time',
    explanation: 'preconnect warms up the connection to a domain early. DNS lookup, TCP handshake, and TLS negotiation are done before the resource is requested, saving latency.',
  },
  {
    id: 'web-web-vitals-lcp',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does LCP (Largest Contentful Paint) measure?',
    options: [
      'Time to First Byte',
      'When the largest image or text block in the viewport becomes visible',
      'Total script execution time',
      'Time from input to visual response',
    ],
    answer: 'When the largest image or text block in the viewport becomes visible',
    explanation: 'LCP measures when the largest content element (image, video poster, or text block) becomes visible in the viewport. A good LCP is under 2.5s.',
  },
  {
    id: 'web-repaint-reflow',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'In browser rendering, what is the difference between repaint and reflow?',
    options: [
      'Repaint changes layout; reflow changes colors',
      'Reflow recalculates layout geometry; repaint updates pixels without changing layout',
      'They are the same operation',
      'Reflow is caused by CSS, repaint by JavaScript',
    ],
    answer: 'Reflow recalculates layout geometry; repaint updates pixels without changing layout',
    explanation: 'Reflow (layout) recalculates positions and sizes — expensive, triggers repaint. Repaint redraws pixels when visuals change without affecting geometry (e.g., color change). Reflow is more costly.',
  },
  {
    id: 'web-origin-policy',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'Two URLs have the same origin if they share the same:',
    options: [
      'Domain only',
      'Protocol, domain, and port',
      'Protocol and domain only',
      'Domain and path',
    ],
    answer: 'Protocol, domain, and port',
    explanation: 'The Same-Origin Policy defines origin as: protocol (http/https) + hostname + port. All three must match. https://a.com:443 and http://a.com:80 are different origins.',
  },
  {
    id: 'web-css-layer',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the CSS <code>@layer</code> rule do?',
    options: [
      'Creates a new stacking context',
      'Defines named cascade layers to control specificity ordering',
      'Groups media queries',
      'Prevents style inheritance',
    ],
    answer: 'Defines named cascade layers to control specificity ordering',
    explanation: '@layer lets you define named cascade layers. Styles in later layers override earlier layers regardless of specificity, giving more control over CSS ordering.',
  },
  {
    id: 'web-fetchpriority',
    category: 'web',
    difficulty: 'hard',
    format: 'true-false',
    prompt: 'The <code>fetchpriority</code> attribute on <code>&lt;img&gt;</code> can hint to the browser to load an image with high priority.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'fetchpriority="high" hints to the browser\'s resource scheduler to prioritize that image (e.g., the LCP image). fetchpriority="low" deprioritizes non-critical images.',
  },
  {
    id: 'web-permissions-policy',
    category: 'web',
    difficulty: 'hard',
    format: 'multiple-choice',
    prompt: 'What does the <code>Permissions-Policy</code> HTTP header control?',
    options: [
      'Which origins can embed the page',
      'Which browser features (camera, microphone, geolocation) are allowed on the page',
      'Which scripts can run on the page',
      'Which cookies the page can read',
    ],
    answer: 'Which browser features (camera, microphone, geolocation) are allowed on the page',
    explanation: 'Permissions-Policy (formerly Feature-Policy) controls access to browser APIs like camera, microphone, and geolocation for the page and iframes it contains.',
  },
  {
    id: 'web-credentialed-cors',
    category: 'web',
    difficulty: 'hard',
    format: 'true-false',
    prompt: 'A CORS credentialed request (with cookies) requires the server to set <code>Access-Control-Allow-Origin</code> to a specific origin, not <code>*</code>.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'When credentials (cookies, auth headers) are included, the browser rejects responses with Access-Control-Allow-Origin: *. The server must echo the specific requesting origin.',
  },
];

export default web;
