// ---- Variable pools ----

import type { VarType } from "./gameLogic"

export type Difficulty = 'easy' | 'medium' | 'hard'

interface VarEntry {
  declaration: string
  type: VarType
  difficulty: Difficulty
}

export const JS_POOL: VarEntry[] = [
  // string
  { declaration: '"Alice"', type: 'string', difficulty: 'easy' },
  { declaration: '"hello"', type: 'string', difficulty: 'easy' },
  { declaration: '"user@example.com"', type: 'string', difficulty: 'easy' },
  { declaration: '"Berlin"', type: 'string', difficulty: 'easy' },
  { declaration: '"Loading..."', type: 'string', difficulty: 'easy' },
  { declaration: '"Submit"', type: 'string', difficulty: 'easy' },
  { declaration: '"Tokyo"', type: 'string', difficulty: 'easy' },
  { declaration: '"password"', type: 'string', difficulty: 'easy' },
  { declaration: '"#FF0000"', type: 'string', difficulty: 'easy' },
  { declaration: '"2024-01-01"', type: 'string', difficulty: 'easy' },
  { declaration: '"42"', type: 'string', difficulty: 'medium' },
  { declaration: '""', type: 'string', difficulty: 'medium' },
  { declaration: '"0"', type: 'string', difficulty: 'medium' },
  { declaration: '"3.14"', type: 'string', difficulty: 'medium' },
  { declaration: '"false"', type: 'string', difficulty: 'medium' },
  { declaration: '" "', type: 'string', difficulty: 'medium' },
  { declaration: '"1"', type: 'string', difficulty: 'medium' },
  { declaration: '"hello".slice(0, 3)', type: 'string', difficulty: 'medium' },
  { declaration: '"hello " + "world"', type: 'string', difficulty: 'medium' },
  { declaration: '"true"', type: 'string', difficulty: 'hard' },
  { declaration: '"null"', type: 'string', difficulty: 'hard' },
  { declaration: '"undefined"', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof 42', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof []', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof null', type: 'string', difficulty: 'hard' },
  { declaration: '"NaN"', type: 'string', difficulty: 'hard' },
  { declaration: '"Infinity"', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof {}', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof undefined', type: 'string', difficulty: 'hard' },
  { declaration: 'String(42)', type: 'string', difficulty: 'hard' },
  { declaration: '(42).toString()', type: 'string', difficulty: 'hard' },
  { declaration: 'JSON.stringify(1)', type: 'string', difficulty: 'hard' },
  { declaration: '[1].join()', type: 'string', difficulty: 'hard' },
  { declaration: 'String(true)', type: 'string', difficulty: 'hard' },
  // number
  { declaration: '42', type: 'number', difficulty: 'easy' },
  { declaration: '3.14', type: 'number', difficulty: 'easy' },
  { declaration: '-1', type: 'number', difficulty: 'easy' },
  { declaration: '100', type: 'number', difficulty: 'easy' },
  { declaration: '9.99', type: 'number', difficulty: 'easy' },
  { declaration: '5000', type: 'number', difficulty: 'easy' },
  { declaration: '0', type: 'number', difficulty: 'easy' },
  { declaration: '7', type: 'number', difficulty: 'easy' },
  { declaration: '255', type: 'number', difficulty: 'easy' },
  { declaration: '-42', type: 'number', difficulty: 'easy' },
  { declaration: '0.01', type: 'number', difficulty: 'easy' },
  { declaration: '99', type: 'number', difficulty: 'easy' },
  { declaration: 'NaN', type: 'number', difficulty: 'medium' },
  { declaration: '1e3', type: 'number', difficulty: 'medium' },
  { declaration: '-0', type: 'number', difficulty: 'medium' },
  { declaration: '0.1 + 0.2', type: 'number', difficulty: 'medium' },
  { declaration: 'Math.PI', type: 'number', difficulty: 'medium' },
  { declaration: '2 ** 10', type: 'number', difficulty: 'medium' },
  { declaration: '0xff', type: 'number', difficulty: 'medium' },
  { declaration: 'Math.floor(3.9)', type: 'number', difficulty: 'medium' },
  { declaration: '"5".length', type: 'number', difficulty: 'medium' },
  { declaration: 'Infinity', type: 'number', difficulty: 'hard' },
  { declaration: '+"42"', type: 'number', difficulty: 'hard' },
  { declaration: 'parseInt("5px")', type: 'number', difficulty: 'hard' },
  { declaration: 'Number(true)', type: 'number', difficulty: 'hard' },
  { declaration: '+false', type: 'number', difficulty: 'hard' },
  { declaration: 'Number("")', type: 'number', difficulty: 'hard' },
  { declaration: 'parseInt("0x1F")', type: 'number', difficulty: 'hard' },
  { declaration: 'Number(false)', type: 'number', difficulty: 'hard' },
  { declaration: '~~3.9', type: 'number', difficulty: 'hard' },
  { declaration: '1 / 0', type: 'number', difficulty: 'hard' },
  // boolean
  { declaration: 'true', type: 'boolean', difficulty: 'easy' },
  { declaration: 'false', type: 'boolean', difficulty: 'easy' },
  { declaration: '10 > 3', type: 'boolean', difficulty: 'easy' },
  { declaration: '1 < 2', type: 'boolean', difficulty: 'easy' },
  { declaration: '0 < 1', type: 'boolean', difficulty: 'easy' },
  { declaration: '"a" === "a"', type: 'boolean', difficulty: 'easy' },
  { declaration: '!true', type: 'boolean', difficulty: 'easy' },
  { declaration: '3 >= 3', type: 'boolean', difficulty: 'easy' },
  { declaration: '5 !== 6', type: 'boolean', difficulty: 'easy' },
  { declaration: '1 === 1', type: 'boolean', difficulty: 'medium' },
  { declaration: '"a" !== "b"', type: 'boolean', difficulty: 'medium' },
  { declaration: '!false', type: 'boolean', difficulty: 'medium' },
  { declaration: '0 === 0', type: 'boolean', difficulty: 'medium' },
  { declaration: '[].length === 0', type: 'boolean', difficulty: 'medium' },
  { declaration: '"hello".includes("ell")', type: 'boolean', difficulty: 'medium' },
  { declaration: '!0', type: 'boolean', difficulty: 'hard' },
  { declaration: '!![]', type: 'boolean', difficulty: 'hard' },
  { declaration: 'Boolean(1)', type: 'boolean', difficulty: 'hard' },
  { declaration: '0 == false', type: 'boolean', difficulty: 'hard' },
  { declaration: '"" == false', type: 'boolean', difficulty: 'hard' },
  { declaration: 'Boolean("a")', type: 'boolean', difficulty: 'hard' },
  { declaration: 'null == undefined', type: 'boolean', difficulty: 'hard' },
  { declaration: '[] == false', type: 'boolean', difficulty: 'hard' },
  { declaration: 'typeof null === "object"', type: 'boolean', difficulty: 'hard' },
  { declaration: 'NaN === NaN', type: 'boolean', difficulty: 'hard' },
  { declaration: '!!"false"', type: 'boolean', difficulty: 'hard' },
  // null
  { declaration: 'null', type: 'null', difficulty: 'easy' },
  { declaration: 'null', type: 'null', difficulty: 'easy' },
  { declaration: 'null', type: 'null', difficulty: 'easy' },
  { declaration: 'null', type: 'null', difficulty: 'medium' },
  { declaration: 'null || null', type: 'null', difficulty: 'medium' },
  { declaration: 'JSON.parse("null")', type: 'null', difficulty: 'hard' },
  { declaration: '[1, 2].find(x => x > 9)', type: 'null', difficulty: 'hard' },
  { declaration: '"abc".match(/\\d/)', type: 'null', difficulty: 'hard' },
  { declaration: 'null ?? null', type: 'null', difficulty: 'hard' },
  { declaration: '/\\d+/.exec("abc")', type: 'null', difficulty: 'hard' },
  // undefined
  { declaration: 'undefined', type: 'undefined', difficulty: 'easy' },
  { declaration: 'undefined', type: 'undefined', difficulty: 'easy' },
  { declaration: 'void 0', type: 'undefined', difficulty: 'medium' },
  { declaration: 'void "hello"', type: 'undefined', difficulty: 'medium' },
  { declaration: 'void null', type: 'undefined', difficulty: 'medium' },
  { declaration: '[1, 2][5]', type: 'undefined', difficulty: 'medium' },
  { declaration: '[][0]', type: 'undefined', difficulty: 'hard' },
  { declaration: '({}).missing', type: 'undefined', difficulty: 'hard' },
  { declaration: '[undefined][0]', type: 'undefined', difficulty: 'hard' },
  { declaration: 'undefined ?? undefined', type: 'undefined', difficulty: 'hard' },
  // object
  { declaration: '{ id: 1 }', type: 'object', difficulty: 'easy' },
  { declaration: '{ name: "Alice" }', type: 'object', difficulty: 'easy' },
  { declaration: '{ x: 0, y: 0 }', type: 'object', difficulty: 'easy' },
  { declaration: '{ active: true }', type: 'object', difficulty: 'easy' },
  { declaration: '{ score: 0 }', type: 'object', difficulty: 'easy' },
  { declaration: '{ width: 100, height: 200 }', type: 'object', difficulty: 'easy' },
  { declaration: '{ items: [] }', type: 'object', difficulty: 'easy' },
  { declaration: '{ color: "red" }', type: 'object', difficulty: 'easy' },
  { declaration: '{}', type: 'object', difficulty: 'medium' },
  { declaration: 'new Date()', type: 'object', difficulty: 'medium' },
  { declaration: 'new Map()', type: 'object', difficulty: 'medium' },
  { declaration: '{ 0: "a", 1: "b" }', type: 'object', difficulty: 'medium' },
  { declaration: 'new Error("oops")', type: 'object', difficulty: 'medium' },
  { declaration: 'Object.assign({}, { a: 1 })', type: 'object', difficulty: 'medium' },
  { declaration: '{ ...{ a: 1 } }', type: 'object', difficulty: 'medium' },
  { declaration: 'JSON.parse("{}")', type: 'object', difficulty: 'hard' },
  { declaration: 'Object.create(null)', type: 'object', difficulty: 'hard' },
  { declaration: 'new RegExp("ab")', type: 'object', difficulty: 'hard' },
  { declaration: 'new WeakMap()', type: 'object', difficulty: 'hard' },
  { declaration: 'Object.fromEntries([["a", 1]])', type: 'object', difficulty: 'hard' },
  { declaration: 'new Set([1, 2])', type: 'object', difficulty: 'hard' },
  // array
  { declaration: '[1, 2, 3]', type: 'array', difficulty: 'easy' },
  { declaration: '["a", "b"]', type: 'array', difficulty: 'easy' },
  { declaration: '[true, false]', type: 'array', difficulty: 'easy' },
  { declaration: '[1, 2]', type: 'array', difficulty: 'easy' },
  { declaration: '[0]', type: 'array', difficulty: 'easy' },
  { declaration: '["hello"]', type: 'array', difficulty: 'easy' },
  { declaration: '[null, null]', type: 'array', difficulty: 'easy' },
  { declaration: '[false, true]', type: 'array', difficulty: 'easy' },
  { declaration: '[]', type: 'array', difficulty: 'medium' },
  { declaration: 'new Array(3)', type: 'array', difficulty: 'medium' },
  { declaration: '[1, [2, 3]]', type: 'array', difficulty: 'medium' },
  { declaration: 'Array(3).fill(0)', type: 'array', difficulty: 'medium' },
  { declaration: 'Object.values({ a: 1 })', type: 'array', difficulty: 'medium' },
  { declaration: '[1, ...[], 2]', type: 'array', difficulty: 'medium' },
  { declaration: '[...[1, 2, 3]]', type: 'array', difficulty: 'medium' },
  { declaration: 'Array.from("abc")', type: 'array', difficulty: 'hard' },
  { declaration: 'Object.keys({ a: 1 })', type: 'array', difficulty: 'hard' },
  { declaration: '"a,b,c".split(",")', type: 'array', difficulty: 'hard' },
  { declaration: '[...new Set([1, 1, 2])]', type: 'array', difficulty: 'hard' },
  { declaration: 'Array.from({ length: 3 })', type: 'array', difficulty: 'hard' },
  { declaration: 'Object.entries({ a: 1 })', type: 'array', difficulty: 'hard' },
  { declaration: '"hello".split("")', type: 'array', difficulty: 'hard' },
  // function
  { declaration: '() => "hi"', type: 'function', difficulty: 'easy' },
  { declaration: '(x) => x * 2', type: 'function', difficulty: 'easy' },
  { declaration: 'function() { return 1 }', type: 'function', difficulty: 'easy' },
  { declaration: '() => {}', type: 'function', difficulty: 'easy' },
  { declaration: '(x, y) => x + y', type: 'function', difficulty: 'easy' },
  { declaration: 'n => n * n', type: 'function', difficulty: 'easy' },
  { declaration: '() => null', type: 'function', difficulty: 'easy' },
  { declaration: 'function add(a, b) {}', type: 'function', difficulty: 'easy' },
  { declaration: 'Math.random', type: 'function', difficulty: 'medium' },
  { declaration: 'parseInt', type: 'function', difficulty: 'medium' },
  { declaration: 'Array.isArray', type: 'function', difficulty: 'medium' },
  { declaration: 'JSON.stringify', type: 'function', difficulty: 'medium' },
  { declaration: 'async () => {}', type: 'function', difficulty: 'medium' },
  { declaration: 'Object.keys', type: 'function', difficulty: 'medium' },
  { declaration: 'class Foo {}', type: 'function', difficulty: 'hard' },
  { declaration: '(function() {})', type: 'function', difficulty: 'hard' },
  { declaration: 'function* gen() {}', type: 'function', difficulty: 'hard' },
  { declaration: 'new Function("return 1")', type: 'function', difficulty: 'hard' },
  // extra tricky
  { declaration: 'typeof NaN', type: 'string', difficulty: 'hard' },
  { declaration: 'typeof typeof 42', type: 'string', difficulty: 'hard' },
  { declaration: '[] + []', type: 'string', difficulty: 'hard' },
  { declaration: 'null + ""', type: 'string', difficulty: 'hard' },
  { declaration: 'String(null)', type: 'string', difficulty: 'hard' },
  { declaration: '+[]', type: 'number', difficulty: 'hard' },
  { declaration: '+null', type: 'number', difficulty: 'hard' },
  { declaration: 'true + true', type: 'number', difficulty: 'hard' },
  { declaration: 'null + 1', type: 'number', difficulty: 'hard' },
  { declaration: '[] - 1', type: 'number', difficulty: 'hard' },
  { declaration: 'Boolean([])', type: 'boolean', difficulty: 'hard' },
  { declaration: 'Boolean({})', type: 'boolean', difficulty: 'hard' },
  { declaration: '!!null', type: 'boolean', difficulty: 'hard' },
  { declaration: '!undefined', type: 'boolean', difficulty: 'hard' },
  { declaration: 'Boolean(null)', type: 'boolean', difficulty: 'hard' },
  { declaration: '(0, null)', type: 'null', difficulty: 'hard' },
  { declaration: '"a".match(/b/)', type: 'null', difficulty: 'hard' },
  { declaration: '[null][0]', type: 'null', difficulty: 'hard' },
  { declaration: 'void false', type: 'undefined', difficulty: 'hard' },
  { declaration: 'void {}', type: 'undefined', difficulty: 'hard' },
  { declaration: '[1, 2].find(() => false)', type: 'undefined', difficulty: 'hard' },
  { declaration: 'new Boolean(false)', type: 'object', difficulty: 'hard' },
  { declaration: 'new Number(42)', type: 'object', difficulty: 'hard' },
  { declaration: '[1, 2, 3].map(x => x * 2)', type: 'array', difficulty: 'hard' },
  { declaration: '"hello".match(/l/g)', type: 'array', difficulty: 'hard' },
  { declaration: 'Boolean', type: 'function', difficulty: 'hard' },
  { declaration: 'Number', type: 'function', difficulty: 'hard' },
]

export const PY_POOL: VarEntry[] = [
  // str
  { declaration: '"Alice"', type: 'str', difficulty: 'easy' },
  { declaration: '"hello"', type: 'str', difficulty: 'easy' },
  { declaration: '"user@example.com"', type: 'str', difficulty: 'easy' },
  { declaration: '"Berlin"', type: 'str', difficulty: 'easy' },
  { declaration: '"Loading..."', type: 'str', difficulty: 'easy' },
  { declaration: '"Tokyo"', type: 'str', difficulty: 'easy' },
  { declaration: '"password"', type: 'str', difficulty: 'easy' },
  { declaration: '"#FF0000"', type: 'str', difficulty: 'easy' },
  { declaration: 'f"hello"', type: 'str', difficulty: 'easy' },
  { declaration: '"42"', type: 'str', difficulty: 'medium' },
  { declaration: '""', type: 'str', difficulty: 'medium' },
  { declaration: '"0"', type: 'str', difficulty: 'medium' },
  { declaration: '"3.14"', type: 'str', difficulty: 'medium' },
  { declaration: '" "', type: 'str', difficulty: 'medium' },
  { declaration: '"1"', type: 'str', difficulty: 'medium' },
  { declaration: '"hello"[0]', type: 'str', difficulty: 'medium' },
  { declaration: '"abc".upper()', type: 'str', difficulty: 'medium' },
  { declaration: '"True"', type: 'str', difficulty: 'hard' },
  { declaration: '"None"', type: 'str', difficulty: 'hard' },
  { declaration: '"false"', type: 'str', difficulty: 'hard' },
  { declaration: 'str(42)', type: 'str', difficulty: 'hard' },
  { declaration: '"NaN"', type: 'str', difficulty: 'hard' },
  { declaration: 'str(True)', type: 'str', difficulty: 'hard' },
  { declaration: 'str(None)', type: 'str', difficulty: 'hard' },
  { declaration: 'repr(42)', type: 'str', difficulty: 'hard' },
  { declaration: 'chr(65)', type: 'str', difficulty: 'hard' },
  // int
  { declaration: '42', type: 'int', difficulty: 'easy' },
  { declaration: '0', type: 'int', difficulty: 'easy' },
  { declaration: '-1', type: 'int', difficulty: 'easy' },
  { declaration: '100', type: 'int', difficulty: 'easy' },
  { declaration: '5000', type: 'int', difficulty: 'easy' },
  { declaration: '7', type: 'int', difficulty: 'easy' },
  { declaration: '255', type: 'int', difficulty: 'easy' },
  { declaration: '-42', type: 'int', difficulty: 'easy' },
  { declaration: '1000', type: 'int', difficulty: 'easy' },
  { declaration: 'len("hello")', type: 'int', difficulty: 'medium' },
  { declaration: 'abs(-5)', type: 'int', difficulty: 'medium' },
  { declaration: 'int(3.9)', type: 'int', difficulty: 'medium' },
  { declaration: 'round(3.7)', type: 'int', difficulty: 'medium' },
  { declaration: 'ord("A")', type: 'int', difficulty: 'medium' },
  { declaration: 'max(1, 2)', type: 'int', difficulty: 'medium' },
  { declaration: 'min(3, 4)', type: 'int', difficulty: 'medium' },
  { declaration: 'sum([1, 2])', type: 'int', difficulty: 'medium' },
  { declaration: '2 ** 10', type: 'int', difficulty: 'medium' },
  { declaration: 'int(3.0)', type: 'int', difficulty: 'medium' },
  { declaration: 'int(True)', type: 'int', difficulty: 'hard' },
  { declaration: 'True + True', type: 'int', difficulty: 'hard' },
  { declaration: 'False + 1', type: 'int', difficulty: 'hard' },
  { declaration: 'int(False)', type: 'int', difficulty: 'hard' },
  // float
  { declaration: '3.14', type: 'float', difficulty: 'easy' },
  { declaration: '0.5', type: 'float', difficulty: 'easy' },
  { declaration: '-2.5', type: 'float', difficulty: 'easy' },
  { declaration: '9.99', type: 'float', difficulty: 'easy' },
  { declaration: '1.5', type: 'float', difficulty: 'easy' },
  { declaration: '0.1', type: 'float', difficulty: 'easy' },
  { declaration: '-3.14', type: 'float', difficulty: 'easy' },
  { declaration: '1.0', type: 'float', difficulty: 'medium' },
  { declaration: '42.0', type: 'float', difficulty: 'medium' },
  { declaration: '0.1 + 0.2', type: 'float', difficulty: 'medium' },
  { declaration: '100.0', type: 'float', difficulty: 'medium' },
  { declaration: '3.14 * 2', type: 'float', difficulty: 'medium' },
  { declaration: 'abs(-3.14)', type: 'float', difficulty: 'medium' },
  { declaration: '1 / 3', type: 'float', difficulty: 'hard' },
  { declaration: 'float(42)', type: 'float', difficulty: 'hard' },
  { declaration: 'round(3.14, 1)', type: 'float', difficulty: 'hard' },
  { declaration: '1 / 2', type: 'float', difficulty: 'hard' },
  { declaration: '2.0 ** 0.5', type: 'float', difficulty: 'hard' },
  { declaration: 'float(True)', type: 'float', difficulty: 'hard' },
  { declaration: 'float("3.14")', type: 'float', difficulty: 'hard' },
  // bool
  { declaration: 'True', type: 'bool', difficulty: 'easy' },
  { declaration: 'False', type: 'bool', difficulty: 'easy' },
  { declaration: '1 < 2', type: 'bool', difficulty: 'easy' },
  { declaration: '10 > 3', type: 'bool', difficulty: 'easy' },
  { declaration: '0 < 1', type: 'bool', difficulty: 'easy' },
  { declaration: '"a" == "a"', type: 'bool', difficulty: 'easy' },
  { declaration: '3 >= 3', type: 'bool', difficulty: 'easy' },
  { declaration: '5 != 6', type: 'bool', difficulty: 'easy' },
  { declaration: '1 == 1', type: 'bool', difficulty: 'medium' },
  { declaration: '"a" != "b"', type: 'bool', difficulty: 'medium' },
  { declaration: 'not False', type: 'bool', difficulty: 'medium' },
  { declaration: 'all([1, 2])', type: 'bool', difficulty: 'medium' },
  { declaration: 'any([0, 1])', type: 'bool', difficulty: 'medium' },
  { declaration: '"a" in "abc"', type: 'bool', difficulty: 'medium' },
  { declaration: 'bool(1)', type: 'bool', difficulty: 'hard' },
  { declaration: 'bool([])', type: 'bool', difficulty: 'hard' },
  { declaration: '"" == False', type: 'bool', difficulty: 'hard' },
  { declaration: 'not not 1', type: 'bool', difficulty: 'hard' },
  { declaration: 'None is None', type: 'bool', difficulty: 'hard' },
  { declaration: 'isinstance(1, int)', type: 'bool', difficulty: 'hard' },
  { declaration: '1 == True', type: 'bool', difficulty: 'hard' },
  { declaration: '0 == False', type: 'bool', difficulty: 'hard' },
  // None
  { declaration: 'None', type: 'None', difficulty: 'easy' },
  { declaration: 'None', type: 'None', difficulty: 'easy' },
  { declaration: 'None', type: 'None', difficulty: 'easy' },
  { declaration: 'print("hi")', type: 'None', difficulty: 'medium' },
  { declaration: '[1, 2].append(3)', type: 'None', difficulty: 'hard' },
  { declaration: '[1, 2].sort()', type: 'None', difficulty: 'hard' },
  { declaration: '[1, 2, 3].reverse()', type: 'None', difficulty: 'hard' },
  { declaration: '{}.clear()', type: 'None', difficulty: 'hard' },
  { declaration: '[1, 2, 3].clear()', type: 'None', difficulty: 'hard' },
  { declaration: '(lambda: None)()', type: 'None', difficulty: 'hard' },
  // list
  { declaration: '[1, 2, 3]', type: 'list', difficulty: 'easy' },
  { declaration: '["a", "b"]', type: 'list', difficulty: 'easy' },
  { declaration: '[True, False]', type: 'list', difficulty: 'easy' },
  { declaration: '[1, 2]', type: 'list', difficulty: 'easy' },
  { declaration: '[0]', type: 'list', difficulty: 'easy' },
  { declaration: '["hello"]', type: 'list', difficulty: 'easy' },
  { declaration: '[None, None]', type: 'list', difficulty: 'easy' },
  { declaration: '[True, False, True]', type: 'list', difficulty: 'easy' },
  { declaration: '[]', type: 'list', difficulty: 'medium' },
  { declaration: '[1, [2, 3]]', type: 'list', difficulty: 'medium' },
  { declaration: 'list("abc")', type: 'list', difficulty: 'medium' },
  { declaration: 'list()', type: 'list', difficulty: 'medium' },
  { declaration: 'sorted([3, 1, 2])', type: 'list', difficulty: 'medium' },
  { declaration: '[1] + [2, 3]', type: 'list', difficulty: 'medium' },
  { declaration: '"a,b,c".split(",")', type: 'list', difficulty: 'hard' },
  { declaration: 'list(range(5))', type: 'list', difficulty: 'hard' },
  { declaration: '[x for x in range(3)]', type: 'list', difficulty: 'hard' },
  { declaration: 'list(map(str, [1, 2]))', type: 'list', difficulty: 'hard' },
  { declaration: '[*range(3)]', type: 'list', difficulty: 'hard' },
  { declaration: 'list(filter(None, [0, 1, 2]))', type: 'list', difficulty: 'hard' },
  // dict
  { declaration: '{"id": 1}', type: 'dict', difficulty: 'easy' },
  { declaration: '{"name": "Alice"}', type: 'dict', difficulty: 'easy' },
  { declaration: '{"x": 0, "y": 0}', type: 'dict', difficulty: 'easy' },
  { declaration: '{"active": True}', type: 'dict', difficulty: 'easy' },
  { declaration: '{"a": 1, "b": 2}', type: 'dict', difficulty: 'easy' },
  { declaration: '{"count": 0}', type: 'dict', difficulty: 'easy' },
  { declaration: '{"flag": False}', type: 'dict', difficulty: 'easy' },
  { declaration: '{}', type: 'dict', difficulty: 'medium' },
  { declaration: 'dict(a=1, b=2)', type: 'dict', difficulty: 'medium' },
  { declaration: '{"1": "a", "2": "b"}', type: 'dict', difficulty: 'medium' },
  { declaration: 'dict()', type: 'dict', difficulty: 'medium' },
  { declaration: '{"a": [1, 2]}', type: 'dict', difficulty: 'medium' },
  { declaration: '{k: k*2 for k in range(3)}', type: 'dict', difficulty: 'hard' },
  { declaration: 'dict(zip("ab", [1, 2]))', type: 'dict', difficulty: 'hard' },
  { declaration: 'dict([("a", 1)])', type: 'dict', difficulty: 'hard' },
  { declaration: 'dict.fromkeys("abc")', type: 'dict', difficulty: 'hard' },
  { declaration: '{**{"a": 1}, "b": 2}', type: 'dict', difficulty: 'hard' },
  { declaration: 'dict(enumerate("ab"))', type: 'dict', difficulty: 'hard' },
  // tuple
  { declaration: '(1, 2)', type: 'tuple', difficulty: 'easy' },
  { declaration: '(0, 0)', type: 'tuple', difficulty: 'easy' },
  { declaration: '("a", "b")', type: 'tuple', difficulty: 'easy' },
  { declaration: '(1, 2, 3)', type: 'tuple', difficulty: 'easy' },
  { declaration: '(1, 2, 3, 4)', type: 'tuple', difficulty: 'easy' },
  { declaration: '("a", "b", "c")', type: 'tuple', difficulty: 'easy' },
  { declaration: '(True, False)', type: 'tuple', difficulty: 'easy' },
  { declaration: '(0, 0, 0)', type: 'tuple', difficulty: 'easy' },
  { declaration: '(42,)', type: 'tuple', difficulty: 'medium' },
  { declaration: '()', type: 'tuple', difficulty: 'medium' },
  { declaration: 'tuple([1, 2])', type: 'tuple', difficulty: 'medium' },
  { declaration: 'tuple()', type: 'tuple', difficulty: 'medium' },
  { declaration: '(None,)', type: 'tuple', difficulty: 'medium' },
  { declaration: 'divmod(7, 3)', type: 'tuple', difficulty: 'hard' },
  { declaration: 'tuple("abc")', type: 'tuple', difficulty: 'hard' },
  { declaration: 'tuple(range(3))', type: 'tuple', difficulty: 'hard' },
  { declaration: '(1, 2)[::-1]', type: 'tuple', difficulty: 'hard' },
  { declaration: 'tuple(zip([1, 2], [3, 4]))', type: 'tuple', difficulty: 'hard' },
  // set
  { declaration: '{1, 2, 3}', type: 'set', difficulty: 'easy' },
  { declaration: '{"a", "b", "c"}', type: 'set', difficulty: 'easy' },
  { declaration: '{True, False}', type: 'set', difficulty: 'easy' },
  { declaration: '{1, 2}', type: 'set', difficulty: 'easy' },
  { declaration: '{"a", "b"}', type: 'set', difficulty: 'easy' },
  { declaration: '{0, 1, 2, 3}', type: 'set', difficulty: 'easy' },
  { declaration: 'set([1, 1, 2])', type: 'set', difficulty: 'medium' },
  { declaration: 'set("hello")', type: 'set', difficulty: 'medium' },
  { declaration: 'set([1, 2])', type: 'set', difficulty: 'medium' },
  { declaration: 'set()', type: 'set', difficulty: 'hard' },
  { declaration: '{x for x in range(3)}', type: 'set', difficulty: 'hard' },
  { declaration: '{*[1, 2, 3]}', type: 'set', difficulty: 'hard' },
  { declaration: '{1} | {2}', type: 'set', difficulty: 'hard' },
  { declaration: '{1, 2} & {2, 3}', type: 'set', difficulty: 'hard' },
  // extra tricky
  { declaration: 'f"{42}"', type: 'str', difficulty: 'hard' },
  { declaration: '"".join(["a", "b"])', type: 'str', difficulty: 'hard' },
  { declaration: 'str([1, 2, 3])', type: 'str', difficulty: 'hard' },
  { declaration: 'format(3.14, ".2f")', type: 'str', difficulty: 'hard' },
  { declaration: '~0', type: 'int', difficulty: 'hard' },
  { declaration: 'int("ff", 16)', type: 'int', difficulty: 'hard' },
  { declaration: '(-1) ** 2', type: 'int', difficulty: 'hard' },
  { declaration: 'bool(True) + 1', type: 'int', difficulty: 'hard' },
  { declaration: 'float("inf")', type: 'float', difficulty: 'hard' },
  { declaration: 'float("nan")', type: 'float', difficulty: 'hard' },
  { declaration: 'sum([0.1, 0.2])', type: 'float', difficulty: 'hard' },
  { declaration: 'bool([0])', type: 'bool', difficulty: 'hard' },
  { declaration: 'not []', type: 'bool', difficulty: 'hard' },
  { declaration: '[] is not None', type: 'bool', difficulty: 'hard' },
  { declaration: 'len("") == 0', type: 'bool', difficulty: 'hard' },
  { declaration: '{"a": 1}.get("b")', type: 'None', difficulty: 'hard' },
  { declaration: 'next(iter([]), None)', type: 'None', difficulty: 'hard' },
  { declaration: 'max([], default=None)', type: 'None', difficulty: 'hard' },
  { declaration: '[*"abc"]', type: 'list', difficulty: 'hard' },
  { declaration: '[1, 2, 3][1:]', type: 'list', difficulty: 'hard' },
  { declaration: 'list(set([1, 2, 2]))', type: 'list', difficulty: 'hard' },
  { declaration: '{"a": 1} | {"b": 2}', type: 'dict', difficulty: 'hard' },
  { declaration: '{i: i**2 for i in range(3)}', type: 'dict', difficulty: 'hard' },
  { declaration: 'tuple(x for x in [1, 2])', type: 'tuple', difficulty: 'hard' },
  { declaration: 'min((3, 1), (2, 4))', type: 'tuple', difficulty: 'hard' },
  { declaration: '{1, 2, 3} - {2}', type: 'set', difficulty: 'hard' },
  { declaration: '{1} ^ {1, 2}', type: 'set', difficulty: 'hard' },
]
